### ISSUE TITLE
Is there a text typing feature ?

### ISSUE THREAD

**Issue by elig0n** [mypaint/mypaint#1012]
To add typed text to images

**Comment by jplloyd** [comment]
There is no way to this _directly_ in MyPaint. Personally I would consider it out of scope, since MyPaint's focus is on drawing/painting, rather than general illustration work. You _can_ use vector layers for this, but editing the svg/text must be done in an external application, and I'm not sure how well fonts are supported.

Although there are a ton of existing enhancement requests in the tracker, the official policy is to, from now on, try to restrict it to actual bugs and use the forums at https://community.mypaint.org to track feature requests. You can start a new thread tagged with **Feature Request**, where people can discuss and vote for it.
