### ISSUE TITLE
Japanese Calligraphy

### ISSUE THREAD

**Issue by rendaw** [mypaint/mypaint#1026]
Forgive me for the kind of inspecific issue here, I believe due to email disabling I can't make an account on the community forum (didn't get the activation email).

#### Description of the problem

I'm writing some calligraphy software and hoping to use libmypaint as the brush engine (thanks so much for splitting that out and making it easy to bundle!)

I wanted to try out some brushes live before diving in too far, so I sat down to do that.

Here's my best shot in MyPaint 1.2.something:
![image](https://user-images.githubusercontent.com/2284359/62894348-84eefc00-bd87-11e9-805a-78e48b0252b9.png)

It's a bit dry, but the blotting at the start, the dark tails, and feathering out are all good.

The speckling, while awesome, seems to be some aliasing artifact when reducing the brush size.  I updated to 2.0 because the brush was unusable at larger sizes/resolutions (and even in that example the brush is too small for the character IMO).

And in 2.0:
![image](https://user-images.githubusercontent.com/2284359/62894380-90422780-bd87-11e9-9d31-6ea794816b98.png)

I wanted to make the brush wetter, and got that result here (the hairs splitting out only is visible at higher speeds later in the stroke).  A lot of the strokes are blotchy though, which might have to do with pressure curves and some unfortunate intersection of parameters.

![image](https://user-images.githubusercontent.com/2284359/62894388-933d1800-bd87-11e9-9c6f-be7459e65b7f.png)

I used the random input to angular directional offset to get a square start to the brush, but this unfortunately seems to prevent size dynamics, and specifically shrinking at the end of the stroke since I'd need a 2nd order input (having pressure modify random modify angular directional offset).

The asymmetry of the fade in the middle of the stroke (it's always biased towards 90 degrees counter clockwise from the direction of motion) is great, but I have no idea why that's happening.  The only directional modifier is the random offset.  I'd love to be able to control that somehow with barrel rotation or tilt maybe?

Also with a normal brush I think there's some smoothing of the brush shape due to ink surface tension pooling, especially at the start, and I'm not sure that's possible here.  Increasing dabs would make the shape smoother but also more regular, and reducing dabs would make the start less squared off.

Here's the same characters drawn on real media (and, well, by someone who knows what they're doing): https://original-sho.com/blog/3109/ (scroll down to the 2nd picture)
And another example of the expressiveness of the ink brushing: https://prtimes.jp/main/html/rd/p/000000010.000014235.html (video of the technique: https://www.youtube.com/watch?v=Kz3IcyPVBwg)

Here are some other things that I don't believe are possible right now:
1. Watercolor type color pooling at the ends (and starts) of strokes.  I can increase opacity at the ends, but the dabbing causes opacity to be non-flat, or at least I didn't have success with it.
2. Non-random bristles/dabs, perhaps clumped or lopsided
3. (Splatters, curved bristle marks at fast corners, drips, canvas textures?)

I also had issues with the "fine speed" input - basically this seems to be brush size independent.  This means using the calligraphy brush with a larger size the brush fades out to nothing immediately (since the fine speed is higher relative to the brush size) and at smaller sizes it doesn't fade out at all (opposite).

Since the software I'm working on has its own input mapping automation I don't think the input things will be an issue there, but I wanted to give some feedback since doing calligraphy live digitally is pretty cool.

A couple other random parting thoughts since this isn't a super specific issue in the first place-
* It seems there's some higher-sensitivity slider mode (activated by timing?) but what about a nonlinear slider?  I've had good success with this for radius sliders in other software I've worked on, since small changes are more apparent at smaller sizes.
* What about a node graph for brush configuration, like the Blender material/compositing flows?  IMO it would help the combinatoric explosion of inputs x parameters, it would reduce the amount of information on screen, resetting parameters would be as easy as deleting nodes, and since it's essentially a user friendly programming abstraction it would allow more or less unlimited complexity.
* Is BountySource the de-facto way for people to sponsor development monetarily?

Brushes: [calligraphy.zip](https://github.com/mypaint/mypaint/files/3494315/calligraphy.zip)

#### Basic system details

MyPaint version: 2.0 MyPaint---20190622.AppImage
Operating system: Arch
Desktop environment: Openbox

**Comment by jplloyd** [comment]
_Disclaimer: I'm not very familiar with the code of libmypaint, nor an expert in all the nuances of the many brush parameters._

For the issue of combining tapering with your random directional offset (square brush), did you try playing around with the "Offsets Multiplier" setting? If you e.g. set the default multiplier (note: it's not a linear scalar) to -2.0 and set the pressure mapping to 2.0, that will allow you to control the spread by the pressure of the input.

There may be other approaches. @briend knows a lot more about this than me.

I believe your points about what is possible are mostly correct. What libmypaint does is draw dabs. Once the dabs are drawn, they stay where they are (until new dabs are drawn). There is no _physical_ simulation of paint at all. The second point might be possible to achieve, but if so, I'm not sure how.

> It seems there's some higher-sensitivity slider mode (activated by timing?) but what about a nonlinear slider? I've had good success with this for radius sliders in other software I've worked on, since small changes are more apparent at smaller sizes.

If you refer to the higher-precision input mode, it is activated by pressing shift. I also believe a number of the sliders are already logarithmic. As or non-linear mapping (I know that's not what you said), any input can be mapped according to a user-defined point-based "curve". The mappings are linear by default, but the controls to modify them can be shown by pressing the arrow beside each input slider.

> What about a node graph for brush configuration, like the Blender material/compositing flows? IMO it would help the combinatoric explosion of inputs x parameters, it would reduce the amount of information on screen, resetting parameters would be as easy as deleting nodes, and since it's essentially a user friendly programming abstraction it would allow more or less unlimited complexity.

Again, my knowledge here is a bit limited, but I think that kind of system would require a large rework of libmypaint. I'm fairly certain the library in it's current state could not support this. It would be cool to have, and personally I love graph-based setups, but it would also be a lot of work.

> Is BountySource the de-facto way for people to sponsor development monetarily?

I wasn't even aware of that page, though I remember reading a conversation about whether the project should accept donations a few years ago. It seems that bountysource has only been used for a single MyPaint issue, which ultimately came down to an upstream fix.

I don't think there _is_ a channel for outright sponsorhip, though maybe we should set something up where the money would go exclusively to project hosting & email service costs.

**Comment by rendaw** [comment]
> For the issue of combining tapering with your random directional offset (square brush), did you try playing around with the "Offsets Multiplier" setting?

Ah, I didn't think of that!  I spent 5h messing around with brush settings and thought I had reached an understanding :sweat_smile: .

> any input can be mapped according to a user-defined point-based "curve"

Just to clarify, I meant a non-linear control purely for static values (not a non-linear mapping function).  Right now for instance a 1px slider change for me jumps from 2.0 to 4.27 for the directional offset, which is a huge jump, and while the "sensitive mode" is better it still jumps from 2.0 to 2.67.

Many thanks for the reply!  I will take a look at the multiplier as soon as I have some time.

**Comment by jplloyd** [comment]
> Just to clarify, I meant a non-linear control purely for static values (not a non-linear mapping function). Right now for instance a 1px slider change for me jumps from 2.0 to 4.27 for the directional offset, which is a huge jump, and while the "sensitive mode" is better it still jumps from 2.0 to 2.67.

Ah, I see what you mean. Yes, more flexible input controls are needed, whether it be numeric input, redefining ranges, something non-linear, or some combination of the above. Definitely something to look at in the hopefully-not-too-far future (there are also some existing issues related to this on the tracker).

**Comment by rendaw** [comment]
@jplloyd Thanks!  Offset multiplier worked great!

![image](https://user-images.githubusercontent.com/2284359/62922098-8a7b2f00-bde5-11e9-92bf-fd3b5b5c696e.png)

Opacity/breakup is still a bit too sensitive, but this is pretty expressive now!

I might try twiddling a bit with dabs at super low pressure to simulate drips.  It would be awesome if you could get a stylus that had a longer mechanical movement for pressure.

**Comment by briend** [comment]
Very cool @rendaw!  It's nice to see some of those newew brush inputs/settings put to use!

I figured out the bias you were seeing.  You have the random input associated with the directional offset AND opacity, which means they are now correlated.  This is a really fun aspect that you'll probably go nuts with.  If you change the opacity/random to a "V" shape instead of a straight line, you'll see how it becomes symmetrical.  

![image](https://user-images.githubusercontent.com/6015639/62994081-f756ef00-be0e-11e9-8a7c-9dfc6c27f7e6.png)
![image](https://user-images.githubusercontent.com/6015639/62994092-08076500-be0f-11e9-971c-3375a13070f8.png)

For a lot of my brushes I use the "Custom" setting with a random input, and then use that for several settings to correlate several things at once (directional offsets and smudge buckets, for instance).

> Here are some other things that I don't believe are possible right now:
> 
>     1. Watercolor type color pooling at the ends (and starts) of strokes.  I can increase opacity at the ends, but the dabbing causes opacity to be non-flat, or at least I didn't have success with it.
> 
That sounds really, really, really hard :-)

>     2. Non-random bristles/dabs, perhaps clumped or lopsided

You can do a lot here by adding "clumps" to the random input:

![image](https://user-images.githubusercontent.com/6015639/62994464-e6a77880-be10-11e9-84d8-8b1c5a3809bd.png)


>     3. (Splatters, curved bristle marks at fast corners, drips, canvas textures?)

Splatters are kind of easy by using offsets and trying to figure out *when* you want the splatter, and then correlate several things for that moment (radius, offset, opacity, etc).  When going fast?  Randomly?  You can do clever things like have a random input with a spike, but keep it suppressed via a negative input on speed (for instance) and allow the random input's spike to emerge to create the spatter, so to speak.  Remember the inputs are "added up" for each setting so you can create deficits as well w/ negatives.

Curved bristle marks are definitely a challenge if not impossible.  The closest thing I can think of is my feather brushes that sort of place dabs in a curved way:

![image](https://user-images.githubusercontent.com/6015639/62995669-68e66b80-be16-11e9-86fa-bc418d02cf7f.png)

This uses the Stroke input as a fast oscillator in combination with offsets multiplier and. . . oh who am I kidding I can't remember how this thing works.

Drips are similar, using a Y offset to randomly place large dabs somewhere below the line or wherever.

Canvas texture is really tricky.  The GridMap settings and inputs can do a lot here if you don't mind the fact that this is a brush setting and has nothing to do with your actual background image.  I have little document on this here:

https://github.com/briend/briend.github.io/issues/5

Basically it does a modulo on the x/y to create a scalable grid that you can then apply as an input to things like opacity.  The grid size needs to be larger than the actual dabs since this effect has nothing to do with the compositing operations but simply brush settings.  I've used this to make a half-tone brush with dabs on a grid:

![image](https://user-images.githubusercontent.com/6015639/62995448-7e0eca80-be15-11e9-97d1-97898f742b7b.png)


> 
> 
> I also had issues with the "fine speed" input - basically this seems to be brush size independent. This means using the calligraphy brush with a larger size the brush fades out to nothing immediately (since the fine speed is higher relative to the brush size) and at smaller sizes it doesn't fade out at all (opposite).
>

Did you have this issue with MyPaint 2.0?  That's one of the things that changed from 1.2.  Speed should now be relative to your hand-movement only, more or less.  In older MyPaint speed was relative to brush size and not calibrated for the zoom level.

**Comment by jplloyd** [comment]
Forum registrations can now be made (and I think this was resolved fully already).
