### ISSUE TITLE
just-install repo

### ISSUE THREAD

**Issue by luzpaz** [mypaint/mypaint#1033]
Create a package for mypaint 1.2.2 when it is released on just-install:  

Official Website: https://just-install.github.io/  
How to submit: https://just-install.github.io/registry/  
The file to edit: https://github.com/just-install/registry/blob/master/just-install.json

**Comment by luzpaz** [comment]
Related #747

**Comment by jplloyd** [comment]
MyPaint 1.2.2 was a proposed solution to an Arch bleeding-edge related problem with 1.2.1, and if it were released, would never be released to windows (because there's no point, no functionality has changed from 1.2.1).

Just-install might be a great package manager (though the lack of a documentation link really puts me off) but unless someone else integrates this into the build process, it's unlikely to happen.

**Comment by odysseywestra** [comment]
Closing Issue. We will probably just distribute windows builds via Github Releases officially. If anyone wants to main distribution for just install, feel free to reopen this issue or create a new one.
