### ISSUE TITLE
No Multiprocessor support in Mypaint 2.0.0 appimage (alpha, beta, final)

### ISSUE THREAD

**Issue by OlliKn** [mypaint/mypaint#1059]
On my Dell Latitude E6530 (and all my other machines) the appimage-version of mypaint 2.0.0 does only use one processor up to 100 % an then naturally drawing stucks.
The installed version 1.2 from the mint repository uses all four processors. Other appimage-packed software (not related to mypaint) does so too. 

#### Basic system details

MyPaint version: 2.0.0 from alpha up to final
Operating system: Mint 18.3
Desktop environment: Cinnamon

**Comment by jplloyd** [comment]
Yes, I don't think libgomp is installed in the docker image we build the appimage in. I'll see to this over the weekend.

**Comment by jplloyd** [comment]
By weekend, I meant today. New builds are up on the release page: https://github.com/mypaint/mypaint/releases/tag/v2.0.0

The problem was actually not a lack of dependencies, but both a problem in an automake script and not actually using `--enable-openmp` in the appimage build script. Unless the new builds don't make use of all your cores (when using large brushes), you can close this issue.

**Comment by OlliKn** [comment]
great! thank you!
