### ISSUE TITLE
mypaint installed in /usr/local fails to find libmypaint-2.0.so.0

### ISSUE THREAD

**Issue by dimmie** [mypaint/mypaint#1067]
[⚠ This tracker is for fixing and improving MyPaint.]
[☞ Use our Community Forum for support queries, or to suggest new features: https://community.mypaint.org.]
[☞ Please search before posting to avoid duplicates.]

#### Description of the problem
I have cloned the listed dependencies and mypaint from github.
I have generated the dependencies of mypaint and installed them with PREFIX=/usr/local.
Likewise, installed mypaint as per instructions in README file.
On executing mypaint, it fails with 
...
 File "/usr/local/lib/mypaint/lib/mypaintlib.py", line 13, in <module>
    from . import _mypaintlib
ImportError: libmypaint-2.0.so.0: cannot open shared object file: No such file or directory

A soft link of the missed library from /usr/local/lib to /usr/lib fixes the issue.
It seems mypaint assumes the library to be in /usr/lib, not (possibly) /usr/local/lib.

#### Basic system details

MyPaint version:  2.1.0-alpha.0+git.ee596383
Operating system: devuan beowulf/ceres
Desktop environment: mate

#### Steps to reproduce
See above bug description

#### Backtraces or error messages
See above bug description

**Comment by jplloyd** [comment]
Well, I think the dynamic link solution is just fine, but I'll write the rest for anyone else that may encounter this problem. 

The problem is that your linker doesn't look for dependencies in `/usr/local/lib`. You can either install libmypaint in a location your linker is already configured to search in, or add `/usr/local/lib` to your configuration (either by adding `/usr/local/lib` directly to `/etc/ld.so.conf` or adding it to any file included by `/etc/ld.so.conf`).

You may also need to run `sudo ldconfig` afterwards.

Your pkg-config is set up to search `/usr/local/lib/pkgconfig`, which is why you could _build_ MyPaint (the , but not _run_ it.

I hope that clears it up.
