### ISSUE TITLE
gui/accelmap.py imports Gtk without specifying version

### ISSUE THREAD

**Issue by hosiet** [mypaint/mypaint#1079]
#### Description of the problem

```
gui/accelmap.py:17: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
```

#### Basic system details

MyPaint version: 2.0.x head (20200505)
Operating system: Debian Unstable/Sid
Desktop environment: N/A

#### Steps to reproduce

This warning should pop up during doctest or when the script is actually invoked.

* * *

Since Gtk 4.0 is just around the corner, it would be better if such import has version included so that the program can properly load Gtk 3.x instead of 4.x when they both exist.

**Comment by jplloyd** [comment]
This is only a problem for the doctests, since the `require_version` calls are all made (in `lib/gichecks.py`) before any of the binding modules are imported when actually running the program. Obviously, it should still be fixed.

Re-exporting the bindings from a local module and switching all direct imports to that one should solve this.

**Comment by jplloyd** [comment]
This is now fixed for all `gi.repository` imports in the `master` and `v2.0.x` branches.
