### ISSUE TITLE
Color Picker doesn't "release" after the shortcut key is released.

### ISSUE THREAD

**Issue by AtsusaKaneytza** [mypaint/mypaint#108]
My shortcut key for the color picker is "R." When I press the "R" key, the color picker activates.
Every once in a while, however, when I release the "r" key, the color picker doesn't deactivate for about 2 seconds.
Kind of frustrating when I think I've picked one color, but I move my tablet cursor and the color picker is still hovering over different colors on the canvas and picks something else.

**Comment by mikshaw** [comment]
I only just noticed this myself, while using Ctrl+click to get colors from a scratchpad.  I've never noticed it happening when grabbing color from the canvas.

Sometimes it locks up the picker for a few seconds, sometimes it takes a couple of tries to pick a color, but usually it works fine.

**Comment by achadwick** [comment]
**Triage note:** needs steps to reproduce, may not affect current git master. I suspect that the behaviour of the colour picker has changed recently enough for the behaviour to be quite different too.

Are there any error messages if MyPaint is run from a terminal window?

Could someone please provide some good steps to reproduce this bug? If I can't see it, I can't fix it. Even if it only shows up some of the time, I'll keep trying what you say.

Bumping to the beta cycle because I doubt it will need any string fixes, and to give it some breathing time. If no steps to reproduce are forthcoming, let's close this or defer it. About a month would seem about right...

**Comment by mikshaw** [comment]
I can't reproduce it either. What i just noticed, though, is that in git master the R key doesn't work in the scratchpad window. I never noticed that before because i use Ctrl to grab colors, which works in scratchpad (why are there two keys that do the same thing?)

**Comment by 0ion9** [comment]
@mikshaw : R and Ctrl are currently almost equivalent, but that is a regression (cf #253 ): Previously,
R would immediately pick the color and, once you released the key, drop out; this allowed more precise operation than Ctrl IMO. No pen-down or drag needed to be involved, only hover followed by key.

I've tried to reproduce this, even pummelling it with insanely fast events via `xdotool key --repeat 64 r`, but so far failed.

**Comment by AtsusaKaneytza** [comment]
this problem appears to be fixed with recent builds.

**Comment by achadwick** [comment]
Okay, I'll treat that as a wrap for this half of it.

@AtsusaKaneytza please can you paste in the exact version of MyPaint that you've been testing with recently, please?

**Comment by achadwick** [comment]
(The detailed information will be useful to others!)

**Comment by AtsusaKaneytza** [comment]
MyPaint 1.2.0-beta.0+gitexport.adc9032
