### ISSUE TITLE
Icons are broken

### ISSUE THREAD

**Issue by chexmo** [mypaint/mypaint#1085]
#### Description of the problem

I've made a fresh installation of the program from repositories and icons are not ok.
[Screen capture](https://photos.app.goo.gl/pREAPu9atBBwivEC7)

#### Basic system details

MyPaint version: 2.0.0+gitexport.af5225a
Operating system: Ubuntu MATE 20.04
Desktop environment: MATE

#### Steps to reproduce

1. Start MyPaint

**Comment by jplloyd** [comment]
Thanks for reporting. The icons have been fixed in master for a few months, and the fixed versions have been in the Debian unstable repository for a long time as well. I will leave this issue up until I have at last tried to bug the relevant Ubuntu package maintainers to update or patch the _mypaint-data_ package, which contains the icons.

Duplicates: #1064 #1082 #1084

A helpful workaround was posted in the original report: https://github.com/mypaint/mypaint/issues/1064#issuecomment-632988335

Other options include using the latest stable appimage release: https://github.com/mypaint/mypaint/releases/tag/v2.0.1 or installing the flatpak version from flathub (if you don't have any flatpak installs already, I would recommend using the appimage).

**Comment by jplloyd** [comment]
By recommendation of the Ubuntu Studio project leader, I made a second, [more exhaustive comment](https://bugs.launchpad.net/ubuntu/+source/mypaint/+bug/1878578/comments/6) on the [relevant ubuntu bug report](https://bugs.launchpad.net/ubuntu/+source/mypaint/+bug/1878578).

Not much more I can do about this personally, I'm afraid. Those who are affected by this, and have a launchpad account, can go to the bug report and mark yourself as being affected by the bug.
