### ISSUE TITLE
Scratchpad → Draw Saturation Spread: AttributeError 'Document' object has no attribute 'stroke_to'

### ISSUE THREAD

**Issue by americogobbo** [mypaint/mypaint#109]
I'm not capable to find documentation about this topic.
I've found a message when I try to use this command on Scratchpad:

Traceback (most recent call last):
  File "/home/jag/installs/mypaint-git-master/gui/drawwindow.py", line 638, in draw_sat_spectrum_cb
    draw_palette(self.app, g, self.app.scratchpad_doc, columns=column_limit, grid_size=grid_size)
  File "/home/jag/installs/mypaint-git-master/lib/scratchpad_palette.py", line 88, in draw_palette
    doc.model.stroke_to(0.008, x, y, pressure, 0.0, 0.0)
AttributeError: 'Document' object has no attribute 'stroke_to'

(mypaint:4639): Gdk-WARNING **: gdk_window_set_icon_list: icons too large

---
Ubuntu Gnome 14.04

**Comment by americogobbo** [comment]
I'm not understood completely the concept of this feature... but CIE-LCh seems ideal to build the discrete transitions between colors... is very difficult for me to understand how it works on mypaint scratchpad, building an on-the-fly palette?

**Comment by 0ion9** [comment]
@americogobbo : If you get [GPick](https://code.google.com/p/gpick/), you can experiment with gradients in different color spaces (RGB, HSV, LAB, LCH) . My own experience has been that RGB, LAB, and LCH are all necessary at different times. 

* LCH is the one I like most, but like HSV or HSL, it has some problems when dealing with greys (since they have an 'undefined' hue, one has to arbitrarily decide 'greys are this hue'. This can produce some surprising gradients)
* LAB is the colorspace that LCH is based on. Since it does not have a concept of hue, it doesn't have the problem I mentioned with greys -- it's pretty reliable, and more 'natural' looking than RGB, but a bit less 'artsy' in gradient generation than LCH
* RGB is not very helpful, but since we are ultimately working with RGB artwork, we need to be able to control things in RGB colorspace sometimes.

So personally I would suggest that LCH is a good default but Lab is probably better (more reliable). I agree with Stuart's evaluation that it does not maintain saturation, but the results he shows for LAB seem far more natural than those for LCH.

@achadwick : 
[python-colormath](https://github.com/gtaylor/python-colormath/) implements various colorspace transforms, including LAB and LCH.
Depending temporarily on that would be enough to get a prototype going, and I guess I could dig up my Python port of GIMP's RGB<->LAB transform code if you want? (python-colormath is BSD not GPL, and GIMP is the only one that I know for sure gets the transform correct -- most implementations of RGB->XYZ->LAB transform are subtly or unsubtly broken.)

What are 'blanks' here? I could see four possible candidates:

* black 000000
* white ffffff
* magenta aka 'transparent pink' ff00ff
* or any consecutive repetition of any color (I don't think this one would be a good idea; sometimes spatially arranging your palette requires you to create this type of dupe.)

**Comment by achadwick** [comment]
@0ion9 :
> What are 'blanks' here? I could see four possible candidates:

They're the special slots in a MyPaint palette:

![A MyPaint palette panel showing some blank slots highlighted with a hand-drawn ring  surrounding them](https://cloud.githubusercontent.com/assets/61299/6553872/51d7fc9e-c64d-11e4-9908-9b47491580f5.png)

they're supposed to have nice checkerboard backdrops, but that's not so obvious with this dark theme (hmm.)

(FYI they're saved in .gpl as "#000000 with a special name", and our palettes/Gnome_Palette.gpl is an example of one. You can create them by going to the palette editor (wrench icon) and clicking "Add".)

**Comment by achadwick** [comment]
Linear Y'CbCr interpolations are identical to linear RGB interpolations. Ignore that, they're [similar](https://en.wikipedia.org/wiki/Similarity_(geometry)) spaces, so a linear interpolation produces the same colours.

The maths is already worked out in our code for our existing colour spaces (which are all transformations of display RGB): see the `interpolate()` methods on [HSVColor](https://github.com/mypaint/mypaint/blob/df8f87eabe78c7765add8b1d6305c67a90ced8bd/lib/color.py#L361), [RGBColor](https://github.com/mypaint/mypaint/blob/df8f87eabe78c7765add8b1d6305c67a90ced8bd/lib/color.py#L291), and [HCYColor](https://github.com/mypaint/mypaint/blob/df8f87eabe78c7765add8b1d6305c67a90ced8bd/lib/color.py#L469) (note the comments about (relative) chroma preservation in the doctest exercise there). They have the advantage of never going out of gamut.

It's just a matter of adding in a suitable context menu for now. I'm not going to add LCH or LAB colour interpolation just yet because the transforms you need for these cannot be assumed.

**Comment by achadwick** [comment]
By the way, our HCY is a bit like a poor-person's [HUSL]:http://husl.boronine.com/ in terms of its characteristics.

(It does assume you're using sRGB's primaries though, please forgive the minor hypocrisy here!)

**Comment by 0ion9** [comment]
The visibility of blanks isn't much better with light (default-ish?) theme: 
![screenshot_473](https://cloud.githubusercontent.com/assets/115782/6554897/47807eac-c6b0-11e4-9163-d19ab2d1c109.png)

I'm not sure what colors are being used, but they seem to be drawn with low opacity. Increasing that to 60% or more opacity seems to be a good move.

**Comment by achadwick** [comment]
Split off blank slot visibility to #249.

**Comment by 0ion9** [comment]
If I understand correctly and we are mainly discussing interpolation of blanks now, then there is another thing that would need to be handled to support interpolation of blanks: DnD. Currently, blanks cannot be dragged, but once interpolation is available, dragging blanks between other palette colors would be very useful, almost essential, to using it effectively.

**Comment by achadwick** [comment]
Pasting a comment of mine from #249 that was a bit offtopic there. I think my reply crossed yours @0ion9 !

> I think runs of blanks are covered by highlighting and pressing add in the palette editor:
> 
> ![palette editor with a cell highlighted and the pointer over the add button](https://cloud.githubusercontent.com/assets/61299/6555905/7b71c1e8-c661-11e4-902b-569125555fca.png)
> 
> Though maybe a `|<---------->|` run marker could be deployed at times when a context menu might show an interpolate option.
