### ISSUE TITLE
Upgrade Python version

### ISSUE THREAD

**Issue by msdobrescu** [mypaint/mypaint#1090]
Now that Python 2 is EOL, my distro of choice, Sabayon, drops the dependent apps.
MyPaint is among them.
Python must be upgraded to 3.

**Comment by odysseywestra** [comment]
As far as I'm aware, the current version of MyPaint has no Python2 Dependencies. The building documentations need to be updated to reflect this, but everything should be fine. I'm not sure how Gentoo base distros build their applications, but it may just be a matter of updating build scripts.

**Comment by jplloyd** [comment]
@odysseywestra is entirely correct, and although it is already stated in the documentation, maybe it should be made more clear.

The actual issue here is that Sabayon is still packaging 1.2.1, which does not support Python 3, and never will. I suggest contacting the Sabayon package maintainers and ask them to upgrade `libmypaint`, `mypaint-brushes` and `mypaint` to the latest released versions (1.6.1, 2.0.2, and 2.0.1, respectively).

**Comment by msdobrescu** [comment]
I see, thank you! Sorry for the misunderstanding!
