### ISSUE TITLE
A popup (panel/window?) GUI problem

### ISSUE THREAD

**Issue by ngdangtu-vn** [mypaint/mypaint#1099]
I've use the seach for the issue from `Search Tracker...` in `Bug Detected` window, the only thing I found is feature request for popup menu.

#### Description of the problem
It happens twice in a row. All I did was open layer panel in popup mode. It happened while I was using it for a bit, maybe around 10-30 min. Despite it allows me to ignore the warning and continue to use it, I think I should report here just in case.   
Btw, I don't know if this helps, but I used a lot `Ctrl+Z`.

#### Basic system details
MyPaint version: 1.2.0 stable
Operating system: Raspberry Pi Buster 5.4.51-v7l+
Hardware: Rasp Pi 4 - 8GB edition, keyboard, mouse, monitor
Desktop environment: LXDE

#### Steps to reproduce
1. Start MyPaint
2. `L` to open Layer panel
3. Drag it out the docker
4. Start drawing

#### Backtraces or error messages
```python
Mypaint version: 1.2.0+gitexport.f62444e
System information: Linux-5.4.51-v7l+-armv7l-with-debian-10.4
Traceback (most recent call last):
  File "/usr/share/mypaint/gui/topbar.py", line 259, _togglebutton_toggled_cb(self=<topbar.FakeMenuButton object at 0xb2dbb760 (gui+topbar+FakeMenuButton at 0x25c9cb8)>, togglebutton=<Gtk.ToggleButton object at 0xb2dbb828 (GtkToggleButton at 0x29953a8)>)
                    pos_func = self._get_popup_menu_position
                    self.menu.popup(None, None, pos_func, 1, 0)
  variables: {'self.menu.popup': ('local', <bound method Menu.popup of <Gtk.Menu object at 0xb2dbb4b8 (GtkMenu at 0x2c15250)>>), 'None': ('builtin', None), 'pos_func': ('local', <bound method FakeMenuButton._get_popup_menu_position of <topbar.FakeMenuButton object at 0xb2dbb760 (gui+topbar+FakeMenuButton at 0x25c9cb8)>>)}
TypeError: popup() takes exactly 7 arguments (6 given)
```

**Comment by jplloyd** [comment]
Thanks for reporting. It's an interesting one. The code has been around for nearly 7 years, so either this functionality was never tested (unlikely) or the pygtk bindings that were used back then allowed the omission of the last argument.

I will fix this in the main branch, but there won't be any updates to the 1.2.x builds (in January, 1.2.0 will be 5 years old). I would suggest building either v2.0.1 or the latest master on your machine instead of running the old one. I think the instructions for Debian (in [`BUILDING.md`](https://github.com/mypaint/mypaint/blob/master/BUILDING.md))should work fine - if they don't, feel free to ask for help [on the forums or the discord channel](https://github.com/mypaint/mypaint/wiki/Community-and-Contacts).
