### ISSUE TITLE
MyPaint does not fully install

### ISSUE THREAD

**Issue by danichou** [mypaint/mypaint#1120]
Hi there, 

This might have been asked before so apologises if I ask the question again. 

I am trying to install MyPaint on my Lenovo laptop but the installation does not complete. The command window opens, a command starts and then it stops. 

Please could you help me figure out the issue. 

I have attached a picture of the command window. 

Thank you so much 

Dan

<img width="677" alt="MyPaint" src="https://user-images.githubusercontent.com/63809758/100278182-5d13af80-2f5c-11eb-9177-c4cd554745da.PNG">

**Comment by jplloyd** [comment]
Please provide:
* The version of windows you're using.
* The version of mypaint you're trying to install.

Sorry for the late response, I missed the notification email.

**Comment by danichou** [comment]
Hey Jesper, 

No worries :) I appreciate your reply. 

Find the requested details below:

windows 10 Pro version 1909
MyPaint is the latest version. V.2.0.1 

Thank you :) 

Dan

**Comment by jplloyd** [comment]
I can't reproduce this on a VM with Windows 10 pro 2004 (assuming you were using the 64bit installer).
Could be a permission issue, though not for the installation directory (or you would not have reached the post-install scripts stage).

Some things to try:
* Try to run the installer again and see if it gets stuck in the same place (if your laptop is on the weaker side, it might need a few seconds).
* Try to use the standalone version - [**download**](https://github.com/mypaint/mypaint/releases/download/v2.0.1/mypaint-w64-2.0.1-standalone.7z) and extract the 7z archive (using 7-zip, or another program that can handle 7z archives) and run mypaint.exe (it will take longer the first time it is run, due to some one-time setup).

**Comment by danichou** [comment]
Thanks for your help on this. 

I think next time I will just keep uninstalling and installing the programme until it works... I have run a windows update reinstalled the app and now it works... No idea why. :)

Have a good evening :)

**Comment by jplloyd** [comment]
No problem. We don't have any dedicated devs/packagers for the windows port, so it can be a bit flaky. Glad it worked out.
