### ISSUE TITLE
Reinstate 1.0-era dock button on subwindows

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#139]
Split out from #106. @AtsusaKaneytza requested:

I noticed that some useful features in MyPaint 1.0 aren't in the Windows version of MyPaint 1.1.

[...]

-The small button on subwindows so that you could dock and undock them from the sidebars was useful.

**Comment by achadwick** [comment]
**Triage note:** clear idea, but time appears to be lacking for this. Deferring until after 1.2, but happy to accept and test pull requests or code that makes this work. Needs mockups or just someone with the time to work on it, basically.

**Comment by achadwick** [comment]
There should be keyboard shortcuts for this: #624 covers that aspect.

**Comment by odysseywestra** [comment]
We could take a page from Krita's UI and just add a pop up icon in the dockpanel. If it's clicked it will undock to into window mode. If clicked while in window mode it will dock at the last place it was undocked from or at default.

![2016-0320-mockup_01](https://cloud.githubusercontent.com/assets/1840562/13909334/50b7b1e2-eece-11e5-95ba-8bfdcf24472b.png)


For #624, it will also make it simpler by only needing one shortcut key instead of two.

**Comment by achadwick** [comment]
Okay, on Windows the ability to drag out tabs has gone away for 1.2.1 and 1.3.0 due to unsolveable window management issues. In addition, due to upstream bugs, the drag preview remains welded to the top right of the screen during the drag on that window. This means that users will be reporting that they cannot drag tabs from one side of the screen to the other because (in fairness) it's become a lot harder since 1.1.

I am currently adding a new sidebar swap button for 1.3.0 to fill the perceived functionality gap.
