### ISSUE TITLE
Brushes don't always drag and drop between brush groups

### ISSUE THREAD

**Issue by AtsusaKaneytza** [mypaint/mypaint#142]
MyPaint 1.1 32-bit, Windows 8.1 64-bit
![image](http://i.imgur.com/a6Dd6mB.gif)

The gif explains it better than I do. I've tried closing and re-opening the program multiple times to try and fix it.

How to reproduce: just try dragging brushes between brush groups. Sometimes, the function will work, but most times, I'm met with this.

EDIT: I've noticed that this problem is more likely to occur when recording the desktop, either with video or gif capture software.

**Comment by achadwick** [comment]
I'm guessing this *is* a Windows thing, although I can't reproduce it in anything (including a Win7 VM). I've tried to reproduce it as described, but I wasn't able to. **Triage note:** still needs steps to reproduce, not much we can do without them.

@AtsusaKaneytza, can you retest with a more recent 1.2.0-alpha build please? This is the sort of thing that may even be fixed by that build incorporating a newer GTK - we just don't know yet. Sorry.

**Comment by AtsusaKaneytza** [comment]
Seems to be resolved in the latest release, I recently updated a brush group I made and it worked fine.
