### ISSUE TITLE
Submenus function awkwardly

### ISSUE THREAD

**Issue by iirelu** [mypaint/mypaint#143]
![buggy](https://cloud.githubusercontent.com/assets/3432543/5063405/63b39450-6ddd-11e4-894c-849037d1077a.gif)

Icons and the small triangle marker should be in the same logical "block", instead of two awkwardly functioning separate entities.

**Comment by jy2wong** [comment]
One Gtk source code download, 2 different incomplete solutions and 8 tabs of documentation later...I'm not so sure this issue is 'bite-size' :P 

To make a long story short, I've been shaving a series of yaks and (hopefully) the last thing I need to do is to figure out how `<property name="icon-name">mypaint-colors-symbolic</property>` in `gui/resources.xml` results in an icon. I got lost somewhere around `gui/factoryaction.py`. When and how does the `icon-name` property get set on the tool item?

**Comment by iirelu** [comment]
Slightly hacky, but isn't it possible to just merge the little drop-down icon with the brush/colour icons?

**Comment by jy2wong** [comment]
nope. Your choices with Gtk3 are "understand icon-name and make two buttons" (GtkMenuToolButton), "understand icon-name and make one button that doesn't understand what a menu is" (GtkToolButton or GtkToggleButton), or "allow you to make a ToolItem with a single GtkMenuButton like you really want to but fail to understand icon-name or the menu as described in `gui/toolbar.xml`" (GtkToolItem).

As far as I can tell, merging involves ripping out widget children with `remove()` and transplanting them elsewhere with `add()`, and possibly replacing the receiving widget's child element with a GtkBox first in case the receiving widget doesn't allow multiple children. The icons don't actually seem to exist as child widgets of `MenuOnlyToolButton`s during initialization and the icon-name property isn't set yet, so there's nothing to transplant in its `__init__`.

**Comment by iirelu** [comment]
I meant merging the icon into the .svgs themselves. Messy, I know.

GTK is a pain, you could try asking how to do it on Stack Overflow and hope you get an answer.

**Comment by jy2wong** [comment]
I'm not sure merging the icon into the svgs would help, since `MenuOnlyToolButton`s don't seem to be aware of icons at all until well after construction. We'd still have to know which merged-icon-and-arrow we need to replace the arrow with.

And yeah, I'm asking around the relevant irc channels.

**Comment by achadwick** [comment]
Using a GtkMenuButton, a custom icon, and defining the menu separately as an old-school GtkUIManager menu seems like the best stopgap approach. Eventually that can be migrated to popovers or GMenuModels once we don't have to support GTK <3.12.

That or we make the main button of a GtkMenuToolButton just launch the "user's favourites" panel (favourite brushes, the palette colour selector).

Unflagging as bitesize, given its yak nature.

**Comment by achadwick** [comment]
Ewwww. I remember writing this and it's horrid and overcomplex.

@jy2wong The `icon-name` property is set by GtkBuilder parsing `gui/resources.xml` and making a FactoryAction named, e.g. "BrushGroups".  When the toolbar initializes from GtkUIManager XML, it looks up the FactoryAction by its name, and asks it for a new proxy widget to go on a toolbar. The FactoryAction knows how to make new widgets based on its own name: `do_create_tool_item()` is invoked automatically for toolbars . This method goes off to GObject's registry to find a class definition using GObject.type_from_name(), hence the need for `__gtype_name__`s everywhere, but we instantiate it with a call to `gtype.pytype()` for... reasons I forget.

This has always been a very backhanded way of doing it, and I'd be glad to see the back of it.

(The long-termism issue is that GtkActions and GtkUIManager are becoming deprecated. Right now I'm *lalala* ignoring that in the name of getting a release out -- but if we're writing new stuff, a more generic approach is probably wiser.)

**Comment by achadwick** [comment]
It also makes the Windows test build (at least) look rubbish:

![the "broken image icon" is displayed for the arrow](https://cloud.githubusercontent.com/assets/61299/6431351/1c22dba6-c025-11e4-989d-4c2f17df06dd.png)

although that's probably just due to broken arrows in the Adwaita (?) theme. I think the one on the left in the image is supposed to be the leftmost toolbar's "▶" (right-facing arrow) image, not a down-facing arrow. Same widget though, probably.

**Comment by achadwick** [comment]
The toolbar menus now looks more like this:

![toolbar-color-menu](https://cloud.githubusercontent.com/assets/61299/8014157/445d884a-0bc6-11e5-91b8-876514a96159.png)

which I think is reasonable.
