### ISSUE TITLE
Bailout threshold for bucketfill tool

### ISSUE THREAD

**Issue by 0ion9** [mypaint/mypaint#157]
As it is, the bucketfill tool is too dangerous. I avoid it because if I click in the wrong place, click accidentally, or click an area I only _think_ is closed, it wastes much more of my time and memory than I would gain from using it, filling every non-closed space.

It would be good if the options included a bailout threshold slider measured logarithmically in KPixels (max value 10000?), and after filling this many pixels, the fill tool would return without trying to fill any more pixels.

**Comment by achadwick** [comment]
Hey, @iirelu 

Option 1. kinda implies that either the entire shape is visible on screen, or the fill halts and undoes itself when it goes out of bounds (really, into any tile which is wholly offscreen). That's doable; we have a tile-based driving loop in Python and a faster C++ pixel filler that operates within a tile. But is this what we want? Note that if there's a frame, we fill to the frame extents and (maybe?) always should.

Option 2. only really works when the layer to be filled is immediately above the background layer and in 100% opacity Normal mode.

I think I prefer option 1. How do we get the feedback right?

What we _can't_ do speedily is use the fill implementation to find potential routes to the screen edge on every pointer motion and set the cursor appropriately.

**Comment by iirelu** [comment]
I'd love Mypaint to have some GUI notification system for displaying user-facing error messages, for things like this. Might as well just put this on the backburner until something like that's in place (or someone else thinks of a good method of communicating this error).

**Comment by jplloyd** [comment]
The fill tool is now faster due to omitting a redundant threshold check in the old code, and _vastly_ faster for large empty areas (single allocation for opaque tiles, constant-time checks for empty tiles or once-per-tile uniformity checks). #1008 

In addition, fills taking longer than a second (currently unconfigurable, but it should be rare, even on older hardware) will trigger a dialog window that reports the status of the fill and allows the user to cancel it.

I think these changes address the core of this issue. Reopen it if I'm mistaken.
