### ISSUE TITLE
MyPaint Not Saving or Exporting PNG Files Correctly

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/mypaint#165]
I've notice this when I was working my last drawing. However, it seems to only effect when I just save it as PNG transparent(.png) and not when I save it as a Multiple PNG transparent(.XXX.png), or as an .ora. I even went back a few commits, and it seems to not change. Is anybody else having a problem with this as well?

System information: Linux-3.16.0-28-generic-x86_64-with-Ubuntu-14.10-utopic
Version: 1.1.1-alpha.20150103+git.6947ad9

**Comment by iirelu** [comment]
Huh, you're right! I guess that's been broken for a while and just nobody's noticed.

**Comment by jy2wong** [comment]
The first three images were done with 'Show background' unchecked in the layers panel and in a fresh instance with a fresh config. Files were saved by typing in the filename with no extension and selecting "PNG transparent (*.png)" in the dropdown.

First export:
![a](https://cloud.githubusercontent.com/assets/4390573/5708816/4f6b9ebe-9a62-11e4-8d37-e00bef24ca70.png)
First save as:
![b](https://cloud.githubusercontent.com/assets/4390573/5708817/52563166-9a62-11e4-8038-fe5c5d93cc84.png)
First save:
![c_orig](https://cloud.githubusercontent.com/assets/4390573/5708995/eed0652e-9a63-11e4-9272-5f432679a52c.png)

Huh. Seems like saving with transparency works the first time you try to save (by any means). I modified the third image, tried saving it immediately afterwards and got
![c_second](https://cloud.githubusercontent.com/assets/4390573/5709004/f9868480-9a63-11e4-952d-34bdc4349c3f.png)
It appears that all the transparent pixels were turned black.

The same thing seems to happen if you save something as a .ora first, then try to save as a transparent PNG.

**Comment by odysseywestra** [comment]
So I tried it again and it seems thats the ```[ ]show background```option in the layers dialog is having an effect on saving transparency.

When the ```[x] show background``` is check and I tried to export, or save it as a transparent .png, it saves it as a png with a background. When the ```[ ] show background``` is unchecked, and I tried to export, or save it as a transparent, it saves as a transparent png.

Another Odd thing I notice is when I just save or save as it as a png with background, it fills it with black. It even worse since save, just repeat what 

I renamed the bug as to better reflect it.

So far the Open Raster File is not effected by this bug.

**Comment by jy2wong** [comment]
@odysseywestra, don't suppose you're interested in testing out this branch?
https://github.com/jy2wong/mypaint/commit/035cfac4bafcf64289e2ac4473c10466f1ae6775

I haven't made a pull request because I'm 1) not yet convinced that I haven't broken anything and 2) not sure whether it's better to save PNGs with an alpha channel by default or to do something more clever (e.g. detect whether or not "show background" is checked). @achadwick ? @iirelu ?

**Comment by odysseywestra** [comment]
@jy2wong sadly I'm getting the same results as before:

Save As/Export: [ ] Show Background/transparent: Yes
Save As/Export: [ ] Show Background/nontransparent: No/Black Filled Background instead of white
Save As/Export: [x] Show Background/transparent: No
Save As/Export: [x} Show Background/nontransparent: Yes/Correct white Background

Save: [ ] Show Background: No Background
Save: [x] Show Background: Yes/ Correct White Background

**Comment by jy2wong** [comment]
Okay, I think I have a better idea of what's going on here.
When I see "PNG (transparent)", I think "write down transparency information in the png for the image I see on the screen".

If I understand correctly, when you see "PNG (transparent)", you think "save without the background", yes?

So it seems like there are actually two separate issues here.

1. when you try to save after previously saving as, mypaint sees ".png" in the filename, and decides to save the image as a PNG without the alpha channel (that is, any transparency information), resulting in a black background. This means that if you saveas a transparent PNG and then hit ctrl+s at some point, the new saved image will be black where it was previously transparent.

  The branch I linked to earlier fixes this in a hacky way, but IMO a proper fix would involve remembering whether the image was last saved as a transparent PNG or a solid PNG. I can take a stab at it, but it'll take a lot longer for me than for someone who knows their way around the codebase.

2. there's a bit of a UI snaggle. When you want to save a "transparent PNG", it's very likely you don't want the background showing up. When you want to save a "solid PNG", you expect the background to show up if you've checked "show background", and perhaps a plain white background if it's unchecked (and certainly you don't expect the "transparent" pixels to show up black).

   Currently the only difference between saving as a solid or transparent PNG is whether or not the alpha channel is saved, but this is, upon reflection, not the most user-friendly. Does the expected behaviour I described above seem reasonable?

**Comment by achadwick** [comment]
Okay, I've tested all the combinations I can think of with the updated #188. Looks good here.

|Saved as|bg layer visible|RGB/RGBA|
|-------|-----|------|
|test0.ora|yes, as layer :)|N/A|
|test1dot-png-by-ext-no-bg.png|no|RGBA|
|test1dot-png-by-ext-with-bg.png|yes|RGB|
|test2png-solid-no-bg.png|yes|RGB|
|test2png-solid-with-bg.png|yes|RGB|
|test3multipng-no-bg.001.png|no|RGBA|
|test3multipng-no-bg.002.png|no|RGBA|
|test3multipng-with-bg.001.png|no|RGBA|
|test3multipng-with-bg.002.png|no|RGBA|
|test4png-transparent-no-bg.png|no|RGBA|
|test4png-transparent-with-bg.png|no|RGBA|
|test5jpeg-no-bg.jpg|no (do get #000000 though...)|RGB|
|test5jpeg-with-bg.jpg|yes|RGB|

In the table, "with-bg" means the background was turned on in the Layers panel, and "no-bg" means it was turned off.
