### ISSUE TITLE
[Feature Request] - (pen-input-)Stroke-based undo buffer

### ISSUE THREAD

**Issue by loentar** [mypaint/mypaint#175]
Please implement stroke based Undo/Redo buffer in addition to time based.

Description: https://github.com/mypaint/mypaint/issues/174#issuecomment-70618849

**Comment by achadwick** [comment]
Could be one by just splitting the stroke on button1 press & release. Maybe proximity-in and proximity-out too.

This depends on having good behaviour for #174 because it involves more stroke splits, and therefore any accidental null-change timeslices on the undo stack will be much more visible.

**Comment by achadwick** [comment]
I guess it may be more intuitive to people to have this be the default behaviour. It'll need some testing to be sure it "feels" right though.

**Comment by martinxyz** [comment]
The most annoying thing with stroke-based undo, from an artist' point of view, is when you draw and scribble around for 5 minutes and you mess up at the end of it. Maybe it's only me, but I was never able to warm-up to stoke-based undo. When doing lots of short strokes (e.g. cross-hatching) undo basically becomes unusable for me.

**Comment by 0ion9** [comment]
" When doing lots of short strokes (e.g. cross-hatching) undo basically becomes unusable for me."
+1 on that. Stroke splitting that roughly matches the timing of your thoughts is exactly why Mypaint is currently so much nicer to use than Krita IMO.

**Comment by loentar** [comment]
Yes, when doing many small strokes time-based undo buffer is more convenient. But when drawing lineart (large strokes, often undo last stroke), stroke-based undo buffer is much more convenient.

Because of that both methods are needed. I'd use both.

Also, probably, it would be nice to have the control to switch the history algorithm on the toolbar. I understand: switching the algorithm on the fly may be hard to implement, it depends of method of storing the history data.

**Comment by achadwick** [comment]
Been reminded of this on Twitter. It's a fairly frequently-requested feature, but it looks as if it will need UI because people's expectations vary quite a bit.

My thoughts are to add a section to the preferences:

    **Undo stack**
    Split brushstrokes after:  2s [-------|------------------------------]
    Also split strokes when:  [x] pressure drops to zero
                              [x] the pen is out of the tablet's range

* The upper slider would vary from 0 to 10s.
  * Setting it to zero would disable time-based splitting, but we'd need to force one of the lower checkboxes to "on" when it transitions from >0 to 0.
  * Probably the upper one, because not all tablets generate proximity-in and proximity-out events.
* The upper checkbox would make MyPaint split on button-press and button-release as well as pressure=0, for maximum compatibility.
* The lower checkbox would make extra splits on the proximity-in and proximity-out events sent by some tablets.

**Comment by achadwick** [comment]
(A word of warning: "pressure drops to zero" is already kind-of implemented. When you're senting a series of zero-pressure events, the splitting is still stroke-based; it's just that the split time for a batch of zero-pressure events is ~0.25s as opposed to ~8s of pressure>0 drawing. Wording that is going to be tricky too.)

But having three UI elements is a little clunky. Maybe someone could counterpropose something mainly driven from a single switch or checkbox? I would still like to make the time period configurable though, but perhaps it's something fewer people are going to want to tweak.

**Comment by loentar** [comment]
IMO, two checkboxes can be combined into just one. For me as user this is the same: the pen don't touch tablet's drawing area anymore (but I understand the difference of course).

Could this be if tablet sends proximity-out, but pressure sensor is still reporting pressure? Guess only if pen leave drawing area or... user pushed the pen's rod by hand and lifted the pen up.. :laughing:

**Comment by 0ion9** [comment]
@loentar 
> Could this be if tablet sends proximity-out, but pressure sensor is still reporting pressure? 

For all of the tablets I have ever used, they are distinct: pressure drops to zero when you stop pressing.. but then, you can move the stylus away from the tablet surface up to half an inch before it sends proximity-out. 

So, to me, if the splitting occurred only on proximity-out, that would be pretty awkward, but splitting when pressure drops to zero would be fairly natural.

I guess if you meant 'when proximity-out occurs, pressure has already dropped to zero', that is true, but the reverse isn't.

**Comment by achadwick** [comment]
A very soft stroke as the user perceives it might not be registered if it contains middle points where the pressure naturally drops to zero as the device measures it. So the user might think they did

    [▁▂▂▃▃▃▃▃▂▁▁▁▁ ▁▂▃▃▃▂▁▁▁▁▁ ▁▂▂▃▃▃▃▂▁]

while the device and software register it as 

    [▁▂▂▃▃▃▃▃▂▁▁▁▁] [▁▂▃▃▃▂▁▁▁▁▁] [▁▂▂▃▃▃▃▂▁]

I guess some devices could be more prone to that, so it might be worth offering the ability to turn it off. But maybe it doesn't really matter?

**Comment by martinxyz** [comment]
Let me summarize the current implementation:

### splitting long strokes

The check in [mypaint-brush.c:1054](https://github.com/mypaint/libmypaint/blob/51fb81b/mypaint-brush.c#L1054) is (paraphrased):

    if stroke_duration_in_seconds > 4 + 3*pressure:
        if pressure is not falling:
            split_stroke()

In words: when you are 4 seconds into the stroke, an invisible pressure threshold starts rising slowly from 0 to 1 within 3 seconds. When you cross below this threshold, the stroke either has to end (if pressure keeps going down) or there will be an auto-split (if pressure goes up again). This tends to produce natural splits.

There are two parameters to tweak: time until a split is possible (4 seconds) and how long you want to wait for a better splitting point (3 seconds). Maybe one can be calculated as a percentage of the other, and the other exposed to the preferences UI. Ideally as a logarithmic slider, so you can set it to 60 years to disable stroke splitting.

### splitting short strokes

The check in [mypaint-brush.c:1074](https://github.com/mypaint/libmypaint/blob/51fb81b/mypaint-brush.c#L1074) is (simplified, for a brush that doesn't produce gaps):

    if stroke_duration_in_seconds + idling_time > 0.9:
        split_stroke()

This is executed when no dab has been painted. If you start two strokes within 0.9 seconds they will be combined.

Personally I preferred 1.2 seconds but [reduced it](https://github.com/mypaint/mypaint/commit/1e948611) as a compromise with users who think that time-based undo is a bug. Maybe this can be exposed as a slider instead of the suggested checkbox ``Also split strokes when:  [x] pressure drops to zero``.

(In case someone feels like improving the undo-split system, I think something could be gained by deciding about the undo step splits "after the fact" when the user presses undo, not while painting.)

**Comment by odysseywestra** [comment]
@loentar Could you move this thread over to https://community.mypaint.org/c/feature-requests? I'm working on cleaning up the issue tracker by move all feature requests there so we can get community feedback. If you can also set your post as a wiki that way we can edit the scope of the feature request that would be awesome as well. Don't forget to link back to here as well so I can keep track of it incase we need to reopen the issue. Thanks.

**Comment by loentar** [comment]
You're free to just close this issue if nobody else needs it.. After 3,5 years if asking.. I don't really need it.

**Comment by odysseywestra** [comment]
This probably should still be transferred over to the forums cause I have a feeling it going to be asked once 2.0 is released.
