### ISSUE TITLE
Strokes go haywire after touch input on Surface Pro 3

### ISSUE THREAD

**Issue by crydalch** [mypaint/mypaint#177]
If I keep my hand away from the screen, it draws just fine, with pressure and everything (WinTab installed). However, if I touch the screen with my palm, things go haywire, and from then on (until I re-run MyPaint), they stay screwed up even with pen input. The upper left two strokes were prior to my palm touching the screen, the others are after.

![mypaint-dev-strokes](https://cloud.githubusercontent.com/assets/458856/5845604/3b6b684c-a172-11e4-9dc4-b8abc71b852f.png)

I see it with both 32 and 64 bits, using the October 8, 2014 build from http://opensourcepack.blogspot.fr/2013/01/mypaint-and-pygi.html. I don't have this problem in MyPaint 1.0, however.

Any ideas?

Thanks!

**Comment by achadwick** [comment]
Pinging @tumagonx 
are you using anything special in your builds that isn't present in the documented MSYS2/WIN32 one? May be worth eyeballing https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-gtk3/PKGBUILD to see what the documented one does.

I'm not very Windows. I don't understand the role of "WinTab" in this, or what it is. Surely you just install the Wacom drivers and GDK will do the right thing? Maybe I'm being a little naïve here... :innocent:

**Comment by crydalch** [comment]
Hehe, yeah if it weren't for the awesomeness of OneNote and one or two other things, I'd just put Linux on this thing :) 

As far as I know, installing Ntrig's WinTab driver is all I've had to do; programs like ZBrush, MyPaint, Krita, etc...all needed the WinTab driver, but Mischief and Manga Studio all work without WinTab.

Thanks guys!

**Comment by 0ion9** [comment]
mm, IIRC Dmitri recently fixed a similar bug in Krita, related to Ntrig / Surface Pro. It was basically a switch from using one part of the WinTab API to a slightly different one. Since MyPaint doesn't interact directly with WinTab, this may well be an upstream bug in GDK / GTK.

**Comment by crydalch** [comment]
Interesting, thanks for that tip; do you know where I could submit a bug for GDK/GTK?

**Comment by 0ion9** [comment]
@crydalch https://bugzilla.gnome.org/enter_bug.cgi?product=gtk%2B

**Comment by tumagonx** [comment]
@achadwick My build use gtk 3.8.9. The last version that detect tablet properly is 3.9.3. Additionally event compression disabled right from the gdk in my snapshot release. Version 3.6 won't need patch but have issue with UI/icon theme.

@Chris I can't reproduce the haywire issue with my tab (UC-logic), it's quite usable in 32bit but in 64bit tablet did not detected at all.

**Comment by achadwick** [comment]
Related upstream bug: https://bugzilla.gnome.org/show_bug.cgi?id=743330

**Comment by achadwick** [comment]
Now that #178 is closed, does using the new MSYS/MINGW32 version of GTK (3.14.8) fix this too? :hopeful:

**Comment by crydalch** [comment]
Nope, I'm still seeing it :( I thought maybe I hadn't updated something, but I still see the problem both in the build I downloaded, and when I rebuild from source.

**Comment by achadwick** [comment]
@crydalch Okay. Do you see more than just a mouse in the Devices tab of the preferences?

I've noticed that similar issues can be caused by moving the mouse (or trying to draw with it) at the same time as moving the Stylus on the Windows platform. If you see your stylus in Prefs→Devices, try setting all other devices to "Allow: Ignore", or to "Allow: Non-painting tasks". Any change?

If you don't see the stylus in there, you're experiencing a different GDK bug I guess.

**Comment by achadwick** [comment]
@crydalch : please can you confirm whether or not you see more than just a mouse in the Devices tab of the preferences, and let me know if the workaround in the month-old comment above works for you.

**Comment by crydalch** [comment]
Woh! So sorry I never responded to this! Yeah, I'm only seeing _System Aggregated Pointer_ under Devices.

![devices_mypaint](https://cloud.githubusercontent.com/assets/458856/6511714/64e071fe-c323-11e4-8fe9-c44df33896d5.png)

I've submitted a bug against Gdk: https://bugzilla.gnome.org/show_bug.cgi?id=745697; hopefully it's a simple fix!

Thanks!

**Comment by crydalch** [comment]
Hey @achadwick, any suggestions on getting Gnome bugs noticed? That last one was shockingly fast, but the latest one I submitted (for the device reporting) hasn't been noticed at all. Any tips would be great.

Thanks!

**Comment by achadwick** [comment]
@crydalch This is a bit of an aside, but it's worth going through somewhere. Maybe something for the MyPaint wiki? I _so_ need to port that "how to fix your tablet issues" page for #242 and perhaps I should draft something for it...

-------------------------------------------

Talking with gtk people on IRC helps a lot, as does being in a position to compile and test GTK itself (because access to hardware). MSYS2 is definitely the way to go on the Windows platform for the latter: it's quite bleeding-edge with its GTK, and rebuilds with different flags are really easy. See https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-gtk3 etc. for details of how that's done, and learn a bit of [makepkg](https://wiki.archlinux.org/index.php/Makepkg). You'll probably need debug rebuilds of both glib and gtk to get any debugging done, and possibly Python too (maybe not in this case). See our CONTRIBUTING.md for some notes on the care and feeding of gdb.

* GTK folks hang out in #gtk+ on GIMPNet. They know the toolkit inside-out, but not necessarily the details of each individual system.
* MSYS2 folks hang out in #msys2 on OFTC. They know the Windows platform, and they're super-helpful about accepting patches and new PKGBUILDs too.
* (We're #mypaint on freenode, but I'm basically useless sorry!)

There's crossover between the teams, play spot the common nyms on channel!

The GTK devs may ask you to patch and test GTK, so be in a position where you can. But start by asking politely on channel and link people to the upstream bug.

The more information you can provide them the better. Especially if there are any Gdk-CRITICAL style errors in terminal output: those tend to indicate internal assertions and self-tests breaking, and can be first step in understanding a problem.

I'd recommend getting familiar with the gtk source code too, or at least pulling down a copy you can rgrep through. Pointing devs at suspicious lines of code via links into https://git.gnome.org/browse/gtk+/tree/gdk/win32/?h=gtk-3-14 helps :D

> That last one

if you mean pressure sensitivity in general from wintab, it only got rolling after some poor sap (me) started jumping up and down about it on IRC and testing things. It was known about for ages before that, and luckily it was a simple-ish fix. I hope this one is too.

Sometimes it can be a matter of simply getting stuck in (alas! but these are volunteer efforts). If you're able to put in the time (and not everyone can), that's brilliant. And good luck!

**Comment by crydalch** [comment]
Those tips are really great, thanks @achadwick! BTW, I added a bit to my last comment, but I think it didn't make it before you saw it: do you know why axischart.py seems to properly report the pen properly? This is what it says:
```
$ python axischart.py
INFO:Axischart:New device class='gtk.gdk.DeviceWintab' name='N-trig DuoSense device Stylus' (src='pen')
```
Maybe that'd provide some clues about why it's not working in MyPaint?

Thanks!

**Comment by crydalch** [comment]
Woh! Okay, so if I change one line in [mypaint/gui/devices.py](https://github.com/mypaint/mypaint/blob/599577b43e20a8f1a1c07113a20207af841062a4/gui/device.py#L106), to `Gdk.DeviceType.FLOATING` then the devices show up properly in the Preferences window:

![devices_correct](https://cloud.githubusercontent.com/assets/458856/6633910/59804718-c90d-11e4-8dec-e2df4345d706.png)

I have no idea what that means. Also ,when I try MASTER, the only device that appears is `Virtual Core Pointer`. 

However, even when the proper device is reported, I still get the same haywire strokes.

**Comment by achadwick** [comment]
Interesting. That's definitely a GDK bug, unless you've done something very odd with your config. I'm pretty that sure `GDK_DEVICE_TYPE_FLOATING`...

>|(type)|(description)|
>|----|----|
>|GDK_DEVICE_TYPE_MASTER|Device is a master (or virtual) device. There will be an associated focus indicator on the screen.|
>|GDK_DEVICE_TYPE_SLAVE|Device is a slave (or physical) device.|
>|GDK_DEVICE_TYPE_FLOATING|Device is a physical device, currently not attached to any virtual device.|
-- https://developer.gnome.org/gdk3/stable/GdkDevice.html#GdkDeviceType

... has no normal meaning under Windows. These are [Xorg/xinput concepts](http://wiki.x.org/wiki/XOrgInputDriverSpec/), not Windows ones!

(But does playing with your tablet's settings have any effect?)

I suspect you're really getting events from them even though GDK also presents them as floating.

**Comment by achadwick** [comment]
@crydalch 
Please can you try patching with

```patch
diff --git a/gui/freehand.py b/gui/freehand.py
index 77e49be..61b7408 100644
--- a/gui/freehand.py
+++ b/gui/freehand.py
@@ -418,6 +418,15 @@ class FreehandMode (gui.mode.BrushworkModeMixin,
             device = event.get_source_device()
             same_device = tdw.app.device_monitor.device_used(device)
             if not same_device:
+                src = device.get_source()
+                type_ = device.get_device_type()
+                logger.info(
+                    "Device changed: now class=%r name=%r (src=%r, type=%r)",
+                    device.__class__.__name__,
+                    device.get_name(),
+                    src.value_nick,
+                    type_.value_nick,
+                )
                 tdw.doc.brush.reset()
 
         # Extract the raw readings for this event
```

and let me know what you see when you just try painting with the stylus alone, in the normal way? I want to see all the "`Device changed: now [...]`" messages you see when you do that. There should be only one...

**Comment by crydalch** [comment]
Okay, so adding that change and reverting back to Gdk.DeviceType.SLAVE, here's what happens; when I immediately start doodling, I see this single entry in the shell:
```
INFO: gui.freehand: Device changed: now class='gtk.gdk.DeviceWintab' name='N-trig DuoSense device Stylus' (src='pen', type='floating')
```
As long as I don't pull my stylus too far off the screen, I can draw and just the N-trig stylus device is show, though it's very slow and laggy. But, when I stop drawing, then start again, I get these two alternating entries over and over again in the shell while I draw and the sketches are erratic/non-nonsensical): 
```
INFO: gui.freehand: Device changed: now class='gtk.gdk.DeviceWintab' name='N-trig DuoSense device Stylus' (src='pen', type='floating')
INFO: gui.freehand: Device changed: now class='gtk.gdk.DeviceWin32' name='System Aggregated Pointer' (src='mouse', type='slave')
INFO: gui.freehand: Device changed: now class='gtk.gdk.DeviceWintab' name='N-trig DuoSense device Stylus' (src='pen', type='floating')
INFO: gui.freehand: Device changed: now class='gtk.gdk.DeviceWin32' name='System Aggregated Pointer' (src='mouse', type='slave')
INFO: gui.freehand: Device changed: now class='gtk.gdk.DeviceWintab' name='N-trig DuoSense device Stylus' (src='pen', type='floating')
INFO: gui.freehand: Device changed: now class='gtk.gdk.DeviceWin32' name='System Aggregated Pointer' (src='mouse', type='slave')
(and on, and on, and on...)
```
I wonder why MyPaint would keep switching between the stylus and mouse so rapidly? 
Does that make any sense to you, @achadwick? Gdk bug?

Also, the only tablet settings for the N-trig pen on a Surface Pro 3 is a little utility to tweak the pressure sensitivity curve, turn off the physical start menu button (to avoid accidental presses), and choosing which One Note to open when pressing the top button. There are nowhere near as many options as a Wacom pen has, unfortunately.

Thanks for helping me track this down, it's so confusing...

**Comment by tumagonx** [comment]
Kind of remind me of old gdk2 bug, but that time wintab32.dll keep loaded/unloaded. Maybe seeing mypaint process in ProcessHacker's module tab could give hint?

**Comment by crydalch** [comment]
Interesting, thanks for the tip. I'm not super familiar with Windows/ProcessHacker, but nothing in the Modules tab jumped out at me as incorrect/broken. Some of the rows were highlighted orange (ones like  cPickle.pyd, _json.pyd); the only thing that caught my eye was this dll appeared when I started to use the pen, but wasn't there when I launched MyPaint, and only appeared when I started drawing with the stylus:
```
ninput.dll, 0x57a80000, 316 kB, Microsoft Pen and Touch Input Component
```
Here is what I could see when I first launched (without the ninput entry): https://gist.github.com/crydalch/bb468d075b916f5e10fb

But wintab32.dll, and the only other related dll I could see, DH0d.dll, didn't seem to change.

**Comment by tumagonx** [comment]
Not sure if that SurfacePro specific, I try enable Pen n Touch Features but still have no ninput when drawing (I have the file though)

**Comment by achadwick** [comment]
Definitely a bug, but in all likelihood an upstream issue. Has anyone tried chasing this one upstream (i.e. in Gtk/Gdk) yet?

------------

**Triage note:** I guess we could close this as "upstream", but I'd like to see a link to an upstream bug report first. I don't own the hardware needed to reproduce this one.

**Comment by crydalch** [comment]
Sorry, I thought I'd add the bug I created: https://bugzilla.gnome.org/show_bug.cgi?id=745697

It obviously hasn't been addressed, and I went on to IRC and asked about it. They were helpful, in that they pointed me to some places in the code to start, but I'm not a C programmer, and nothing jumped out to me as what's wrong. And they indicated that there are very few Windows Gtk+ developers, and probably fewer still that would have access to a Surface Pro 3, so it's not likely to be resolved anytime soon.

It's unfortunate, but that's where things are at right now for MyPaint + Surface Pro 3 :(

I appreciate all the help, in getting as far as possible!

**Comment by crydalch** [comment]
Hey @achadwick! Just wanted to ask a related question: is it possible to
disable all touch related input? I realize that might not solve this
problem, as gtk just sees a system pointer. But just thought I'd see if it
were possible!

Thanks!

**Comment by achadwick** [comment]
@crydalch yes, that's possible now if GDK supports it: 5cc2da4ffa7360566109f385fe87e032f749af6d

**Comment by crydalch** [comment]
Thanks for that tip @achadwick! Okay, things have sort of improved? Running under Windows 10, and using the latest git build (and those Windows instructions have improved a ton, thank you and well done!), I can see two devices. The only way I can avoid the haywire strokes, but I loose pressure in the process, is to set them up as follows:

<img width="570" alt="mypaint_devices" src="https://cloud.githubusercontent.com/assets/458856/9187661/0769b9ea-3fa1-11e5-96b6-546e278cc1b7.PNG">

Closer, but still not any closer than before! :/

It appears that GDK has improved somewhat under Windows, it detects the N-Trig stylus with less effort. Do you have a way of contacting the win32-gtk devs directly? The last time I tried to go that route, through the chatroom, I could only get a hold of Linux developers...

I should add, the reason I'm trying again, is a certain combination of Windows 10, newer Wintab-Ntrig drivers, and turning off *Flicks* in the Tablet settings allows me to use MyPaint 1.0 alongside Mischief without any issues. Hopefully, the good fortune can continue with 1.2! :)

**Comment by achadwick** [comment]
> Do you have a way of contacting the win32-gtk devs directly?

Raising it through their bug tracker and yelling at the devs on IRC is the best bet. You could try seeing if you can get Carlos again: email per <https://git.gnome.org/browse/gtk+/tree/gdk/win32/gdkdevice-wintab.c> ?

In this case, GDK support for listing tablet devices initially is a bit lacking. That list above is actually auto-discovered  by MyPaint right now :neutral_face: Still, at least it lists both 

On the other hand, that "ignore" is literally just telling MyPaint to ignore events marked as coming from that device: it doesn't disable the device in any system-mediated way (and shouldn't). Do you get pressure again (plus position glitches) when both are set to "any task"? because that would tell us something.

One other things to try:

* Does the tablet's drivers have any mapping that sets it to "window" mode, i.e. the tablet area corresponding to the active window? Turn this off, or make it "screen" (screenshots welcome if you find it) (old, but I don't think anyone has mentioned it for this)

**Comment by achadwick** [comment]
@crydalch It may not solve this problem completely, but can you test out the latest master? That ab2bb78ae81efeebd563f5759239c41ccfaa82f8 commit may help this problem quite a bit as well as solving the other issue it was targeted at.

**Comment by crydalch** [comment]
Thanks for the heads up @achadwick 

I just gave it a go, and it does seem to resolve the strokes going haywire. I don't have pressure sensitivity, and the strokes sometimes lag, especially when I draw quickly. But they don't go haywire, so things are definitely in a better place!

I'll open an issue for the pressure sensitivity, since it's a different problem.

Thanks, and well done to you and everyone working on this!

**Comment by achadwick** [comment]
Reopened, because ab2bb78ae81efeebd563f5759239c41ccfaa82f8 was reverted.

**Comment by achadwick** [comment]
@crydalch Sorry to reopen this one. Would you be able to test latest master against latest MSYS2 GDK? People are asking in the forums about Surface Pro support.

**Comment by achadwick** [comment]
Closing again. No feedback on this one.

**Comment by odysseywestra** [comment]
@achadwick I just bought a HP tx2 that use N-trig hardware and I'm experiencing the same issue on Antegros Linux on latest git version of MyPaint.  So what do I need to do to diagnose this issue so it can be resolved upstream?

**Comment by odysseywestra** [comment]
Problem seems to go away when I tell MyPaint to ignore the touchscreen as an input in edit preferences.

**Comment by odysseywestra** [comment]
However, when I physically touch the screen with the pen hovering, it will register and draw on the screen. So I think the GDK is having trouble telling the difference when the I touch the screen and when the pen is in use. This is how `xsetwacom --list devices` sees the N-Trig hardware.

```
[albert@Odyssey-Linux ~}$: xsetwacom --list devices
N-Trig Pen stylus                                   id: 11   type:  STYLUS
N-Trig Pen stylus                                   id: 13   type:  STYLUS
N-Trig Pen eraser                                   id: 19   type:  ERASER
N-Trig Pen pad                                      id: 20   type:  PAD
N-Trig Pen eraser                                   id: 21   type:  ERASER
N-Trig Pen pad                                      id: 22   type:  PAD
```

**Comment by achadwick** [comment]
@odysseywestra 
Since the original report is Windows-specific, let's open a new issue about it to keep things more easily searchable - but references back to this one to say that the effect looks similar would be useful!

Interesting that the N-Trig stuff is considered a Wacom tablet. Is it handled by the Linux Xorg Wacom driver? The X11 logs will know, I guess. Presumably the touchscreen is considered its own device, which would account for the weirdness.

The output of `xinput list` would be useful in the new report, so we know the names of everything.
