### ISSUE TITLE
Clipping group

### ISSUE THREAD

**Issue by loentar** [mypaint/mypaint#181]
Please implement clipping group feature similar to SAI. This feature is extremely useful when shading.

```
  [ [v] some other shadow ] - clipped to "some other layer"
  [ [ ] some other base ]
  [ [v] highlight ]  - clipped to "base"
  [ [v] shadow-dark ] - clipped to "base"
  [ [v] shadow ] - clipped to "base"
  [ [ ] base ]
```

All immediate layers which is above of base with "clipping group" check enabled will be clipped to "base" layer.

Currently this feature can be done using masks, but you must have two base layers (one for mask) which is inconvenient:

```
[ Group ]
    + copy of base - mask. Mode: Destination In
    + shadow. Mode: Normal/Darken/etc...
    + base. Mode: Normal
```

And to reproduce the first scheme you must have a mask for each layer:

```
[ Group ]
    + copy of some other base - mask. Mode: Destination In
    + some other shadow. Mode: Normal/Darken/etc...
    + some other base. Mode: Normal
    + copy of base - mask. Mode: Destination In
    + highlight. Mode: Normal/Darken/etc...
    + copy of base - mask. Mode: Destination In
    + shadow-dark. Mode: Normal/Darken/etc...
    + copy of base - mask. Mode: Destination In
    + shadow. Mode: Normal/Darken/etc...
    + base. Mode: Normal
```

It's too complicated..

**Comment by achadwick** [comment]
This sounds way too complicated to do for 1.2. Postponing.

**Comment by 0ion9** [comment]
@loentar I think you make this sound more complicated than it is, because in line one of your first list you refer to the unlisted layer "some other layer". I think you may have meant "some other base".

Overall I would say your proposal needs more specifics. For example, is the clipping mask used supposed to clip to the next layer below it in the stack that has a 'destination in' mode, counting only the current group, not parent groups etc?  Then it ought to be relatively simple to introduce a layer of code that filters such a layerstack into the final layerstack that needs to be rendered.
OTOH, if the behaviour can transcend the current group level, then you definitely need to demonstrate how it should behave in a greater variety of cases.

**Comment by loentar** [comment]
Oh, yes, sorry for typo. I meant "some other base". Of course all the layers in the layer group is clipped ONLY to the one base layer which is below of it. Only the layers in the group is clipped, I don't expect any other interaction between layers. "base" and "some other base" is a just two independent layers like without shading, they don't interact unless you change the Normal mode.

Please see on the picture what I mean: https://drive.google.com/file/d/0BwvdX1pBENi1QWJzY3Z6NEliVUU/view

Not a problem if multiple bases cannot be easy implemented within one layer group (due to stack), It's ok if it will be in separate layer groups (Group 1 for "base", Group 2 for "some other base"):

```
  [ Group 2 ]
      [ [v] some other shadow ] - clipped to "some other layer"
      [ [ ] some other base ]
  [ Group 1 ]
      [ [v] highlight ]  - clipped to "base"
      [ [v] shadow-dark ] - clipped to "base"
      [ [v] shadow ] - clipped to "base"
      [ [ ] base ]
```

**Comment by 0ion9** [comment]
Thanks for the image, that definitely clarifies things.

The issue with multiple bases in one layer group is not a programming one (no matter how many masks you have, each operation is a simple transformation on a graph), rather a UI one : the idea 'layers in a group may be clipped to the bottom layer in that group' is easy to understand, whereas if you allow multiple clipping layers, some way to indicate which clipping layer is used by which layer is needed.

I'd prefer to keep things simple so that if someone wants multiple clipping layers, they make multiple subgroups instead.

**Comment by loentar** [comment]
I've implemented the new blending mode "Destination Atop" which resolves the issue for me. Link to recommendation: http://www.w3.org/TR/compositing-1/#porterduffcompositingoperators_dstatop

*patch is here:* https://gist.github.com/loentar/bb7ccdda021f33b63516

To achieve the clipping effect base must be placed as top layer with "Destination Atop" mode applied.

Example of use:

  [ Group ]
      [ base / mode "Destination Atop" ]
      [ highlight ]  - clipped to "base"
      [ shadow-dark ] - clipped to "base"
      [ shadow ] - clipped to "base"

**Comment by achadwick** [comment]
I think I have an intuitive dislike of the base having to be at the top of the stack. Couldn't

* [Group (Normal)]
  * [Group (Source Atop)]
    * Highlight
    * Shadow-Dark
    * Shadow
  * Base (Normal)

do the job instead?

**Comment by 0ion9** [comment]
+1 on src-atop . Reading the dest-atop and src-atop descriptions, it took me ages to work out it's application to masking, whereas src-atop's application was immediately obvious.

Especially if you want to use nested groups to clip several groups to one mask, source-atop seems easier to follow.

**Comment by loentar** [comment]
@achadwick yes, looks much better! If you don't mind I can implement src-atop as well. By spec it looks slightly easier to implement than dst-atop.

Can I add it then into existing merge request?

**Comment by achadwick** [comment]
@loentar Sure, just push onto the pull request's branch and it'll auto-update. If it gets messy there's ways of tidying it up.

We do need to get some discussion rolling on the CREATE list though.

**Comment by achadwick** [comment]
Now I understand the problem and we've got some patches in the pipeline - I had a real aha! moment when code came along, thanks for that - I think we should try to get this into 1.2.

Start of discussion thread on the CREATE list: http://lists.freedesktop.org/archives/create/2015-April/005038.html - hopefully that'll just be a formality since the W3C have helpfully done all the dirty work.

--------------------

(Aside: one day we really must make "Group Clipped by Bottom Layer", "Masked layer", and "Masked Group" available as shorthands for these masking structures. The layer tree implementation should be flexible enough to do this even now, and we already have some distinctions between raw OpenRaster XML and MyPaint's user-facing internal representation.)

**Comment by loentar** [comment]
OK, I understand.

Nevertheless, here is new blending mode "Source Atop".

**Comment by achadwick** [comment]
Okay, merged #284's changes since it's been out there for discussion for the best part of a fortnight :)

Here's a test .ora:

* ![atop1.ora](https://cloud.githubusercontent.com/assets/61299/7221194/bfd07c56-e6d9-11e4-9134-5ebb8c475298.png) (download and rename to .ora)

And its expected output:

* ![atop_good](https://cloud.githubusercontent.com/assets/61299/7221160/7628ee9a-e6d8-11e4-82e8-f9d27659e440.png)

The weirdness of having to nest groups aside, I think this is closed now. Please test the updated master and let me know if more is needed. Please raise any UI suggestions as separate issues - they're only likely to be addressable in the next release after 1.2.

**Comment by loentar** [comment]
I tested new blending modes (with your fixes) for days, and it working as expected. Now performing the shading is much more convenient than before. Actually I use dst-atop, because it does not require to create separate group, has more compact appearance and faster in layer organization. I don't feel any inconvenience when the base layer is above to the others - this is a matter of habit.
Thank you very much.

**Comment by achadwick** [comment]
Found and fixed a glitch when the alpha < 100% on the layer woth the *atop* mode:

![glitchies](https://cloud.githubusercontent.com/assets/61299/7380506/22d8c3be-edf4-11e4-8cc6-c5ab2d92ce3b.jpg)

Fix is in as 053fddd2d1f728e8686067ca236ecee85405b893.

**Comment by achadwick** [comment]
@loentar BTW you'll find that "Destination Atop" and "Destination In" are slower in use than the other modes when adjusting opacity. The glitch pic above is excerpted from a test file of mine that demos all the modes, and it looks like too many screen updates are being sent out right now...

**Comment by achadwick** [comment]
Anyway, fun glitch fixed and the modes are technically OK now I think. Thanks for the code and the testing!

**Comment by MR4Y** [comment]
Well, unfortunately, this way is not intuitive nor practical for people coming from other painting programs. It takes too long for the whole group workflow to be set up and even after reading all the issue commentaries with the pictures, I still have no idea how to use it for what I want nor when to use what.

**Comment by loentar** [comment]
Actually destination atop mode is easy in use (IMO it's easier and faster in use than source atop).. You just need to understand the logic.

Here is a small example how it look, please see layer names:

![image](https://cloud.githubusercontent.com/assets/4038431/14226312/870c8574-f8e7-11e5-9184-f2cf1d1f9413.png)


I'm placing the base as top layer in group and set "Destination Atop" blending mode to it. Other layers: cell shading, gradient shading, highlights, etc.. I place under it. 

In destination atop mode base clips all the layer underneath and desired effect is achieved.


Here is how it look when base in normal mode.

![image](https://cloud.githubusercontent.com/assets/4038431/14226334/3586e892-f8e8-11e5-9a88-f64e538cef7b.png)

Here is example on how to use it (unpack it and open in mypaint):

[example-dest-atop.zip](https://github.com/mypaint/mypaint/files/200819/example-dest-atop.zip)



The only problem when using source/destination atop is: blending modes of bottom layer does not work on base (but upper layers does work). But I don't care, because my lower layer is always cell shading without any blending mode.

**Comment by MR4Y** [comment]
Problem is that this is backwards from how every other painting program under the sun does it. And you can't use blending modes on the layers that are clipped under your mask, you are forced to group your layers (which can lead to workflow slowdown, especially when you have groups inside other groups and so on.). So, while MyPaint is a great tool for that traditional look, I'll have to rely on krita for shading in the mean time.

**Comment by achadwick** [comment]
Patches welcome. Discussion's welcome too, but let's get some additional eyes on it: <http://community.mypaint.org/> maybe?

**Comment by MR4Y** [comment]
I'm not a programmer. 

I'm sorry, but it seems counter productive to make an account just to post an issue that probably will be overlooked. Plus I'll never use it anyways after that.

**Comment by achadwick** [comment]
Our community forums are kinda _for_ people who aren't programmers. You can sign in with your github account over there too... :smile:

<small>_(This is quite an old closed issue, and the topic is drifting. I'm locking it now. Tell us how the new proposed feature should work in the forums, or raise a separate issue please. I'm only doing this to keep the tracker tidy.)_</small>
