### ISSUE TITLE
Filedialog: not so native (Windows) behavior in sorting the items

### ISSUE THREAD

**Issue by tumagonx** [mypaint/mypaint#195]
First: The folder sorted together with files, should be "folder before files"
Second: Drives should be sorted in driveletter not drivelabel

Not serious thing, but in case someone complain here is the upstream bugreport: 
https://bugzilla.gnome.org/show_bug.cgi?id=741018

**Comment by iirelu** [comment]
The first one isn't windows specific and I find it annoying as well.

**Comment by iirelu** [comment]
[Here's how to fix the first one app-wide](http://stackoverflow.com/questions/28157314/programmatically-change-filechooserdialog-to-list-directories-first-with-python). Where should that snippet go? What's the best place for init stuff like that?

**Comment by tumagonx** [comment]
@iirelu see the above bugreport for 1st issue workaround, I think gtksetting would be better

**Comment by achadwick** [comment]
(I prefer mixed because I love reverse chronological sorting. The POSIX fs semantics make mixed folders and files nice with that sort order: work in a directory in most things and the folder bubbles to the top.)

Linux users should change `org.gtk.Settings.FileChooser.sort-directories-first` globally in `dconf-editor`. **MyPaint is not a UI for changing global settings**.


I don't think there's an equivalent `GtkSettings` property for it. The nearest thing to that which I can find is a flag saying which backend to use:

```python
>>> from gi.repository import Gtk
>>> s = Gtk.Settings.get_default()
>>> [n for n in dir(s.props) if "choo" in n]
['gtk_file_chooser_backend']
>>> s.get_property("gtk-file-chooser-backend")    # mine is None, guess that means default
>>> [n for n in dir(s.props) if "file" in n]
['gtk_file_chooser_backend', 'gtk_recent_files_enabled', 'gtk_recent_files_limit', 'gtk_recent_files_max_age']
>>> for n in s.props:
...     print n
... 
<GParamInt 'gtk-double-click-time'>
<GParamInt 'gtk-double-click-distance'>
<GParamBoolean 'gtk-cursor-blink'>
<GParamInt 'gtk-cursor-blink-time'>
[...]
```

If the GTK chooser or any other backend is sensitive to GtkSettings, let me know.

We may be able to spin some sort of RAM-only GSettings override with [g_settings_delay()](https://developer.gnome.org/gio/stable/GSettings.html#g-settings-delay). However that would prevent us from ever using GSettings in the future.

It's also possible (with a lot of work) to write custom GSettingsBackends. But *ugh.*

I think this one is best left to Linux users to set globally, and left to upstream to resolve for Windows.

This isn't a bug in MyPaint, so this issue should be closed IMO. If anyone has a good workaround though, please submit a PR referencing this issue.

**Comment by iirelu** [comment]
Ah, I didn't realise it was system-wide. Yeah, maybe not then.

Adding a configuration option for something and making it off by default is a very GTK thing to do, I feel. But yeah, there's nothing we can really do here, so I'll close this for now.
