### ISSUE TITLE
Frame Tool Resolution Block

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/mypaint#217]
In the frame edit tool, the resolution (DPI) option doesn't work when pixels is used as the metric for canvas size. This confused someone on google plus which led me to report this issue. I think a fix for it would be to block the resolution option when pixels is used for canvas size.

**Comment by achadwick** [comment]
Huh, maybe I should finish this thing...

![preview screencap of a frame sizing dialog I'm working on](https://cloud.githubusercontent.com/assets/61299/6360053/1f7376a8-bc6f-11e4-8aa2-9376bd9f90ba.png)

(Don't get your hopes up, it's only a preview but I thought you'd appreciate a sneak peek. Consider that "advanced mode" or something!)

**Comment by achadwick** [comment]
As for the current dialog,

![screencap of the current dialog from git master](https://cloud.githubusercontent.com/assets/61299/6360147/c2b62004-bc6f-11e4-8168-296852cbb63b.png)

it could probably do with some similar section headers, spacing, and a "DPI" label like the light-theme-variant preview above, but I really don't want to make the entry mysteriously inactive - that would be confusing to users too.

I'll see what I can do. There's an element of WONTFIX about this, but the spacing and labelling could probably be improved a lot.

**Comment by achadwick** [comment]
Closing WONTFIX because the DPI you see there is the nominal - and yes, almost meaningless - DPI setting that gets saved into an OpenRaster file. This UI is how you adjust that _document property_, even when you are measuring your _frame_ in pixels.

We can't grey out ("block") the resolution entry (set it as insensitive).

However I've bumped up the spacing and put some headings in. If it looks wrong, or if it's still confusing, please raise a new issue.

**Comment by odysseywestra** [comment]
Yeah, I understand since you are working on a potential replacement. So,
what you have looks pretty good. I appreciate everything you are doing for
mypaint. Keep up the great work.
