### ISSUE TITLE
Feature proposal - design proposal, xSheet dock that coexists with the current layer's dock as an alternative way to manage layers, instead of overriding it!

### ISSUE THREAD

**Issue by blurymind** [mypaint/mypaint#222]
Hi,
I initially made this proposal for Drawpile, but since the gist of the idea is using layer data to create an animation workflow and it has already been started but never finished and kind of broken in mypaint, here is my proposal for a simple and clean design that allows for both a traditional Layer dock and a true animator x-sheet dock to co-exist in perfect harmony! :)

I think that if you want to use the layers data to animate, you will have to create an alternative way to edit/manage the layers in Mypaint.

A new X-sheet dock is needed to address the animation workflow!

I put down some time to create a proposal design and a mockup. Please let me know what you think and if some stuff in there is unclear. :)
Click for full screen.

![xsheetindrawpile](https://cloud.githubusercontent.com/assets/6495061/6405150/a402cf9e-be28-11e4-8438-8707bd95231a.png)

Under the hood x-sheet dock is just managing the same layers that are in the layer's dock. It's just doing it in a radical new way!

> key pose drawings can occupy frame ranges. So When you extend a drawing to occupy three frames instead of one, the x-sheet dock technically creates two new copies/clones of that layer above or bellow it (depending on which of the two arrows the user dragged)
> when playing from xsheet, mypaint can operate in solo layer view: like the "hide" feature, but hides all other layers except the selected one.
> Onion skin mode: hide all layers above the selection and show the ones below it with adjusted opacity

note for the mockup proposal: a frame that doesnt contain a drawing yet could be just the number of the frame, but color coded.. or it could be a symbol [-] or [0]  or something.
The +(add) MENU should say "add drawing" instead of "add frame". Replace the word "frame" with "Drawing" there. I will update it later if you like the proposal

The ability to scribble annotations is very very nice, but not a must have.

> Copying and pasting+insert drawings could be done with the right click menu.
> Deleting a drawing should move all the drawings bellow it upwards- filling its spot, so as not to have a missing drawing in its place.
> moving a drawing in the x-sheet could be done by just dragging it.

Other features needed:

> Export to animated GIF
> Export individual layers (this already exists in a way: ORA files are actually zip files containing the >layers in PNG format)

**Comment by achadwick** [comment]
Hi! Thanks for the mockups.

Right now, animation is very far outside what I consider the primary use of MyPaint, and we're chasing the 1.2 release. However if we get a plugin system up and running first (see issue #209) it might be possible to add a panel like that if someone were to write it.

I can't contribute any time to this, and I don't think we should be accepting any patches to do it for now. Later, maybe.

**Comment by blurymind** [comment]
ah I see. Thats alright :)

It was worth a shot

**Comment by iirelu** [comment]
Yeah, anything related to animation is way out of scope for Mypaint. Tiny tweaks we can make to improve the experience, maybe, but big new features dedicated towards animation are a no-no.

**Comment by martinxyz** [comment]
Are you aware of this branch from Manuel Quiñones: http://wiki.mypaint.info/Animation#X-Sheet_MyPaint_branch

**Comment by blurymind** [comment]
I am aware of it, but it has a terrible interface :)

**Comment by mikshaw** [comment]
I agree the x-sheet branch has a terrible interface, as does dopey (hoping there's a plan to improve that), as does gimp. Using layers as frames, rather than in addition to frames, is a bad idea that immediately removes a very important feature of digital art (gap gets around this by using separate files as frames, which in my opinion isn't much better).

If mypaint ever has animation features (i assume it  would be a plug-in, considering the apparent keep-it-simple approach for mypaint), i seriously hope it uses a proper timeline that doesn't interfere with the basic features of the original program.

In the meantime i will continue to follow pencil2d, which in spite of its current unstable condition is still the most promising open source 2d raster animation package available.

**Comment by blurymind** [comment]
Drawpile's author has created a very nice and clean implementation :
https://github.com/callaa/Drawpile/issues/180

Get the latest build from github and give it a try.

**Comment by blurymind** [comment]
Pencil2d is in a very stale state for months now. The latest build from github has many issues too.

**Comment by odysseywestra** [comment]
Closing this since this is really out-of-scope for MyPaint. @blurymind If you still want to see this implemented, I would post this on our [Community Fourms Feature Requests](https://community.mypaint.org/c/feature-requests) So that if we implement plugins, this would be a good one for someone to work on.
