### ISSUE TITLE
Inking tool drops out when color or brush size is changed

### ISSUE THREAD

**Issue by 0ion9** [mypaint/mypaint#226]
Not sure what to say about this other than: it does, and this is somewhat surprising.

**Comment by achadwick** [comment]
(This refers to the newly added gui/inktool.py at eb76974)

* What do you mean by "drops out" exactly?
  I assume this means that you stay in the mode, but control points and buttons go away. If that's the case, I think this is working as designed: these actions cause checkpoints, and checkpoints cause pending changes to be flushed to the canvas. A current ink tool curve is one big pending change.
* What did you expect to happen when you changed the brush colour?
* If it's different, what did you expect to happen when you changed the brush size?

**Comment by iirelu** [comment]
I'd have expected the stroke colour to change when I changed it and for the brush size to be scaled accordingly.

It's also pretty weird how right click seems to make an invisible stroke.

**Comment by 0ion9** [comment]
Yes, +1 on what iirelu said: I expected the line to be redrawn with the new parameters. 

I had this expectation because of two reasons:

a) This is how most other brush tools work when brush settings change, and 

b) being able to globally modify the thickness of the line is pretty important IMO.

(tweaking the color is much less important IME, but I took the time to test it because it's a brush parameter too)

**Comment by achadwick** [comment]
Okay, if that's what people expect :)

Current thinking: instead of checkpoint()ing normally, inktool should roll back its pending changes before the super()call and re-render them after with any changed brush settings. That way you get new colours or brush sizes.

But there are edge cases. Currently the code does the safest thing, which is to commit the pending stroke before any brush change, leaving the mode "downwards", **or any layer context switch**. That means I'll need to rejig the semantics of checkpoint(): you can't replay an ink tool brushstroke onto a layer group or a vector layer!

Also I'm guessing that if you're tweaking ink nodes but then decide that the stroke just looks wrong no matter what, you _probably_ want Undo to discard the the ink line, not: undo what happened immediately before then replay the ink line you didn't like :D
