### ISSUE TITLE
Scratchpad detached tab

### ISSUE THREAD

**Issue by americogobbo** [mypaint/mypaint#244]
When you've the tab detached of normal position, for example, you put over canvas or another screen, is not possible to move the scratchpad canvas with 'space+mouse cursor'. This behavior is normal?

**Comment by achadwick** [comment]
What OS, desktop environment, version of MyPaint?

**Comment by americogobbo** [comment]
Ubuntu Gnome 14.04 and the last git master release: 1.1.1-alpha.20150306+git.6b3a1e7

**Comment by achadwick** [comment]
Thanks!

Reproduced with {Debian testing+unstable (2015-03-08), GNOME 3.14, git master at 6b3a1e7f21e6cc597baa31a48f6947ced9f760e3 as above}.

If I detach the scratchpad, holding Space and *just* moving the mouse (no click) sometimes works, and sometimes doesn't. When it works in this config, it doesn't cancel properly when the space bar is released: you need to click to end the drag.

Docking the scratchpad restores the expected behaviour.

**Comment by americogobbo** [comment]
OK, works.
The features on bottom toolbar are working too, but they appear as disable (tab not focused) ... but this is a behavior of all detached tabs... I've noted now... is normal? or I need open another issue for it?

**Comment by achadwick** [comment]
That's a consequence of the window not accepting keyboard focus (with some gtk3 themes?). Raise it as a separate cosmetic issue please: annotated screenshots of the windows will help clarify the problem to other readers!

**Comment by americogobbo** [comment]
I've made a small video to show this behavior:
https://www.youtube.com/watch?v=L8rthkYOnjs
When you use space key to drag the scratchpad canvas focused it don't works... but if you click on mypaint canvas is possible to drag the scratchpad canvas.
