### ISSUE TITLE
Tabs detached and focus appearance problem 

### ISSUE THREAD

**Issue by americogobbo** [mypaint/mypaint#247]
When the tab is detached it appears no focused always... but works normally.
The screenshot is made over the mypaint canvas.
Ubuntu Gnome 14.04 and MyPaint Git Master - last release.

![detached-tabs-not-focused-mypaint](https://cloud.githubusercontent.com/assets/8180638/6554395/f9bbe2f4-c639-11e4-839e-e1a52a9acaa1.png)

**Comment by achadwick** [comment]
(That's the default Adwaita theme, right?)

I think the cure risks being more problematic than the disease here. It's happening because our detached tab windows currently [reject keyboard focus](https://github.com/mypaint/mypaint/blob/50a737b69a0772526b09d120b80f17dd8362604a/gui/workspace.py#L1742) for window-handling reasons in other WMs which I barely remember (but it's probably the reason mentioned in [gui/workspace.py:1821](https://github.com/mypaint/mypaint/blob/50a737b69a0772526b09d120b80f17dd8362604a/gui/workspace.py#L1821)).

We should review this though; I'll need to mess around with Xephyr and Metacity again I guess. Maybe metacity just isn't important enough to bother with these days though...

And we need to test Windows (the OS) too.

Thanks for flagging this one up for our attention.

**Comment by mikshaw** [comment]
Maybe this is off-topic (or uncalled for) but why code to accommodate bad programming in window managers? This has been going on for years, if not decades, in so many programs, and it makes no sense to me. If your code is solid and according to standards, then the window manager devs should be held responsible for their software not behaving the way it should.

**Comment by achadwick** [comment]
@mikshaw I know, right?

But then people complain, and the WMs' interpretations of the standard might be quite valid to them, and it's too much to ask anyone to chase bugs on ALL THE WMs, and you have to deal with stuff like Windows which isn't ICCCM-compliant and never will be, and users *still* ask for stuff like #245 even when it's already implemented and even if they're running an old version it tells you how much it matters to them, and, and, and...

(There's a good reason to review this old hack though, so we'd better)

**Comment by achadwick** [comment]
Looking at this again in Metacity 3.14.2 (Xephyr), GNOME 3.14 (Debian testing+unstable shortly before the Debian Jessie (8.0) release), Windows 7 64-bit, and Unity 7.2.2 (Ubuntu 14.04 LTS), I can't see any reason for the code above any more. We handle keypresses anyway - feeding them to the main window - so tool stack windows will do the right thing without those bits. Hopefully.

Bumping to 1.2.0-alpha - let's get people to test this out a bit. We can always roll it back if necessary.

**Comment by achadwick** [comment]
Spoke too soon. The second one at least is still needed (in GNOME!)
