### ISSUE TITLE
[Feature Request] - Add numbers to Tool Options sliders for Freehand Drawing

### ISSUE THREAD

**Issue by Deevad** [mypaint/mypaint#25]
Hi, 

**Problem:**
The Tool Options in Freehand Drawing mode display a series of sliders ( see the screenshot bellow ):
![screenshot from 2014-06-26 22 52 19](https://cloud.githubusercontent.com/assets/4021867/3404663/cd72e3a8-fd73-11e3-92c3-b40170059c20.png)
Those sliders are difficult to use, because they don't display any numbers. 
Numbers, can be important while painting and to adjust brush settings. They also provide a feedback. 

**Proposition:**
Using Interface widget with more infos and control ; eg under, the one of Gimp:
![slider-fast](https://cloud.githubusercontent.com/assets/4021867/3404745/e3be3134-fd74-11e3-9478-3ca829a52c25.png)

**Comment by odysseywestra** [comment]
Luckily with the new sliders you can use shift to fine tune the value, but yes number should added wither it's a tooltip or physical numbers on the tool box.

---
Tiage Note: Adding to 2.0 milestone, if we can't do it in time. I'll move it to the 2.1.x milestone.

**Comment by odysseywestra** [comment]
@Deevad Could you move this thread over to https://community.mypaint.org/c/feature-requests? I'm working on cleaning up the issue tracker by move all feature requests there so we can get community feedback. If you can also set your post as a wiki that way we can edit the scope of the feature request that would be awesome as well. Don't forget to link back to here as well so I can keep track of it incase we need to reopen the issue.
----
I know you stated in #12 that you won't be able to till January.

**Comment by jplloyd** [comment]
Dynamic tooltips showing the setting values are enabled for these sliders here 0c722d20c6e6bf97e5febc5413495f1e3056046a

Additionally, these commits enable keyboard input for sliders by double clicking on them: 6a2f91a3829d91912fdfd6d0f17f632e3addee48 & 31a072ae6d797ae687dc6154f49db62cfe31343f which will show the current value in an input box.

----

A thing to consider here ([which was also raised in a related issue](https://github.com/mypaint/mypaint/issues/898#issuecomment-461382670)) is that even though this provides a numeric reference, the numbers themselves are not very straightforward, since they map directly to brush settings.

Without knowing the mappings of these values to the units they relate to, it may just be more confusing than not having any values. For example, if you don't know about logarithms, you will probably be perplexed about seeing the range for __Size__ be **`-2`** to **`6`**, and unless you are very familiar with how the brush engine works, the __Opacity__ going from `0` to **`2`** will be a bit surprising as well.

Those things should be dealt with in a separate issue.
