### ISSUE TITLE
Enabled Tool on Top bar - Dark theme

### ISSUE THREAD

**Issue by americogobbo** [mypaint/mypaint#255]
I've some difficult to see the tool enabled in the dark theme version. I've the check of my monitors and the black levels seems OK... the first line of 1 to 5 (http://www.lagom.nl/lcd-test/black.php) is all visible.
I'm using ubuntu gnome 14.04 with the Adwaita default theme.
MyPaint Git Master updated (1.1.1-alpha.20150312+git.08f3cc5)
![enable-tool-mypaint-darktheme](https://cloud.githubusercontent.com/assets/8180638/6617758/c81375ec-c89a-11e4-9434-f3d3c14df7bb.png)

**Comment by achadwick** [comment]
This is a theming issue, and newer versions of GTK may fix it already. Debian testing/unstable looks like

![image](https://cloud.githubusercontent.com/assets/61299/6617929/cec5850e-c8b5-11e4-8806-c3e8b33a6529.png) (png with no embedded color mgt chunks)

and uses gtk 3.14.5. How does that look on your setup, and what gtk version are you using? The usual 3.10.8 for that system?

**Comment by americogobbo** [comment]
Yes the 3.10.8.

**Comment by achadwick** [comment]
Okay. Solution is either to upgrade GTK or switch to a theme with more contrast, I guess.

Does the [screenshot above](https://github.com/mypaint/mypaint/issues/255#issuecomment-78473310) look better on your system?

**Comment by americogobbo** [comment]
Yes! But is safe to upgrade GTK? Perhaps is more safe to find another theme... Thanks!

**Comment by achadwick** [comment]
I can't say, because I haven't tested doing that. I recommend only upgrading GTK as part of a planned OS upgrade though, if you want to be safe.

Anyway, this isn't a MyPaint issue, and has been fixed upstream (in the Adwaita theme for GTK 3.14). A good workaround for users who don't want to upgrade their system in whole or in part might be to switch to a different theme. @americogobbo - if you find a new one, please paste a recommendation here! ISTR that "Numix" and "MediterraneanNight" have been good in the past.

**Comment by americogobbo** [comment]
OK, I've installed the shimmer-themes - Gtk+ themes from Shimmer Project.
The Numix is not good ... but I've used Numix to window and Greybird to GTK+... and is OK... is more comfortable that Adwaita. But if someone know a good dark theme for GTK+ 3.10.8 is better.
