### ISSUE TITLE
intuos touchring, cursor flicker 

### ISSUE THREAD

**Issue by artsnake** [mypaint/mypaint#263]
The touchring on my intuos 5 causes the freehand cursor to flicker when using any of the circle type.
I have the touchring set to increase and decease the the brush size [mode1] as well as image zoom in an out[mode2] and rotate [mode3] nothing [mode4]. It flickers in any mode. 
The increase and decrease in size of the brush using the touchring is glitchy also. Some times it works and sometimes it does not. It is hard to use as result of all this flickering and  on and off functionality.  
It does not cause the inking mode cursor to flicker and increases and decreases smoothly. 
It zooms and rotates just fine but still flickers the cursor a bit when in freehand mode.
It does not flicker when cursor is in cross hair mode. 
I am pretty sure it as been doing this with all the alphas I have tried.
ubuntu 14.04, gnome3 classic, mypaint 1.1.1 alpha.20150320+git.4d5bd9b

**Comment by achadwick** [comment]
#### Workaround: set the device to "Ignore" or "Non-painting"

On some tablets the "pad" devices look like pens to the software, meaning that when you activate the touch-ring MyPaint treats it like a device switch and tweaks the cursor. The workaround in recent builds like yours is to set the "pad" device presented by your tablet to "Ignore" or "Non-painting Tasks" only in the Preferences dialog, on the Devices tab:

![Example Preferences dialog showing the setting in question](https://cloud.githubusercontent.com/assets/61299/6765402/8648500e-cfd6-11e4-9508-52dd69b5c18b.png)

Highlight the row first, then click in the row's "Allow..." column to change the value there.

Doing this makes MyPaint skip over the hardware device when it would otherwise notice a device change. By the way, it's doing other things besides flickering the cursor a bit - essentially the size changes you wanted are being assigned to the wrong hardware device at the moment! But the workaround is to make it something other than an "All tasks" device.

Anything more needed for this, or is this workaround OK for now?

**Comment by achadwick** [comment]
#### Software development note

Even if we get #259 fixed up, this little glitch is still going to be with us. What's happening at the moment is that the device change is detected, it looks enough like a pen or a mouse to change to a different device-specific brush, and then the user's radius change goes there. Then they move their stylus a bit and the device changes *back*, and cursors flicker all over the place because the two brush settings had different radius values.

We could set `radius_logarithmic` to be an override setting that works no matter what brush you choose, but what happens if the user wants to choose that favourite "small eraser" brush of theirs to rub out some little detail? Maybe it would work if the radius the user sees was implemented as an override multiplier though...

**Comment by achadwick** [comment]
Workaround pasted to the [FAQ](https://github.com/mypaint/mypaint/wiki/FAQ). It's silly having to do this, but it makes Intuos tablets *significantly* more useful.

**Comment by artsnake** [comment]
this workaround does the trick. 
thanks

**Comment by achadwick** [comment]
Thanks for testing it out! Closing for now, since there's not much we can do about the underlying problem without some fairly scary changes.
