### ISSUE TITLE
Use linear light for tile storage (and therefore in the brush engine, improving blending)

### ISSUE THREAD

**Issue by hawstan** [mypaint/mypaint#265]
As MinutePhysics says, many image editors don't blend colors properly. https://www.youtube.com/watch?v=LKnqECcg6Gw
He suggests that the color values should be first squared and then averaged and square-rooted instead of being just averaged.

This image shows how MyPaint 1.0.0 does it. (windows 32 bit)
![mypaint_bad_blend](https://cloud.githubusercontent.com/assets/1917541/6769734/7fa5baee-d0a7-11e4-82b0-1807e0429df0.png)

**Comment by martinxyz** [comment]
It's called linear light and has many other benefits: http://wiki.mypaint.info/Linear_light_composition

The video is a bit simplistic, what you need is not squaring but sRGB gamma correction. The problem is also that it changes everything, e.g. it changes how already existing images (with multiple layers) look, and when you paint you will notice that a white stroke is now "stronger" (thicker) than black. There are experimental MyPaint branches where you can test the feature.

**Comment by achadwick** [comment]
Related issues: #4, #6. They don't specifically make linear light compositing a requirement though, so I'll retitle this issue and make sure the page gets migrated to the new wiki (issue #242!), but we won't be able to do anything about this for the 1.2 release.

**Comment by achadwick** [comment]
Wiki page migrated and updated (with significant corrections, I don't think I understood this correctly at all back when that page was written!). It's now at https://github.com/mypaint/mypaint/wiki/Linear-Light

**Comment by briend** [comment]
I've been working on various things here:
https://github.com/briend/libmypaint/tree/RYB-Smudge
and here:
https://github.com/briend/libmypaint/tree/Burns
One feature is "smudge_gamma" that lets you apply this linear light to blended colors.  Nothing to do with storage or layer modes, though.  From my testing, you wouldn't always want linear light:
https://community.mypaint.org/t/real-color-blending-wip/390/49
because what you (often) want is something that behaves more like paint, not light.  Having the option to flip or blend between paint and light is pretty cool though.

**Comment by briend** [comment]
I believe we could keep the existing storage sRGB but implement the conversion to linear light just before certain blend operations at the expense of CPU usage.  My current patch does this just for smudge+canvas and smudge+brush.  The next step would be to do the same for the dab+canvas operation so that hardness, pixel feather and opacity are blended correctly.

We could leave the layer modes alone and this would effectively preserve backwards compatibility for the most part.  As mentioned somewhere else the opacity of existing brushes would change, but maybe we can apply the gamma correction to that alpha to "fix" them?
We should also check the coefficients for the luminosity calculations throughout mypaint.  Those appear to be wrong (not REC 709) and also not using linear.

**Comment by briend** [comment]
Or maybe... we just make a clean break with MyPaint 2.0 and make everything linear internally.  Everything changes, nothing is backwards compatible.  But we'll be in a great place going forward

**Comment by martinxyz** [comment]
IMO one of the biggest advantages of linear light is that, if you convert to sRGB only after scaling down (right before displaying), the brightness of your ink-hatching-patterns stays the same. It's really a strong argument to just use linear light everywhere, IMO, otherwise you'd be converting forth and back basically before every operation. Another concern was: can I still open my multi-layer ORA in GIMP and it will look the same? But I'm starting to think this is getting silly if this holds future software back, maybe sRGB compositing should simply be declared to be a bug.

**Comment by briend** [comment]
Yes yes yes it is a bug we should finally leave behind :).  Do you still have the linear test branches somewhere? I can't seem to find them.

**Comment by briend** [comment]
I started a forum here: https://community.mypaint.org/t/color-management-and-linear-light/944
I think implementing OCIO w/ linear space will solve the color management problem as well.

**Comment by martinxyz** [comment]
@briend I just pushed some branches (from 2012!) that were on my gitorious fork to my github fork (linear_light_scaling, blend_modes4, rgbu2). Not sure if they still compile; tell me if you miss a specific branch.

**Comment by briend** [comment]
@martinxyz  awesome, thank you!

**Comment by briend** [comment]
Well, I made some progress with a really horrible and messy branch I documented in that link above.  I got display-referred working with OpenColorIO, full float tile storage, which also handled the color correction for the monitor.  Trouble is it is MUCH slower, almost entirely because OpenColorIO's python implementation requires a bazillion copies and transforms of the cairo surface pixel buffer.

So, this could actually work REALLY well if we managed to use OpenGL w/ OpenColorIO. http://opencolorio.org/developers/usage_examples.html
Basically you configure the GPU to do all the work and then you write your image to opengl textures.  If we could use Cario's open-gl backend then we wouldn't have to copy the image from the normal cairo surface to the gl texture-- we could write directly to the open-gl surface.  Basically free up the CPU entirely. I don't think you'd need a super fancy video card, maybe something within the last decade or so.

So, how do we use OpenGL with PyCairo?  Cairo has the opengl backend but that doesn't seem to be exposed in PyCairo.  Can we still access it via the C API somehow?

At least it seems there is some active development on the cairo open-gl backend:
https://blogs.s-osg.org/introducing-cairo-gl-es-v3/

**Comment by ShadowKyogre** [comment]
One problem with not making mypaint's rendering backwards compatible is that old files will appear discolored when opened in the new MyPaint. I currently have mypaint-git stuck at mypaint/mypaint@24d6f2bc and libmypaint-git stuck at mypaint/libmypaint@a2b3f56 because of such.

These are both the last commits that I have before linear light was introduced into mypaint. We definitely need a backwards compatibility mode if we make linear light the default for future stable versions. Otherwise people will have to be stuck with an old version to work on files they've made before the transition.

**Comment by briend** [comment]
@ShadowKyogre I've just added a preference: display.colorspace_OETF in https://github.com/mypaint/mypaint/commit/55af8eac4fd70d943798294e848cfc53a5fdd0a4
If we set that to 1.0 mypaint will composite everything in the legacy non-linear way.  A setting of 2.2 is the default and is ~linear.  What's interesting is we could easily make this a per-layer setting now.  This would be similar to the way GIMP has the "legacy" mode for layers, but more customizable (maybe for artistic effect you'd like change it to 1.5 or something random).  Other things we could do is extend the ORA spec to include this transfer function as part of the global document as well.  Then we could assume old documents use the legacy mode. . . or not?  One problem with legacy mode is that the new pigment brush mode doesn't work too well with it-- it's too dark since it is a ~plausibly physical rendering that requires linear light.  So just slide the pigment slider to off, I suppose for now.  Please let me know what you think.  I haven't exposed the preference in the GUI preferences yet, just the settings.json file.
