### ISSUE TITLE
Color Wheel Primaries preferences

### ISSUE THREAD

**Issue by americogobbo** [mypaint/mypaint#266]
It seems don't working the color wheel preferences... when I change the kind the wheel is always the same:
*Standard*
![standard-red-green-blue-wheel](https://cloud.githubusercontent.com/assets/8180638/6770829/dfa585f6-d0ab-11e4-98a7-ee8bae86715b.jpg)

*Traditional artist*
![traditional-artist-red-yellow-blue-wheel](https://cloud.githubusercontent.com/assets/8180638/6770838/03766c48-d0ac-11e4-8114-ca8d509816ab.jpg)

*Opponent*
![red-green_blue-yellow-opponent-wheel](https://cloud.githubusercontent.com/assets/8180638/6770839/15fc68e0-d0ac-11e4-847d-a6b426fa8df7.jpg)

I'm with the last git master 1.1.1-alpha.20150322+git.f4da91a

**Comment by achadwick** [comment]
Yeah, that's the built-in GTK one. We can't do anything about that, sorry.

**Comment by achadwick** [comment]
Given the confusion caused by this to our users, the fact that the GtkHSV widget is deprecated, and messy sizing issues like #169 (also tagged wontfix!), I vote that we should just remove this selector eventually. It just has too many problems to be maintainable.

However I'd like a good square/triangle-within-a-hue-wheel of our own before we do that. Our users clearly love it :/
