### ISSUE TITLE
Replace GTK built-in GtkHSV colour selector with our own

### ISSUE THREAD

**Issue by iirelu** [mypaint/mypaint#268]
See #169, #266 for prior discussion. As a summary, the fact that we can't do any of our usual colour selector methods with the built-in selector means it looks and feels out of place, and has a tendency to cause unexpected behaviour. Outright removing it isn't a good option as I imagine plenty of people rely on it, so replacing it is second-best.

**Comment by achadwick** [comment]
I think I prefer square-in-circle ones to triangle-in-circle ones, but it's not a strong preference.

Maths behind it: https://en.wikipedia.org/wiki/Barycentric_coordinate_system

It'd be nice having something with the same visual style as the other widgets!

**Comment by achadwick** [comment]
Bouncing till after 1.2. Not enough time to knock together a replacement now, and I've just gone and and added the old popup widgets as dockable panel tabs too (* I have reasons). Those suffer from nay of the same problems TBH, but we can live with them I reckon.

**Comment by achadwick** [comment]
Actually this hasn't yet been fully closed: the old triangle hasn't been *replaced* yet, but we do have a capable replacement courtesy of @ShadowKyogre.

Should we remove uses of Gtk.HSV for 1.2? There's no really pressing need since it still works in all known GTK 3.10+, but people are already complaining about there being too many colour selectors... :D

**Comment by achadwick** [comment]
Moving to -beta again, since we should be making a decision about this for consistency reasons (see #432)
