### ISSUE TITLE
MyPaint will not open up!!

### ISSUE THREAD

**Issue by UnicornElliot** [mypaint/mypaint#271]
It was working wonderfully and then suddenly I cannot use it! It will start to load as if it is opening up, but then won't open! I have tried uninstalling and re-installing many times, but it won't work! All of my other programs work fine :(

**Comment by achadwick** [comment]
This isn't enough information for us to decide whether this is a bug or not, sorry.

What version of MyPaint are you running, and what OS please? And where did you download it from?

What happens when you try to run MyPaint from the terminal? Are there any error messages there?

**Comment by martinxyz** [comment]
Maybe all your windows are off-screen. Find a file named "windowpos.conf" and delete it. It's in a folder called "MyPaint" or ".mypaint" wherever your OS stores your user settings. If this doesn't help, try to remove (or better rename) the whole folder.

**Comment by eg103** [comment]
Mypaint won't open up too, (btw im using mypaint 1.0.0)it wouldn't open up on my old pc either so i had to make a new acount :(

**Comment by AtsusaKaneytza** [comment]
The 64-bit versions of MyPaint usually don't work (from my experience) so you need to download a 32-bit version. If that's not the case, you probably need to go ahead and download a (32-bit) build of MyPaint 1.1. (Make sure you either have *WinRAR or 7-zip*)

A lot of people experience this issue where MyPaint 1.0 doesn't work on certain versions of Windows. You also need to delete your previously downloaded versions of MyPaint if they're not opening.

**Comment by achadwick** [comment]
1.0.0 is really old, too old for us to properly support.

If making a new account fixes it, this is probably a settings issue. Cleaning any mypaint folders out of `%APPDATA%` in your profile may help some. That's where your mypaint settings live, so you may want to be judicious about what you delete in there. You can generally leave brushes and backgrounds folders alone, and just get rid of any files named `windowpos.conf`, `settings.json`, and `accelmap.conf`: see if that works. The `scratchpads` folder may contain a dud scratchpad too, so delete that after backing it up somewhere.

Settings like these persist from one installation to the next.

Check out the FAQ too: https://github.com/mypaint/mypaint/wiki/FAQ - section "How do I reset all settings to the installation defaults?".

Sometimes you get an error log in there too, which can contain useful info about what might be causing the problem.

(For really old Windows installs, settings can live in "somewhere" in the installation folder too. Deinstalling the program should help, but you may wish to confirm that the folder's gone before reinstalling!)

I tend to recommend @tumagonx 's 1.1.1-alpha builds from http://opensourcepack.blogspot.fr/2013/01/mypaint-and-pygi.html - if you're happy trying the bleeding edge. That's what I've been promising (and to a small degree managing) to make suck less recently.

Anyway, this issue is beginning to get very tech-supporty, and the issues tracker is not really for direct user support. Unless anybody has some concrete log traces, I'm just going to answer with a pointer to the FAQ ( https://github.com/mypaint/mypaint/wiki/FAQ - section "How do I reset all settings to the installation defaults?") and advise you to try that. That's all I can suggest without knowing more.

-------------------------------

**TRIAGE NOTE** The original reporter has still not responded, and this issue is stale right now. Close this issue after two weeks unless concrete and fixable errors are reported.

**Comment by achadwick** [comment]
Closing: ancient version, no proper error report.
