### ISSUE TITLE
Undo shortcut undoes unintended strokes?

### ISSUE THREAD

**Issue by AtsusaKaneytza** [mypaint/mypaint#276]
Windows 8.1 64-bit, MyPaint Version 1.1.1-alpha.20150319+git.4d5bd9b, 32-bit 

I'll do my best to explain this, its really... odd...
Normally, the function will undo 1 or 2 strokes that are closely related, but what it does is this:
Example: if I made a stroke with the curve tool, and then make a freehand stroke, and I use "Undo", it will undo both of those strokes.
The other oddity is that if I use "Undo" twice, it will undo how I'm expecting it to.
Example: Stroke with a curve tool, then freehand stroke. First "Undo" undoes both the curve and the freehand lines. The Second "Undo" will make the curve line reappear.

Again, I'm sorry if this doesn't make a lot of sense.

**Comment by achadwick** [comment]
This is 4d5bd9b3cd30804d5fcb2ecc96cd4f31b8f5798a, which does things to linemode (Lines and Curves etc. - the old curve tools). Did it work as you expect before this change?

Is this a local build, or something you downloaded from somewhere?

> Example: if I made a stroke with the curve tool, and then make a freehand stroke, and I use "Undo", it will undo both of those strokes.

Which curve tool exactly? I've tried with the old Lines and Curves, and the new Inking (smooth curves) tool, exactly as you describe (trying not to even move the mouse and using the "p" key to change back to 

Please tell me exactly what you click or press for this one, and in what order.

> The other oddity is that if I use "Undo" twice, it will undo how I'm expecting it to.
Example: Stroke with a curve tool, then freehand stroke. First "Undo" undoes both the curve and the freehand lines. The Second "Undo" will make the curve line reappear.

This sounds like a dup of #200 and #174 - and those should be fixed in the version you're describing. Please check out the video in that and tell me if it's what you're seeing.

There should be a checkpoint enforced when switching tools. I can't reproduce either of these cases.

**Comment by achadwick** [comment]
Also, I really need to see any messages printed to the terminal during this. Can anyone bitten by this *after* 5690ea677575c64c8efa47044ca5dc4f3d4ce59b run MyPaint from a DOS prompt or Powershell please, with MYPAINT_DEBUG set in the environment, and let me know whether it checkpoints when the unexpected things happen?

**Comment by AtsusaKaneytza** [comment]
You're right, this is a duplicate of the issue you linked me to. it's exactly like what's going on in that video.

*"Is this a local build, or something you downloaded from somewhere?"*
Downloaded the latest build for Windows from Tumagonx's blogspot site.

*"Which curve tool exactly? I've tried with the old Lines and Curves, and the new Inking (smooth curves) tool, exactly as you describe (trying not to even move the mouse and using the "p" key to change back to"*
The "Lines and Curves" tool, not the other ones.
![image](https://cloud.githubusercontent.com/assets/8382492/6953999/1475bbfe-d893-11e4-8e2b-9627ecbff5fb.png)

**Comment by achadwick** [comment]
@AtsusaKaneytza thanks for that!

Please can you give me some exact step-by-step instructions to reproduce this as reliably as you can manage? I've been trying to verify it on Win7 64-bit with an unpatched git master branch, and it's just evading my attempts!

**Comment by AtsusaKaneytza** [comment]
I'm having a hard time reproducing the issue I was having...
if anything changes, I'll let you know, but like I said: at the time, it sounded like a duplicate of the issues you already mentioned.

**Comment by achadwick** [comment]
By the timeline, it can't be a strict duplicate. 4d5bd9b3cd30804d5fcb2ecc96cd4f31b8f5798a (Mar 19) contains 5690ea677575c64c8efa47044ca5dc4f3d4ce59b (Feb 13, hopefully a confirmed fix for #174!).

Though it's really tricky to reproduce this bug... is it possible that you noticed the bug, *then* installed that 1.1.1-alpha.20150319+git.4d5bd9b build, but after that you never saw the bug again? Though I believe you if you say that it happened *after* 4d5bd9b3cd30804d5fcb2ecc96cd4f31b8f5798a - regressions happen!

**Comment by achadwick** [comment]
Right now, two possibilities:

1. 5690ea677575c64c8efa47044ca5dc4f3d4ce59b didn't really fix #174.
2. Something between 5690ea677575c64c8efa47044ca5dc4f3d4ce59b and the later 4d5bd9b3cd30804d5fcb2ecc96cd4f31b8f5798a inclusive reintroduced the bug.

Wish there was a reliable way of reproducing this one.

**Comment by AtsusaKaneytza** [comment]
_"is it possible that you noticed the bug, then installed that 1.1.1-alpha.20150319+git.4d5bd9b build, but after that you never saw the bug again?"_
No, I noticed and reported it immediately in the version I initially mentioned. This sort of bug didn't occur in other builds I tested.

**Comment by achadwick** [comment]
Okay. We just need someone to provide a good summary of how to provoke it now...

------------------------

**Triage note**: isolated to a range of revisions (hopefully), needs steps to reproduce, could be bisected, video exists in #174, probably not a duplicate.

**Comment by achadwick** [comment]
@AtsusaKaneytza Is this still happening? Has it happened since you reported it that first time?

I notice that there is a new alpha build available from http://opensourcepack.blogspot.fr/2013/01/mypaint-and-pygi.html, dated April 1. Please could you 

1. Uninstall all versions of MyPaint from your computer via Add/Remove Programs
2. Install that alpha build.
3. Retest, tell me whether it's still happening.

-------------------------

**Triage note:** no steps to reproduce still. I may be holding onto this too hard by marking it as a bug, and given the lack of feedback I'm no longer certain it's a regression.

Flagging as stale, please feel free to close this issue if nothing has been forthcoming after 28 days.

**Comment by achadwick** [comment]
Ahem, wrong button :) I'm happy to leave this open till a good way of reproducing it comes along, or until someone confirms it's still happening.

**Comment by americogobbo** [comment]
I've tried to reproduce this bug in the new git master - 1.1.1-alpha.20150420+git.c0c088b
Perhaps the problem have a relationship with lapse time between each strokes... if you draw fast the undo works for a strokes series.
If you draw slowly each stroke is recover or erase how them were created.
I've used the same process used on the video #174.

**Comment by achadwick** [comment]
@americogobbo Tried, but without success I assume?

**Comment by americogobbo** [comment]
:-) Sorry...
The first tentative not... but I normally paint slowly on MyPaint :), and I began writing here...
After I thought better, and I decided to see the the video of #174, and after I've tested again and I noted this behaviour...
Well, I've made two tests, the first with large time between the strokes and another test with a short time between the strokes... and the test with short time between the strokes the undo or redo is working with strokes group. If you think interesting... I'll make a short video.

**Comment by AtsusaKaneytza** [comment]
Seems to be fixed in the latest build for windows: 1.2.0-alpha.20150504+git.a80a54b

**Comment by achadwick** [comment]
Okay, thanks for testing everyone! I'll knock it back to closed.
