### ISSUE TITLE
Add context to string

### ISSUE THREAD

**Issue by prescott66** [mypaint/mypaint#278]
Please add context to this string. I mean, split/disambiguate this string to two self trnslateable strings, because we have different translation forms for window title/label

#: ../gui/brushselectionwindow.py:304 ../gui/brushselectionwindow.py:327
msgid "Rename Group"

this wiki helps gnome guys:
https://wiki.gnome.org/TranslationProject/DevGuidelines/Translation%20contexts

**Comment by achadwick** [comment]
To clarify, that's
https://github.com/mypaint/mypaint/blob/a86ebfe8f279586b84ae8dc744845c18691de8dd/gui/brushselectionwindow.py#L304
https://github.com/mypaint/mypaint/blob/a86ebfe8f279586b84ae8dc744845c18691de8dd/gui/brushselectionwindow.py#L327
right?

The C API `Q_` and `C_` macros are not available in Python, and I can't fake my own `Q_()` with `glib.strip_context()` because the function simply does not work as [documented](https://developer.gnome.org/glib/2.44/glib-I18N.html#g-strip-context):

```python
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from gi.repository import GLib
>>> GLib.strip_context("foo|bar", "foo|bar")   # pretend untranslated: supposedly returns "bar"
'foo|bar'
>>> GLib.strip_context("foo|bar", "xab")   # pretend it was translated: all OK!
'xab'
```

I can't use this as part of a fake Q_() function in case any strings with contexts are not translated.

I will test if I can fake up a C_() using g_dpgettext2(), which does seem to be wrapped.

**Comment by achadwick** [comment]
Some success making my own C_(): intltool-extract likes it! I can write sensibly-formatted Python code like

```python
C_(                                                      
    "brush group properties dialog title",
    u"Group \u201C{group_name}\u201D",
).format(
    group_name = self._group,
)

and `scons translate=...` doesn't freak out and instead makes something sensible like:

```po
#: ../gui/brushselectionwindow.py:318                                          
#, python-brace-format                                                         
msgctxt "brush group properties dialog title"                                  
msgid "Group “{group_name}”"                                                   
msgstr ""                                                                      
```

@prescott66 Is that the style you're seeking? Also, what kinds of strings do you want to see in `msgctxt`?
