### ISSUE TITLE
New binaries for new versions?

### ISSUE THREAD

**Issue by patlecat** [mypaint/mypaint#281]
It would be lovely if there were more frequent releases and binaries with each one. I'm a Windows 8.1-x64 user for example.

**Comment by achadwick** [comment]
Oh I agree. We just have a big pile of bugs that need fixing first, and a few more developers and testers wouldn't hurt.

If you're asking about progress, you can check our progress for this release at https://github.com/mypaint/mypaint/milestones/MyPaint%201.2

If you just want binaries right now, there are third-party Windows builds of what we're doing in this available from @tumagonx 's blog: http://opensourcepack.blogspot.fr/2013/01/mypaint-and-pygi.html (ignore the outdated text in the post, and check out the 1.1.1-alpha downloads). I'd certainly appreciate any help anyone can give in turning our (internal and developer-only, non-install) https://github.com/mypaint/mypaint/blob/master/README_WINDOWS.md windows docs into something that can be bundle MyPaint as an MSI or a setup.exe by following instructions. Not my area of expertise that :/

I'm very keen to get Windows working as well as Linux does for MyPaint - driver and library support permitting of course - and I'm happy to say a load of cross-platform issues got killed off lately. Pressure support in GDK for example (I think. I'd need ALL THE HARDWARE to test it properly.)

So that's where we are. Perhaps you could look at the Windows bugs flagged for 1.2 and help triage, test, and bugfix? That would be a super-useful thing you could do to help speed things along. Perhaps some of those 1.2 tasks could be bumped till later? Perhaps they've gone stale and the reporters need poking to provide the information we've asked for? There's a wealth of things that can be done without getting your fingers into the code: a good article on the subject is http://words.steveklabnik.com/how-to-be-an-open-source-gardener 

For now though, I'm going to close this issue since it's not really a reproducible bug or a specific feature request that anybody could just pick up and implement. What I think you're requesting is something that just needs an investment of developer/tester/triager time, and MyPaint is fundamentally a volunteer-run project.

**Comment by patlecat** [comment]
Well it would be if you had something like a cross-platform build tool like CMake, then adding Windows specific stuff would be easy and using the installer InnoSetup is easy enough too. :)

**Comment by achadwick** [comment]
Pull requests welcome for CMake support *if* it offers a clear benefit over our existing cross-platform build tool, [SCons](https://en.wikipedia.org/wiki/SCons).

Pull requests welcome for InnoSetup support, or any other Windows installer-maker. It would need to be a complete solution, one that bundles all the required libs and a Python runtime.

But we're drifting off-topic here, and the issue tracker is not a discussion forum.

**Comment by patlecat** [comment]
It's an issue for me, I can say at least that ;) I would love to contribute an installer for Windows but not willing to go through the building process on Windows. So let me know if someone else tackled that.
