### ISSUE TITLE
[Feature Requests] - Brush Resizing with Pen Button+Drag.

### ISSUE THREAD

**Issue by Ico-dY** [mypaint/mypaint#293]
Could you add the brush resizing with pen button+drag?
It's very convenient, the shortcuts method is tiring! 

Thanks in advance for the help. ^^

**Comment by achadwick** [comment]
How should it work? Hold down a modifier key and then drag with a button?

**Comment by Ico-dY** [comment]
I use it without a modifier key in other software, but it's a configurable thing. Keeping pressed the pen button and moving the pen to left (diameter decreasing) or right (diameter increasing) I can resize a  symbolic brush tip preview, usually a simple circle, to adjust the actual brush diameter.

**Comment by whitetree** [comment]
something like alt right click in ps, and shift normal click in krita i think. its very handy.  i could see swapping the alt click functionality for that.

**Comment by achadwick** [comment]
Anybody got any screenshots of what other programs do, or mockups? I need something concrete to go on here.

It would be easy enough to add a mode for doing this.

I don't like left=decrease, right=increase. It needs to be a radius-adjusting thing, with reference to a centre, and moving point on the circumference. UI challenge: pick the centre appropriate for all initial screen positions!

Gut feeling is that button-1 is best for this, as it affects the current pen nib.

We can either use the approximate circle used by the cursor, or do something clever and attempt to render with the current brush some. My previous attempts at anything like the latter haven't been that successful though :(

----------------

**Triage note:** needs some concrete examples or mockups (but maybe not that much). Deferred: leave till after the 1.2 release before chasing.

**Comment by Ico-dY** [comment]
I've just  found this video about the Photoshop method: https://www.youtube.com/watch?v=5ztucGGf6cg
However I don't like the modifier keys: with Krita, Clip Studio, Opencanvas, etc. etc. I can do the same thing without touching the keyboard. :P

**Comment by AtsusaKaneytza** [comment]
FireAlpaca and Paint Tool SAI does this with "Ctrl+Alt+Drag Cursor" The UI displays a crosshair and the brush cursor changing in size when the brush/pen tool is in use.

**Comment by Griatch** [comment]
This is really a matter of preference, but it can be very quick once you get used to it. The Krita resize works like this: 

1. Press and hold the Left or Right `Shift` Key.
2. Press and hold `LMB`  (you can now release `Shift` if you want, you are in "brush-resize mode" until you release `LMB`). 
3. Move the cursor. You will always see a brush outline centered on the point where you clicked `LMB` (even if you configured the program to not display the outline it normally). You will see the brush outline resize dynamically around the center point:
   - Up: Larger brush radius in small steps (this is for fine-tuning brush size)
   - Right: Larger brush radius in big steps (coarse adjustment) 
   - Down: Smaller brush radius in small steps (fine-tuning)
   - Left: Smaller in big steps (coarse adjustment)
4. Release `LMB`. This locks in the brush size currenly selected and the brush outline will be hidden again if so configured.

**Comment by odysseywestra** [comment]
Another program that resizes bush with the pen is Krita as well. It uses shift + drag left or right.

**Comment by didli** [comment]
Sorry to dig an open request 3 years after, but well ... since I would love to see this too, here's my contribution anyway : Blender has something similar in sculpt mode.
Hitting "F" while in "sculpt mode" brings out a resizeable circle area that determines the brush size : holding your cursor close to the center circle decrease your brush size, taking your cursor away from the center increases it. This is amazingly intuitive and super fast. I really wish to have something like that in mypaint.

**Comment by odysseywestra** [comment]
@Ico-dY Could you move this thread over to https://community.mypaint.org/c/feature-requests? I'm working on cleaning up the issue tracker by move all feature requests there so we can get community feedback. If you can also set your post as a wiki that way we can edit the scope of the feature request that would be awesome as well. Don't forget to link back to here as well so I can keep track of it incase we need to reopen the issue. Thanks.

**Comment by jplloyd** [comment]
I implemented this for my personal use at the end of 2016 (I think it was around there at least, I reset commit dates when rebasing into my experimental build and don't have the original branches anymore). If you build my [experimental branch](https://github.com/jplloyd/jpl-mypaint-experimental) you can try it out by creating a button-binding for "Drag-resize brush".

The main problem is that what we adjust in the click-drag is not necessarily indicative of the **real size of the brush output**. Depending on jitter, offsets, pressure-mapped brush size and all of the various dynamics, it's pretty hard to come up with a good indicator of the _actual_ size, and not just a (sometimes meaningful, sometimes wildly misleading) representation of the base radius parameter.

A solution to that problem is required before this is added.

**Comment by odysseywestra** [comment]
That would probably require us adding a suppress option which is also what xsetwacom uses to deal with that issue. The scope would probably also require modifier to slow down the brush resizing which should help with control as well. I'll take a look at your branch so I can get an idea of what needs to be done. Cause honestly, personally I'd rather have this functionality than using keybinds to increase or decrease brush size due to be much more accurate if done right. It would probably also require us to implement #470 (Software Cursor) for ux flow before anything else.

**Comment by jplloyd** [comment]
The first sentence of the previous comment was caused by confusion from me not specifying that I was referring to _brush settings_ when mentioning jitter, offsets, etc. The rest I agree with (though optional software cursors are not essential for this, I'll look into it after I'm done with some other areas of the gui).

Initial implementation in: 12195c7a3d0bdc61c111e86f6ba746389026dbc8

To try it out, build the latest master or download the [latest continuous appimage build](https://github.com/mypaint/mypaint-appimage/releases/tag/continuous), go to the Buttons tab in the preferences and create a binding for "Resize brush".

Using that binding, clicking and dragging on the canvas will adjust the size of the brush, based on whether you move the cursor away from, or towards to the location of the brush center when the resizing started (it gives the appearance of the cursor being locked, though that is not actually the case).

Toggling the shift key enables/disables high-precision mode (slowing down the resizing, as suggested previously).
Down the line, the modifier key and rates of change should be made configurable, at least in the settings file to begin with.
