### ISSUE TITLE
The mypaint program won't launch

### ISSUE THREAD

**Issue by littlesestras** [mypaint/mypaint#314]
I'm a Windows 8 user. After a few weeks of using the 32 bit 1.1.0 program, (I downloaded from http://mypaint.intilinux.com/?page_id=6) today I found that no matter how many times I clicked on the mypaint icon on my desktop, it wouldn't launch. It would simply act like it was about to load and then not do anything. I uninstalled/reinstalled it and still nothing. I've seen other people have this same problem but I can't find a solution anywhere. I really like this program and i'd like to continue using it.

**Comment by achadwick** [comment]
The issue tracker isn't really for direct user support requests; on the face of it, it sounds like your config has become corrupt somehow. However there _may_ be something that could become a bug here - it depends on what's going on. Can you answer a few questions?

1. Did you de/reinstall after a reboot?
2. After attempting to launch MyPaint, does switching windows with Alt+Tab show any MyPaint windows?
  * And if so, when you choose one, does it come to the fore or become visible?
3. Does the Task Manager (Ctrl+Alt+Del, Task Manager button) show any running MyPaint or Python processes?

**Comment by littlesestras** [comment]
Oh, my apologies, I wasn't sure how this worked. 
1. It wasn't directly after a reboot, but I did restart my computer when it wouldn't launch. After trying to check for solutions online, that's when I decided to try uninstalling and reinstalling again to see if that would do anything
2. No, I don't see any mypaint windows
3. I don't see either of those in my task manager

**Comment by achadwick** [comment]
Okay, presumably it's just bombing out without giving any exception dialogs. Could you try and launch it from a command line please (Windows cmd.exe in your case), and paste what happens here between Github's triple backtick markers? It'll all be pasteable text.

    ```
    (log stuff goes here)
    ```

Some builds of MyPaint also write logs to files, if you're not comfortable finding out how to launch your installed MyPaint from the command line. @tumagonx can you help this user out?

(I prefer not looking at logfile output because I don't know how up to date yours will be or if anything useful has gone in it. You'll have to use your judgement in deciding what to paste, and check file timestamps to make sure it's useful.)

Many thanks in advance if you are able to do this.

-----------------------------

You can possibly fix this by moving the config folder out of the way. "See the FAQ":https://github.com/mypaint/mypaint/wiki/FAQ#how-do-i-reset-all-settings-to-the-installation-defaults.

You may also be able to fix this by installing @tumagonx 's latest alpha build from the 1.2.0-alpha series.

If either of these approaches fix it for you and you don't want to take it further, let us know so we can close this issue.

**Comment by littlesestras** [comment]
Okay, so I apologize in advance because a lot of this stuff flies over my head, but I tried a couple of these things to the best of my abilities. I started by going to follow the instructions of moving the config folder. I found an order.config file in the brushes folder which I deleted, which didn't really do anything. It said to either delete the whole folder or relevant files. I went to @tumagonx 's profile but I couldn't find what you were referring to, I looked here https://github.com/tumagonx/mypaint but couldn't find anything referring to an alpha build. Lastly, I opened a command prompt, and I tried some things for a little bit. I can't figure out the markdown thing right now, I've been trying to work on this for a few hours and my brain is kind of fried by this point. I tried to take the mypaint .exe file and drop it into the command prompt, but I wasn't sure how to go about actually starting it via the command prompt.I also tried 'start mypaint.exe' as well as 'C:\Program Files\MyPaint\mypaint.exe' I think that one gave me error messages saying that I hadn't entered a command.I haven't really worked a lot with the command prompt before. 

I'd like to keep trying things, but if most of them are going to be out of my element than I'm not sure I'd be much use figuring them out. Still, I appreciate the help so far.

**Comment by tumagonx** [comment]
@littlesestras
Unfortunately mypaint 1.0 is so dated. Please try one these:
http://sourceforge.net/projects/tumagcc/files/mypaint-1.2.0a.7z/download
http://sourceforge.net/projects/tumagcc/files/mypaint-1.1.1a.7z/download

**Comment by achadwick** [comment]
The issue tracker is not for user support. Please provide the requested info if you want us to take this further and update the codebase. Without that we can do nothing for you.

---------------------

You have two options for helping yourself:

* Reset your user configuration as described at https://github.com/mypaint/mypaint/wiki/FAQ#how-do-i-reset-all-settings-to-the-installation-defaults
* Try @tumagonx 's latest versions, report back via opensourcepack.blogspot.fr/2013/01/mypaint-and-pygi.html

Never run software off the internet as root or Administrator just to get it working.

----------------

**Triage note:** this doesn't seem to be going anywhere right now. Close and lock after 2 weeks if no reporter provides the requested info.

**Comment by achadwick** [comment]
Seems to have dried up. Closing...
