### ISSUE TITLE
HSV Square Selector Don't Works in the two sides

### ISSUE THREAD

**Issue by americogobbo** [mypaint/mypaint#338]
The HSV Square selector don't working in two sides: vertical (right side) and horizontal (top side). When the selector is positioned over the border of two sides the H wheel don't works... if you place a bit more inner works but is in steps way. 

I'm not safe if this is a bug or the normal behaviour when the color is back 100% or when the color is positioned over the grayscale.

![hsv square problem](https://cloud.githubusercontent.com/assets/8180638/7967665/d452bcde-0a01-11e5-8d84-6273c51287b2.jpg)

A short video to show this behavior:
https://youtu.be/j1VvW23orIk

My DE is Gnome 3.10
Ubuntu Gnome 14.04.2
MyPaint 1.2.0-alpha.20150603+git.4985174

**Comment by achadwick** [comment]
Reproduced in 4985174a0995347d5739b94b4b0705b0b8e38fd8. If the S-and-V marker is positioned at s=1 or v=1, the hue ring cannot be adjusted. The HSV Cube selector is affected too, so this seems common to the square bit - maybe it's just a range test off? Both selectors should be using an HSVColor internally...

(Paging @ShadowKyogre, but on;y because they touched the code there more recently than I have☺)

**Comment by ShadowKyogre** [comment]
@americogobbo, @achadwick - I think #326 is also related to this. I can also reproduce this with the sliders if I set the chromance all the way down. It doesn't allow changing the hue when I do that too. I think it might have to do with the color manager since both HSVCube and HSVSquare are using HSVColors internally.

So the steps to reproduce it in each widget, other than the HSVCube, HSVSquare, and Concentric Rings are:
* Sliders - Set C all the way to the left, can't change H
* HCY Wheel - Crank the white/black slider all the way up or all the way down, the dot circle should be locked in place
* HSV Wheel - Crank the brightness slider all the way down, the dot circle should be locked in place

Should I record a video of the reproduction of the bug in the other widgets listed?
