### ISSUE TITLE
New Layer from Visible - Strange blend with layers below

### ISSUE THREAD

**Issue by americogobbo** [mypaint/mypaint#349]
I've tested the new feature and for me is occurring a strange blend with the below layers, the new layer from visible is reinforcing the value colour. For me the new layer from visible must create an exact copy of layers without any blend operation with below layers.

The .ora doc is on my google drive, I'm not capable to attach here the code :(
https://goo.gl/Ix4R4F

Screenshot of three layers
![three-layers](https://cloud.githubusercontent.com/assets/8180638/8316406/32549e30-19cd-11e5-9cbb-6291a16a1f15.png)

Screenshot of New Layer from Visible with all layers visible
![new-from-visible](https://cloud.githubusercontent.com/assets/8180638/8316425/540c4a8c-19cd-11e5-87af-bf0ddf5fd632.png)

Screenshot of New Layer from Visible with only visible the new create layer > New Layer from Visible
![new from visible - only on](https://cloud.githubusercontent.com/assets/8180638/8316445/7f508f3c-19cd-11e5-9ad9-045e7594156d.png)

**Comment by americogobbo** [comment]
I've made a variation of this .ora with copying all three layers first to merge... only to understand the behaviour of Merged Layer... and really the Merge layer when are below the merged layers is making some blend. As the merge feature cancelled all visible layers was not possible to see this behaviour before of the new variation New from Visible that preserve all visible layers.
https://goo.gl/LOCF79

**Comment by achadwick** [comment]
Hi - looks like the brush you're using is 100% opaque, but the layers are being merged while the backdrop is visible. When you do this, MyPaint:

1. Calculates the merged layer
2. Subtracts the backdrop from it (surprise!)

To get the behaviour you want, turn off "Show Background" before doing the merge, then turn it back on again. Merges are sensitive to that.

(This is the way "Merge Visible" and "Normalize" have always worked in MyPaint. It's supposed to preserve the results of effect layers like Multiply when they touch the background.)

**Comment by Toybulldog** [comment]
Hallo

Thanks for the note .
To me , the days ago also noticed.
Now I understand why , that makes sense .
Here is an example , exportation layers to Gimp

![mypaint](https://cloud.githubusercontent.com/assets/11164330/8323617/29eabd0e-1a47-11e5-8d8f-5fe61d120c57.jpg)
![merge visible with background](https://cloud.githubusercontent.com/assets/11164330/8323618/2b2d86a6-1a47-11e5-8a71-bccd994d44c9.jpg)
![merge visible with no background](https://cloud.githubusercontent.com/assets/11164330/8323619/2ccc75e4-1a47-11e5-8210-9932305793ab.jpg)

**Comment by achadwick** [comment]
This is tricky to explain, and while that's often a sign that one is Doing It Wrong™, it actually does make it more flexible.

What's happening is that all of the following commands work with backdrop subtraction:

* Merge Layer Down
* Merge Visible Layers
* New Layer from Visible
* Convert to Normal Painting Layer   ← effectively a Merge Visible of one layer

Backdrop subtraction is something that's unique to MyPaint as far as I'm aware. It works by:

1. Calculating their inputs layers' combined appearance. This naturally includes the combined backdrop underneath the layers you want to merge, which is a problem because you probably just wanted the data in the layers you merged. To fix it, we:
2. Subtract the background from the results.

This stops the merge you're doing from changing the appearance from what you see on screen. What you see on screen before you do the merge is hopefully an accurate picture of what the results of the merge will look like.

**Comment by achadwick** [comment]
Let's address this by documenting the weird behaviour. Please review, and feel free to make edits!
https://github.com/mypaint/mypaint/wiki/v1.2-Layer-Merging-and-Normalization
(Somebody add some screenshots please!)

If this isn't sufficient, we could bump this to back to the alpha phase and add variant commands for merge-with-backdrop and merge-without-backdrop. Let me know if you feel investigating this is necessary.

**Comment by martinxyz** [comment]
Just an opinion and braindump - I'm of course a big fan of "merge result is what you see". But there are multiple ways to achieve this, or more precisely: multiple choices for the result's alpha channel. The current choice is to minimize the alpha channel. This works in all cases, but is unnatural for "Normal" layers. Mathematically, we are free to choose a minimum alpha value for each pixel of the result. "Normal" layers are special because they can be visually merged with a well-defined alpha result. (They have no "do-nothing" color, meaning their alpha channel always corresponds to the influence of the layer's pixels on the result.) So, another choice for the minimum alpha would be to use whatever result merging the involved "Normal" layers would give. Or more pragmatically, maybe "Convert to Normal Painting Layer" could be used on all involved layers first, and the result combined with standard RGBA blending.

**Comment by achadwick** [comment]
I think the docs are enough to close this. There may be smarter things we can do for the merges once I get my head around the maths.
