### ISSUE TITLE
Cursor :  visibility problem 

### ISSUE THREAD

**Issue by carypt** [mypaint/mypaint#353]
if i use fine lines in freehand  on total black painting  and i zoom out  12 times  from closest view  the cursor isnt visible any more . blind flight . ( eg. if i want to paint fine white lines on black  , and i really need  the 12 time and above zoom-out for balanced painting ) . 
i need at least a color-inverted dot for knowing where i am . a  keyboard shortcut for highlighting cursors position would be useful  otherwise .( same theme here : https://github.com/mypaint/mypaint/issues/83  but not as sharp ) ( in version 1.00 i dont have any preferences dialogue  about cursor appearance , right ? )
it is really not creative working if no cursor is visible . 
on other hand  thx for good program , really fast responding brushes !

**Comment by achadwick** [comment]
Please upgrade, 1.0 is too ancient to be supported by us. 1.1.0 and above (I think) have settings which allow you to change the appearance of the cursor. Here's what it looks like in the actively developed version (1.2.0-alpha):

![Cursor prefs](https://cloud.githubusercontent.com/assets/61299/8396652/f543d91a-1da6-11e5-8082-0f5da602fbff.png)

Closing because this is a user support request relating to an unsupported version, and because the issue tracker is not really intended for user support requests.

However, *please raise a second issue about inverting the cursor colour* referring back to this one as #353. I can envisage something like that working as a keypress command, but you'll have to explain exactly what you want, and why.

FYI in GNOME, you can make the system highlight the cursor position by pressing the Ctrl key. The setting is in _tweak tool → Keyboard and Mouse → Show location of pointer_. Cinnamon has something similar too.

**Comment by carypt** [comment]
ok , updated to 1.10 windows . seems lot better . thank you .
but cursors response is gotten too slow to follow fast drawing now , so i prefer fast sketching on 1.0 .
thank you anyway . )
