### ISSUE TITLE
Dialog Windows pop up under the Main Program window. Can't refocus the Main Window to get to the pop-up window under it.

### ISSUE THREAD

**Issue by AtsusaKaneytza** [mypaint/mypaint#358]
_Using 32-bit MyPaint 1.2.0-alpha.20150605+git.4e8a6b5, downloaded from tumagonx's blog.
Using a Yiynova MVP10U screen tablet. Windows 8.1 64-bit system._

I checked to see if I (or someone else) has reported this before, but didn't catch anything. Apologies if this is a duplicate.

I'm not really sure how to reproduce this, but sometimes, doing something that causes a pop-up dialog window (Like renaming a layer, editing a brush, or even saving the file) will cause the window to show up BEHIND the main program window.

Clicking outside of the pop-up window doesn't do anything, and therefore, means you can't do anything about it except press the "Esc" key to close the dialog window you can't access. Haven't found any workarounds for this. (Can be a hassle for saving files, especially when working on something I didn't intend to save as a scrap file)

**Comment by achadwick** [comment]
Sounds like an upstream Windows window management bug, not sure if we'll be able to do anything about this one, or even get a reliable way of reproducing it.

* Can you not bring the dialog to the fore _at all_? Try the Window's taskbar button's menu - the dialog should be listed.
* Does it happen for *ALL* the dialogs you mention?
* Does it happen for the X/C/V/B popups too?
* What about floated-out sidebar panels? (:warning: some versions of GTK have a nasty crasher bug when dragging tabs that only got resolved recently)

I will need reliable steps to reproduce this on Windows 7 if I'm to debug this at all.

**Comment by AtsusaKaneytza** [comment]
>The taskbar doesn't show the pop-up window as another window.
>It doesn't happen for the x/c/v/b popups (I don't consider them Dialog Windows because they don't have a Window border and an "X" in the corner)
>Floating panels work fine for me, and haven't crashed the software for me.

For reproduction:
>It MAY have been caused by me closing the laptop lid while the program was open (Closing the lid will put the computer to sleep) I'm not sure if that's a factor though, and it might be a stretch.
>Other factors might be doing other things in other programs for too long while MyPaint is open in the background (usually 30+ minutes)

**Comment by achadwick** [comment]
Thanks for the feedback.

* Weird that the dialog isn't listed.
* Are you able to even *see* the dialog window under the main window. When it happens, please move the main window so that you can see the dialog, and then click on the dialog's title bar. This SHOULD raise the dialog above the main window (that's what I meant by "can you not bring the window to the fore at all").
* Tried Ctrl-tab at all (this may not work if the window isn't listed, I'm guessing)
* If the dialog is stuck behind the main window, is it also stuck behind other windows you bring up on your computer (try launching Windows Explorer or Notepad and putting the Mypaint dialog in front of them in the way I described). If it's stuck behind those too, something fundamental is broken, and its surely an upstream problem.

Does this happen very frequently? What you describe kinda makes it sound more like a one-off now. Those don't sound like they could be contributing factors to me. I'm more inclined to suspect a glitch in GTK or GDK stemming from a difference in the way X11 (Linux/Unix) and Windows deal the windows you see on screen.

**Comment by AtsusaKaneytza** [comment]
_Are you able to even see the dialog window under the main window. When it happens, please move the main window so that you can see the dialog, and then click on the dialog's title bar. This SHOULD raise the dialog above the main window (that's what I meant by "can you not bring the window to the fore at all")._

It IS possible to bring the dialog window in front of the main window then part of it is poking out- but most of the time, I am working with a Maximized program window so I can't do it. I can usually press "Esc," resize the window and fix it, but I just consider it more trouble than what its worth. It does happen frequently, around every 3 times or so that I use MyPaint. If it happens again, I'll try what you said here and try to update with the results.

**Comment by achadwick** [comment]
@AtsusaKaneytza Has this happened again with the current betas?

**Comment by AtsusaKaneytza** [comment]
It hasn't happened again yet with the beta.

**Comment by achadwick** [comment]
Thanks for the confirmation. I'll leave this open for a couple of weeks in case anyone else has anything else to add, or in case I come across it myself.
