### ISSUE TITLE
GUI or CLI to migrate the contents of the "old-style configuration area" to $XDG_*

### ISSUE THREAD

**Issue by aleksejrs** [mypaint/mypaint#368]
MyPaint built from https://github.com/mypaint/mypaint

When I start it, it says in the terminal:

```
INFO: mypaint: There is an old-style configuration area in u'/home/user/.mypaint/'
INFO: mypaint: Its contents can be migrated to $XDG_CONFIG_HOME and $XDG_DATA_HOME if you wish.
INFO: mypaint: See the XDG Base Directory Specification for info.
```

Migration includes moving 3 directories into `~/.local/share/mypaint` and 2 files into `~/.config/mypaint`. Also `settings.json` has a reference to a file (`"scratchpad.last_opened_scratchpad"`) in one of the directories, which is not updated automatically, and causes an error on shutdown. Should every user have to find out what to move by trial and error?  There should be a button or a command-line option to do it automatically.

**Comment by achadwick** [comment]
This would require new UI strings. Postponed until after the 1.2 release.

**Comment by achadwick** [comment]
Sorry, marked it as closed by accident there.

**Comment by odysseywestra** [comment]
We should just write in the wiki of what commands to use to move the old mypaint config folders to the correct new one. After that, this issue could be closed.

**Comment by jplloyd** [comment]
Yeah, at this point I don't think it's worth introducing code to implement this directly in MyPaint. 3-4 years ago it could have been justified, but now most users are almost certainly on v1.2.0 or newer.

I have documented the migration steps here: https://github.com/mypaint/mypaint/wiki/Migrating-settings-&-data-from-1.1 and changed the printout to reference that page (918751e29fe178469babf07405b9823669dba469).

It's questionable whether the printout is very useful, since most people won't start the program from a terminal, but it's kind of moot, since very few people will still be affected by this.

The warning should probably be removed entirely a couple of versions from now.
