### ISSUE TITLE
I can't draw with my tablet?

### ISSUE THREAD

**Issue by lilych4** [mypaint/mypaint#380]
Hello, recently I got a monoprice drawing tablet and I've been trying to set it up with MyPaint. For a while, whenever I tried to draw it showed me this weird bar with my past colours. I got it to stop doing that but now I don't know how to make it so I can draw normally. Please help!

**Comment by achadwick** [comment]
Hi there - thanks for the feedback! There's not quite enough information in your original report
to move this issue forward, however. Please read the [reporting guidelines][reporting]: we need more information about your system, and more information about your MyPaint installation if this report is going to be useful to us.

This issue tracker is not for direct user support really. We try to limit it so that each thread is a single fixable issue which can be closed by changing the MyPaint code. I won't close this report straight away though because sometimes we can help, often the feedback is useful anyway, and sometimes support requests can turn into stuff programmers can actually do something about!

We may not be able to help you straight away here, but don't be discouraged if we can't. You may find you get more useful feedback on IRC ([#mypaint on freenode][irc]), in the [MyPaint forums][forums], from Twitter ([@MyPaintApp][twitter], `#mypaint`), or on the [MyPaint mailing list][list].

[reporting]: https://github.com/mypaint/mypaint/blob/master/CONTRIBUTING.md#test-the-program-and-report-issues
[forums]: http://forum.intilinux.com/index.php#c9
[irc]: irc://freenode/mypaint
[twitter]: https://twitter.com/MyPaintApp
[list]: https://mail.gna.org/listinfo/mypaint-discuss

**Comment by Teyphas** [comment]
My assumption may sound stupid, but I think that "weird bar with past colors" is one that appears by pressing X key. I didn't have any experience with Monoprice tablets, but maybe it's stylus or some hotkey on tablet itself that triggers it. If there is a way I would check settings for that tablet if it allows to customize hotkeys, etc (just like Wacom for example).

**Comment by achadwick** [comment]
@lilych4 Is this Windows, like with #119? Is this an ancient release (v1.0.0) also?

If so, please try a newer Windows release from <https://github.com/mypaint/mypaint/releases>, and please tell us what happens.

**Comment by achadwick** [comment]
From #381. I assume closing this issue was an error?

> Hey, recently I bought a drawing tablet so I installed MyPaint 1.0.0. 

@lilych4 Please upgrade to a recent 1.2.0-beta and let me know if this is still happening. 1.0.0 is too old for us to support.

Are you using Microsoft Windows?

**Comment by achadwick** [comment]
**Triage note**: needs system information, almost certainly an unsupported MyPaint version. Reporter: please upgrade and test again.

**Comment by achadwick** [comment]
No feedback from reporter after 4 months. Closing.
