### ISSUE TITLE
While drawing, freehand cursor sometimes changes to default windows cursor.

### ISSUE THREAD

**Issue by zb13y** [mypaint/mypaint#384]
[SOLVED] 1.2.1+gitexport.bcf5a28d (Python 2.7.13, GTK 3.22.7, GdkPixbuf 2.36.4, Cairo 1.15.4, GLib 2.50.1)

.

1.2 beta 0.73, Windows 7 64.

Main problem. While drawing, freehand cursor sometimes changes to default windows cursor.
1. Always. Changing brush size with 'F' and 'D'. For milliseconds.
2. Sometimes while drawing. For milliseconds.
3. And finally, sometimes after few minutes of sketching freehand cursor changes to windows cursor, and stay like that. But i can recover freehand cursor using (key shortcuts e.g. pan view, popup menu).

Here also message on forum - http://forum.intilinux.com/mypaint-general-discussion/mypaint-1-2-0a-for-windows/msg13479/#msg13479

**Comment by achadwick** [comment]
Seems fairly minor, and there is a workaround. I'm happy to accept patches for this, but let's defer this till after the 1.2.0 release.

**Comment by AtsusaKaneytza** [comment]
I'm currently using MyPaint 1.2.0 32-bit on a Windows 10 64-bit system
(I can't use the latest releases because of certain reasons, but that's probably a different issue. I'll answer about it here if asked though)
Using a Yiynova MVP10U Screen Tablet, drivers are all up to date.

I've been having this issue recently, but it actually does affect the drawing in a buggy manner:
![image](https://cloud.githubusercontent.com/assets/8382492/18736957/d062c1ec-8051-11e6-9f95-faa9e7ac6ea6.png)
That middle line is NOT supposed to be "connected" to the one on the right. But this always comes from a result of MyPaint drawing with the Windows Cursor instead of the Canvas Cursor.

Also, the "Hide Cursor While Painting" option is unchecked in my preferences:
![image](https://cloud.githubusercontent.com/assets/8382492/18737175/e7a28296-8053-11e6-8fb9-094522d8c900.png)


Pressing "Esc" while hovering over the canvas will change it to the appropriate cursor, but the problem is that after drawing each stroke, the canvas cursor always changes back to the Windows cursor. Which is troublesome because it results in random, unintended streaks on the drawing.

Not much to say about how to reproduce, except use Windows, and just pick any brush and try to draw strokes that are far apart from each other.
Watch for lines that connect them. The main thing is that if you see the Windows Cursor on the canvas, that's how the issue occurs. If you want to "toggle" MyPaint's cursor for reproduction purposes, just press "Esc"

**Comment by achadwick** [comment]
@AtsusaKaneytza
The cursor is "just" feedback, don't read too much into its exact appearance.  Although it's not displaying right according to the original report, that shouldn't matter. #470 would make the feedback more reliable.

The glitch is a new symptom.

That's an interesting coincidence you spotted. The cursor change could indicate some weird focus-like change that's also causing the glitch, I guess. I'm getting that the cursor outages correspond one-to-one, 100% with the streaks on this Yiynova MVP10U screen-tablet device - is that right?

* So the cursor outages don't happen on every pen-up? Or is it not even that predictable?
* I guess the streak happens when you put the pen down next after a "cursor outage" - is that right?
  - I'm assuming you draw those strokes from left to right here...
* Try pressing the F and D keys (change radius) as you're pen-up. That should cause a "cursor outage" 100% of the time according to the original reporter
  - then on your next pen down after F or D, do you *always* get the glitch?

**Comment by achadwick** [comment]
Don't know if the two aspects of this issue are really related yet. Let's see hos strong the association is.

**Comment by AtsusaKaneytza** [comment]
The cursor outage does, in fact, happen on every pen up. If the paint cursor is active, after pressing the tablet pen to the canvas and lifting it, the cursor reverts to the windows cursor, every time.

The paint streaks happen exactly how you describe.
(My personal fix for it is to change the pressure sensitivity settings in MyPaint, but even turning it down can still result in undesired streaks, so it doesn't totally fix the problem or work as a perfect workaround, so it's still an issue.)

Pressing F & D the way you said doesn't cause the cursor outage. Each time the pen is lifted is when the outage occurs, so changing the radius doesn't impact it. (The radius of the brush does still change)
So I always get the glitch when the pen's up. (And like I mentioned, pressing "Esc" will fix it so the pen reverts to the painting cursor.)

**Comment by achadwick** [comment]
[MyPaint v1.2.1](https://github.com/mypaint/mypaint/releases/tag/v1.2.1) is now out. Can you confirm whether or not this bug is still happening with it please? Our Windows build of 1.2.1 has a much newer GTK than the 1.2.0 build.

**Comment by zb13y** [comment]
I can't reproduce bug, so i think that problem was resolved.

1.2.1+gitexport.bcf5a28d (Python 2.7.13, GTK 3.22.7, GdkPixbuf 2.36.4, Cairo 1.15.4, GLib 2.50.1)
Windows 10 x64 1607 14393.693

P.S. I think that my bug and AtsusaKaneytza bug are different. Let's rename topic for only Yiynova MVP10U.

**Comment by achadwick** [comment]
@zb13y 
I think that's reasonable. Thanks for testing :smile: 

@AtsusaKaneytza 
Sorry we weren't able to address the glitch you found in this thread. Can you test with the latest stable release please? <https://github.com/mypaint/mypaint/releases/tag/v1.2.1>

If it's still happening, then please report a new issue, referring back to this thread with `#384`. Thanks!

**Comment by AtsusaKaneytza** [comment]
OS: Windows 10 64-bit
Tablet: Yiynova MVP10U Screen Tablet
MyPaint version 1.2.1 (32-bit)
the cursor inconsistency seems to be fixed at the moment. Will continue testing and update.
