### ISSUE TITLE
Exception on Reset Button from Brush Tool Options

### ISSUE THREAD

**Issue by ydahhrk** [mypaint/mypaint#403]
Click on Reset:

![Brush Tool Options](https://dl.dropboxusercontent.com/u/95836775/MyPaint/BrushToolOpts.png)

``````
```python
Mypaint version: 1.2.0-beta.0.73+gitexport.1932648
System information: Linux-3.13.0-55-generic-x86_64-with-Ubuntu-14.04-trusty
Traceback (most recent call last):
  File "/usr/share/mypaint/gui/mode.py", line 615, reset_button_clicked_cb(self=<FreehandOptionsWidget object at 0x7f2cb1e98a00 (gui+freehand+FreehandOptionsWidget at 0x33c4d20)>, button=<Button object at 0x7f2cb1e98b90 (GtkButton at 0x31d52f0)>)
        parent_brush = bm.get_parent_brush(brushinfo=app.brush)
        parent_binf = parent_brush.get_brushinfo()
        for cname in self.adjustable_settings:
  variables: {'parent_binf': (None, []), 'parent_brush': ('local', None)}
AttributeError: 'NoneType' object has no attribute 'get_brushinfo'
```
``````

`get_brushinfo` appears to be lacking when the brush being reset came from a shortcut (Brush > Shortcut Keys > Restore Brush _x_) defined from a brush that no longer exists (in a brush group). I discovered this by loading a brush that existed in a previous version of MyPaint.

I guess fixing this should be easy by graying out the button... but making the shortcut recall feature set the base settings would perhaps be more sensible?

Thanks

**Comment by achadwick** [comment]
In order to trigger this one, I have to physically delete the brushes from the settings folder. Just deleting the group using the actions popup doesn't suffice - MyPaint logically moves them to its Deleted folder.

The problem here is that the base setting just aren't available by name on disk. I guess in the absence of an existing parent brush at the time the settings are loaded, the working parent_brush_name could be reset to the name of whatever settings are being loaded into the working brush?

The parent_brush_name stuff is an early hack to make the brush list highlights work, IIRC. 

I'll patch up the code in that area so it doesn't raise an exception for now, and see if a better fix can be sorted out. The reset button also turns off eraser mode overrides (the "E" key, and the same for colourize and lock-alpha), so it still does useful things.

**Comment by achadwick** [comment]
Deferring the "doing it properly" part of this till after the 1.2.0 release, just to make myself feel a little less overwhelmed. I want to be rearchitecting how brushes and brush collections work then too.

**Comment by ydahhrk** [comment]
Ok, no rush :)

**Comment by achadwick** [comment]
@ydahhrk 
MyPaint v1.2.1 is now out. Can you test it out please, and let us know if this should be prioritized?

**Comment by ydahhrk** [comment]
Ok, I'll try later today.

**Comment by ydahhrk** [comment]
I managed to reproduce the exception again in tag `v1.2.0-beta.0` by loading a brush from tag `v1.0.0`. I can confirm that the exception is no longer raised in tag `v1.2.1`.

However, the settings do not reset to their defaults either, like they do with any other shortcut brush. I was assuming that you intended to enable this along the brush rearchitecting you wanted to do.

When I load a brush via a shortcut, and the settings do not exist "by name" as you said, I sort of expect MyPaint to create a temporary parent brush that can be later garbage collected when I switch again. This would enable the Reset button to work on deleted brushes, would it not?

That said, this bug does not really affect me; I have long since updated my old brushes. The current behavior is sort of undesired, of course, but I understand if you think that fixing it would imply too much undesired overhead. I can also offer to try and hack the code myself. But if you want to close this, that's fine by me too.

**Comment by achadwick** [comment]
I think the whole brush settings system needs an overhaul. The parent brush thing is, frankly, a nasty hack intended to allow for the "current brush" (i.e. the parent brush of the current active settings) to be highlighted in the brush panels.

Considering #259, I'd much rather do it by nearness in an array, much like we do for the current colour.

Closing for now.
