### ISSUE TITLE
Proposal: add "New layer group" button to layers dock

### ISSUE THREAD

**Issue by loentar** [mypaint/mypaint#406]
This is just an idea, not sure if this will be very helpful for all users.

![mp](https://cloud.githubusercontent.com/assets/4038431/9227682/776b8c5a-411d-11e5-8b1b-4cb92f419450.png)

When creating/arranging project structure using layer groups it's faster to click the button instead of using the context menu (in addition to menu of course)... 

https://gist.github.com/loentar/b337cfe0429082d5fc70

Probably the icon for the "new group" should be replaced to similar with plus sign...

**Comment by achadwick** [comment]
Yeah, I'm pretty down with this: it'll help make the feature more discoverable. Patch looks reasonable too (minus the changed submodule revision). I think this would be reasonable to have for beta, since no new strings would be added by it.

We'll have to make sure that it's greyed out at appropriate times, like New Layer Above.

(As an aside, I've always thought that we should have some sort of "Add Group as Parent" / "Remove Parent Group" pair where the Remove Parent action moves the children to the grandparent group's list first. Menu only, of course.)

**Comment by achadwick** [comment]
Done. I kept the layer-new button as just a `+` since painting layers are the default, and to keep the look of the area cluttered (the one above is a bit close to a `±` as well, to my eyes).

**Comment by loentar** [comment]
I was unsure regarding "add new layer" icon. Agree, the concept "layers are the default" is intuitive.
Cool, thanks.
