### ISSUE TITLE
No tooltips using tablet (Windows 10 x64, beta 1)

### ISSUE THREAD

**Issue by zb13y** [mypaint/mypaint#411]
Something wrong with tooltips in Mypaint 1.2.0. Windows 10 x64, 1.2.0 beta 1.

<i>Tablets generate a lot of very small movements, so tooltips often do not work. Tooltips require stillness. <b>Try taking your stylus out of range</b>: the tooltip may appear.</i>

That strange. I can see tooltips in Krita, Gimp, Inkscape, Chromium using my tablet. As i understood all of this programs uses trigger - stilness of cursor. And i think that i was able to see tooltips in MyPaint 1.0. But i can't see them in MyPaint 1.2.0, i tried to not move cursor, but tooltips doesn't appear. In mypaint 1.2.0 trigger tough - don't move cursor within 1-2 seconds, while in krita, gimp, inscape, chromium - don't move cursor in milliseconds.

There are another type of tooltips in windows, they triggers time. Hover 3 seconds and tooltip will appear, you can move cursor. Paint.NET have such type of tooltips.

**Comment by achadwick** [comment]
MyPaint uses GTK tooltips, not Windows ones. I won't add support for the Windows-specific tooltips you describe because there are just too many of them and they're scattered all over the code. Additionally I don't really want to add a load of platform-specific code for something trivial that has built-in support in the toolkit we use.

This is very likely to be an upstream issue, with GTK this time. Have you searched in the upstream bugzilla? Two upstream bugs stand out straight away:

* https://bugzilla.gnome.org/show_bug.cgi?id=542652
* https://bugzilla.gnome.org/show_bug.cgi?id=695695

So I'll try replicating this from GNOME/Linux as well to see if the behaviour is markedly different between Windows and Linux.

There are a number of GtkSettings properties which used to control tooltip periods and wait times (gtk-enable-tooltips, gtk-tooltip-browse-mode-timeout, gtk-tooltip-browse-timeout, gtk-tooltip-timeout), but they are all deprecated and ignored as of GTK 3.10.

As of GTK 3.12, we can use GtkPopover, which is a little speech balloon thing. I rather like them, and they can be used for providing detailed info or controls as a rollover.

Krita uses QT, a completely different toolkit.

GIMP and Inkscape use GTK 2, an earlier version of GTK where the properties named above may still work (they became deprecated in 2.12, but that is quite old even for the GTK2 series).

**Comment by achadwick** [comment]
**Triage note:** tentatively, this is an upstream issue, and should be tracked upstream. However this issue needs a comparison of Windows–GTK behaviour vs. Linux+X11–GTK behaviour.

**Comment by achadwick** [comment]
GtkPopover is too new for the GTK version we are using as a baseline for MyPaint 1.2.0. It's a bit bulky as well, better suited for display of a menu or a bunch of tools in response to a click on an on-screen button.

(That's sort of the way things are going anyway, in GTK3 - more touchscreen-related stuff by the day, and you can't hover with a touchscreen. I suppose that means we have to concentrate harder on making our UI immediately and intuitively obvious :grinning:)

**Comment by achadwick** [comment]
[MyPaint v1.2.1](https://github.com/mypaint/mypaint/releases/tag/v1.2.1) has now been released, and the Windows build contains GTK 3.22.7. Please can you confirm whether or not this bug is still happening in that version?

There should be something with tooltips in the GTK3-Demo program we ship too. You'll have to close the tablet pressure tester first to get to it through :grin:

**Comment by zb13y** [comment]
No tooltips. In demo popover works only on click, and it works fine but there are no demo with hover-tooltips.

**Comment by achadwick** [comment]
Thanks for the testing. Let's close this issue in that case. There's nothing we can do about it in the MyPaint codebase that doesn't involve a complete reworking of the UI, and I don't have time for that.

Upstream bug: <https://bugzilla.gnome.org/show_bug.cgi?id=695695>. Anyone who needs GTK tooltip behaviour to change needs to comment there and make their voices heard. You will need a login on the GNOME bugzilla.
