### ISSUE TITLE
Reverse color axis direction for 2 color pickers

### ISSUE THREAD

**Issue by BlenderNPR** [mypaint/mypaint#432]
While producing a comprehensive color course, we discovered reverse color axis in MyPaint **1.20**

The problem is the axis of some color pickers are reverse in direction to sliders version.
![screenshot from 2015-10-02 23 46 26](https://cloud.githubusercontent.com/assets/11452632/10263932/275c74f8-6a31-11e5-9c46-b27841e346f6.png)
![screenshot from 2015-10-02 23 46 29](https://cloud.githubusercontent.com/assets/11452632/10263939/3c3842bc-6a31-11e5-8f2e-b578a75e6124.png)
While the sliders do it correctly.
![screenshot from 2015-10-02 23 46 32](https://cloud.githubusercontent.com/assets/11452632/10263941/42f08f4c-6a31-11e5-8185-af912cae8a66.png)

Blender's color pickers follow the axis direction rule strictly.
Increase always toward the top or right direction.
![sv hsquare](https://cloud.githubusercontent.com/assets/11452632/10263956/7ce30d10-6a31-11e5-919f-35c4d76320ce.png)

GIMP's color pickers on the other hand have more serious UX problems, but that's for another bug report else where.

**Comment by BlenderNPR** [comment]
I missed 1 color picker UX inconsistency.

Color wheel, clockwise or CCW?

**Note:** Clockwise is referencing 0 deg toward 360 deg (the longer path)
red to yellow in clockwise direction

On Triangle Color wheel, hue is CCW. (incorrect)
On Square Color wheel, hue is CW. (correct)

For consistency, please use CW direction. Blender also using CW direction with red starting at the bottom (0 deg). The position of red hue isn't a problem (each software has its own convention), but the direction to next hue is important.

**Comment by odysseywestra** [comment]
For semantics sake, could you put down which version of MyPaint you are
using and your operating system. You can easily get that information by
going to Help > Debug > Stimulate a Crash and then click on Details. Thanks.

**Comment by achadwick** [comment]
I can't do anything about the triangle one: it's a GTK builtin: [GtkHSV](https://developer.gnome.org/gtk3/stable/GtkHSV.html), so its direction is fixed. Sorry! Not only is the Hue direction fixed to CCW, it doesn't respond to the colour wheel type setting
GtkHSV is old and deprecated upstream, and Should Be Removed from MyPaint because it has a ton of old bugs relating to it: see #268 about replacing it, and #266, #169 too.
Our colour circle/square selector pictured above is its designated replacement already, so maybe I should just be bold and remove the triangle selector for 1.2.0?

Somebody will have to redo the icons when we change the selector directions for the other ones.

I can't add HSV sliders to the slider control at this stage (strings are frozen), but maybe after 1.2.0 is out? Personally I think HCY is more useful anyway, but YMMV.

**Comment by BlenderNPR** [comment]
For your reference:
Mypaint version in question: **1.20 beta** 
OS: **Linux, Windows**

So GtkHSV is the problem with triangle wheel. 

I love Krita's color selectors, all are very consistent. But their small color picker has a problem, which I will report next.
![krita_color_selector_types](https://cloud.githubusercontent.com/assets/11452632/10264933/c7a2274c-6a4e-11e5-8679-19b5c6d703a5.PNG)

**Comment by 0ion9** [comment]
@achadwick 
HCY is MUCH more useful IMO. Not only that, but HSV is pretty much the absolutely least reliable of the HS* colorspaces.
It's true that there are many users who are used to HSV, but personally I'd suggest that the basic idea of HCY and HSV are similar enough that we can reasonably expect them to pick it up.
Adding another colorspace (whether it be HSV or something different) would IMO be moving towards the same UI problems that GIMP's color selector has.

**Comment by ShadowKyogre** [comment]
@BlenderNPR: From the examples I'm seeing, it looks like that the cube panels just need to be flipped horizontally to make it consistent with the color direction examples you've shown. I'll get to work on it ASAP.

@achadwick: I'm in favor of dropping the builting GtkHSV widget. It's a bit of a sight for sore eyes since it visually stands out from the rest of the widgets.
