### ISSUE TITLE
Pressure not detected OS X 10.11, MyPaint 1.2.0-beta.1+git.f4d79d1

### ISSUE THREAD

**Issue by rustacian** [mypaint/mypaint#434]
Currently I'm hunting through brushlib trying to find out why MyPaint won't detect pressure under OS X El Capitan. I'll see if I can reproduce this in a previous version as well. Sketchbook Pro and the Wacom app both detect pressure changes while MyPaint does not. Where would I go to find interaction between the driver and mypaint? What are the best ways to debug tablet issues? I checked the wiki and found a blank page for "Debugging Tablet Issues".

**Comment by achadwick** [comment]
I'm in the process of reinstating old wiki pages - I must get round to doing that one. IIRC the old one was terribly out of date, so it may take a while. Sorry :disappointed: 

This is quite likely to be an upstream issue: MyPaint can only use pressure information if GDK captures that info and adds it to each incoming event. Our pressure and tilt stuff is only as good as what GDK provides us.

I'm assuming this is an upstream bug initially, but please dig further and tell me if I'm wrong! :smile:  <https://git.gnome.org/browse/gtk+/tree/gdk/quartz> should probably be where you should start looking - that's the OSX platform-specific module for Quartz.

Does pressure work with other GTK 3.x programs on OS X? https://gist.github.com/achadwick/54e5b111e5ac908becf1 for example should do something other than flatline on pressure if you have a tablet.

libmypaint ("brushlib") is probably the wrong place to start looking, since IMX that *always* works if pressure information is passed on to it. libmypaint doesn't read pressures from any hardware by itself - that's not its job. You can verify that brushlib is working correctly when given different (faked) pressures by setting the pressure at a node in the Inking tool.

MyPaint has a handy input test window: Help→Debug→Test Input Devices. Hope that's of use for diagnosing this one.

Good luck!

**Comment by metakermit** [comment]
I am experiencing the same issue. I just tried it with GIMP and at first saw the same thing happening – no pressure sensitivity. Then I went into GIMP - Input Devices and saw that "Core Pointer" was selected instead of the "Quartz Pen". Once I selected the Quartz Pen, pressure sensitivity started working inside GIMP. Not in MyPaint, though, so I'm guessing it would be possible to allow the manual selection of these input devices in MyPaint too. Still, I think this used to work fine in before. Quartz would automatically select the correct input.

![screenshot 2016-03-05 20 36 30](https://cloud.githubusercontent.com/assets/1818628/13549959/6c925c04-e312-11e5-9e61-b13a7fe8b80a.png)
