### ISSUE TITLE
Can't change the language

### ISSUE THREAD

**Issue by shayli147** [mypaint/mypaint#435]
Hopefully I'm just blind, but there is no option that I can find to change (windows) MyPaint 1.2 beta's language, and I really need it.
MyPaint on my language isn't complete and I anyways always set all my programs to English.

If I'm right and there is no option- I hope this is the right place to ask to add it. If not, please let me know where to ask (since the user forum doesn't seem so active).
On the other hand, if there is a way, please help me to do it and sorry for the burden.

Thanks ahead,

**Comment by achadwick** [comment]
MyPaint 1.2.0-beta.1 and above should pick up on your global Windows settings for Region and Language.

* In Win7 Professional you don't get language packs through Windows Upgrade, but MyPaint should still use the language you set on the Formats tab (because MyPaint is open source, we can translate everything without reliance on MS's language packs - sure, it seems weird to be using the Formats setting, but apparently that's what others do and it works!)
* In Win7 Enterprise and above, it should pick up on your actual user interface language setting. I haven't tested any other Windows installations.

If that doesn't fix it, I will need to know a lot more about your system so I can treat this as a bug. Please read [CONTRIBUTING.md](https://github.com/mypaint/mypaint/blob/a9f71f27dc5894eb6e7bfe7a5a83722f8b0d1f0d/CONTRIBUTING.md#test-the-program-and-report-issues) and let us know. In this case, running from the console debug launcher may help diagnose the problem. For now, can you give me the exact version of Windows and the exact version of MyPaint you're using (you can go to the About dialog in MyPaint to find out - we need the whole thing including build info).

Here's the start-up code that deals with this stuff, for reference: <https://github.com/mypaint/mypaint/blob/a9f71f27dc5894eb6e7bfe7a5a83722f8b0d1f0d/mypaint.py#L256>

**Comment by shayli147** [comment]
Thank you for your reply, setting English under the Format did fix MyPaint
on that matter :)

About the open source "magical" behavior- I'm well aware of it as a Linux
user since Ubuntu 8.04 Hardy Heron (I think?).
To me MyPaint 1.0.0 was the perfect replacement for Corel Painter X since
2011 or so, and from ever since so I'm Happy to have it on my Windows too.
(Sadly I had to move back to Windows and run it on a stronger computer
since I couldn't convince some other strong softwares that I need to
cooperate with Ubuntu.)

To another subject, if I may.
I have been trying my best to work with my current MyPaint today after
having English back, but sadly I couldn't actually draw on it with my Wacom:

​I was trying to draw a single diagonal line (this one / ), then realized
that the brush was seriously delaying and adding all the extras. The
original stroke is somewhere in the middle of this weird chaos. The same
happened with all brushes. When stroking the same line using the mouse
there was no problem and it worked *just fine*.
Please note that my Wacom works as should under any other program. I have
also played with it's settings- nothing helped thus far.

MyPaint version: 1.2.0-beta.1+gitexport.a7012b4
OS: Windows 7 Ultimate

I have provided all I know to provide, if there is any more useful deta to
add please let me know what to do.

For the meantime I am running the friendly 1.0.0 alongside my other
programs, waiting for a solution.
Thank you again for your time and help,
Shay-Li

**Comment by achadwick** [comment]
Thanks for the confirmed fix on this language issue. You may also want to keep an eye on #438 as well, since that may affect the usability of MyPaint in the case of a particular translation being a mess or distractingly incomplete.

If you have awesome language skills and know MyPaint, you can dive in and help fix your language's translation with comments, changes, and suggestions. There's a (comparatively) easy tool for it at <https://hosted.weblate.org/engage/mypaint/>

There are a couple of open issues already regarding laggy behaviour on the Windows platform: #390 and #429, and I'd really welcome your feedback there. There are notes in those bugs/issues about specific Wacom driver versions which may show this behaviour, but we don't have enough data to tell users for certain not to upgrade to specific Wacom versions. If you could watch and follow up there and tell the other watchers your Wacom driver version number(s), that might really help.

I'd really love it if issue reports could be kept to one topic per numbered issue - that way us developers can close them meaningfully! So please search the issue tracker here if you find an annoyance - you may find it's already being discussed or worked on.

(And finally... sorry to be a bore but 1.0.0 is not supported now (limited time, mostly, and a need to get the kinks ironed out for next release). Though I hope it works well for you!)
