### ISSUE TITLE
origin marker in graph editor should use different symbol

### ISSUE THREAD

**Issue by jeisner** [mypaint/mypaint#464]
The graph editor (in brush settings editor) often seems to show a spurious control point that the line doesn't go through.  Sometimes this point isn't there at the start, but it's left behind when you move a control point - seems like a graphics glitch.

It took me a while to realize that it was actually marking the origin (0,0).  

For clarity, I think it would be better to use a symbol for the origin that is _different_ from the symbol for the control points.  I would suggest a thick "+" that is large enough to stick out behind any control point that may be sitting on top of it.  (Alternatively, instead of using a symbol for the origin, you could just thicken the x=0 and y=0 lines.)

**Comment by odysseywestra** [comment]
Your right the orgin point on the graphic should have a different symbol like tirangle. From the looks of it we should be able to address this before the 2.0. I'll leave @briend and @jplloyd decided here.

**Comment by jplloyd** [comment]
> It took me a while to realize that it was actually marking the origin (0,0).
@jeisner 

You realized incorrectly and nobody corrected you. The assumption is understandable however, as that marker is (from what I can tell) completely undocumented.

The marker actually indicates the x-coordinate (relative to the xmin/xmax mapping) of the "normal" input value for that input. This is sometimes 0.5, sometimes 0, and for pressure 0.4 (for some reason). These are constants that are (these days) defined in `brushsettings.json` in libmypaint.

Since there are now 64 control points, there is generally less need for decreasing the input range (for the sake of precision), though I'm sure it can still be useful in some situations. We'll change the drawing of the marker so that it won't be mixed up with the control points. I think a green vertical line should suffice, possibly covering the entire grid vertically, since its position on the y-axis has no meaning.

**Comment by odysseywestra** [comment]
Okay now that we know what that does, it still will probably be a better idea to use a symbol instead of color. I say this because of people with colorblindness which would probably break ux flow for them.

**Comment by jplloyd** [comment]
Fixed with a hopefully inoffensive compromise in: 23e0c6226db292f066fa094e3da3891762cd59cb
