### ISSUE TITLE
Each stage of loading an OpenRaster document is rendered, resulting in glitches

### ISSUE THREAD

**Issue by jeisner** [mypaint/mypaint#468]
When a scrap loads, the initial view is somewhat "off-center" -- translated a bit in both the x and y directions, though the direction and amount of translation vary by scrap.  Then the view corrects itself as if someone had hit F12.  

This wasn't the case in the previous MyPaint release, where it was very clean and quick to page through the scraps using F6/F7.  Now there is a distracting jumpy effect.

**Comment by achadwick** [comment]
Reproduced. I suppose it's true of all file loading, just most apparent with the faster scrap switcher commands. It would be nice to investigate this before the release of 1.2.0.

Since we make the rest of the UI insensitive while a document loads, freezing (and dimming?) the canvas's display during load makes sense to me too. We used to snapshot the canvas widget's display during load to avoid glitches, but the old implementation depended on a GTK2-era bodge involving GdkPixmap, and this was removed during the port to GTK3+GI because GdkPixmap was removed upstream. Time to reinstate a workalike using the new API at least.

Related glitch that the proposal above would fix: if a large document has a lot of layers, they'll load one-by one, and this will cause display updates as the layers load. The result can be weirdly unsettling if you usually paint eyes/irises/their specular highlights on separate layers. Since OpenRaster document order means that layers on top load last, you'll see incomplete renderings as the layers are loaded... :eyes: → :black_circle::black_circle: → :fearful:!

**Comment by jeisner** [comment]
There is another related glitch.  Although layers may load from back to front, the *background* seems to load last for some reason.  

For example, if your *current* drawing has a purple background, then loading a scrap that has a white background will show it at first on top of a purple background, and then the background will switch to the saved white background.

**Comment by achadwick** [comment]
Yeah, background layers are loaded specially :)

That glitch should have gone away with f40bd31 too, but please test.
