### ISSUE TITLE
"Pick Stroke and Layer" could do more on flood fill

### ISSUE THREAD

**Issue by jeisner** [mypaint/mypaint#475]
The W key usually sets the layer, color, brush, and paint mode to match whatever you're pointing to.  

However, if you're pointing to a flood-filled area, it only sets the layer.  I understand that there's no stroke there to match ... but I would kind of expect it to also set the color, return the paint mode to normal, and possibly even select the Flood Fill tool (in lieu of selecting a brush).

**Comment by achadwick** [comment]
For this to work, the mask of the fill needs to be computed and then inserted into the strokemap.

Actually, having separate 1bpp stroke mask would be brilliant for the purposes of filling correctly too - we currently use a magic pixel value to determine where the fill has been in the past. There is some dubious code in `lib/fill.cpp` that outputs a filled pixel with a tiny alpha of 0x0001 [÷ 2<sup>15</sup>] when the tolerance check rejects a pixel to avoid revisits. Feeding it a separate mask may help with this issue and make the C++ fill code more understandable, but is the mask of "pixels the fill algorithm tested" going to be as useful as the mask of "pixels the fill algorithm filled"?

**Comment by jeisner** [comment]
> but is the mask of "pixels the fill algorithm tested" going to be as useful as the mask of "pixels the fill algorithm filled"?

Probably not.  However, I suppose you could accumulate a stroke mask with all tested pixels, while also maintaining a temp list of rejected pixels.  The fill algorithm makes use of the stroke mask as you say.  Once the fill is complete, the rejected pixels are deleted from the stroke mask before it is added to the strokemap.

**Comment by odysseywestra** [comment]
Closing this issue infavor of #843 which should also address this issue as well.

**Comment by jplloyd** [comment]
That issue does not address this at all; _it_ concerns the ability to "dig down" into multiple layers of strokes, being able to pick older strokes that are obscured by newer ones.

The more general version of _this_ issue is that we don't store information about _which tool_ was used when the output was produced (and the context/settings of that tool). Other examples of this: picking a stroke that was created with the ellipse tool will not restore the ellipse tool, picking an ink stroke won't restore the ink tool.

_If_ this is added, it should be configurable to retain the old behavior, except possibly for the fill output, since that should not really have any brush data associated with it.

A preliminary thing to do is to be more lenient in the stroke-context restoration mechanism, wrap it in try-except and do nothing if it fails. That means we don't have to break file-forward compatibility* if generalizing the strokemap data in the future.

\* Meaning: picking a stroke from a file created in a newer version of MyPaint could cause crashes.

Anyway, since "Pick Stroke and Layer" _can't_ actually do more without changing the format, we'll leave this closed.

**Comment by odysseywestra** [comment]
Okay well, what I'll do is is I'll add this as part of the scope of the work for pick and stroke when I transfer #843 over to the Community Forums.
