### ISSUE TITLE
Edit list for "Edit layer in external app..."

### ISSUE THREAD

**Issue by jeisner** [mypaint/mypaint#477]
When I try to edit a vector layer using an external app, MyPaint somehow comes up with a list of programs that can handle SVG inputs.  The list happens to have 3 kinds of problems on my Linux system:
- Some entries are missing.  I installed Dia, but it does not appear.  I'm not sure how to register it as a handler for SVG, and MyPaint's dialog box doesn't offer a Help button to explain how, nor does it let you enter a path to an arbitrary program.
- Most entries are inappropriate because they are actually viewers rather than editors - they can read SVG but not write it.
- One entry is mistitled.  LibreOffice can handle SVG, and clicking on it does open LibreOffice Draw as desired.  However, the entry is _listed_ as LibreOffice Writer, so I didn't realize for a while that I had access to LibreOffice Draw

Are there any reasonable options for improving this?  The first point above seems like the most important.

**Comment by achadwick** [comment]
Not to my knowledge - desktop entries have no way of distinguishing between whether the tool is an editor or a viewer.

The default one should be listed near the top, then any the DE has recorded as "recommended", then other tools which just happen to be capable of opening the file.

Please check dia.desktop (or whatever the file is). Is there an entry for "image/svg"?

Please check that there is a libreoffice-draw.desktop on your system that launches "libreoffice --draw".

Code in question is in gui/externalapp.py.

**Comment by jeisner** [comment]
**Regarding applications that are missing from the list:**

* Dia does get added if I edit  /usr/share/applications/dia.desktop to include image/svg+xml on the MimeType line, and then run update-desktop-database.  I've filed a bug against the dia-common package, which provides dia.desktop: https://bugs.launchpad.net/ubuntu/+source/dia/+bug/1514093

* Similarly, LibreOffice Draw gets added if I do the same for libreoffice-draw.desktop.  Does a bug need to be filed against LibreOffice?  Or is there already some information in libreoffice-draw.desktop that MyPaint could use to cast a wider net and discover it?

Again, it might be nice if the MyPaint dialog allowed you to browse for an arbitrary external program that is not on the list.

**Regarding applications that are uselessly on the list:**

Unfortunately, image/svg+xml inherits from application/xml, which inherits from text/plain.
So any application that can read text/plain is listed, including all text editors and web browsers on the system.
I don't grok why /usr/share/mime/subclasses elects to set up such aggressive inheritance ... 
Given that it does, should MyPaint use some kind of narrower test that skips inheritance?

**Comment by odysseywestra** [comment]
Basically what he asking for is the ability to use an other applications
option for External Edit. For  example, I can't use Krita as an application
option, it would be nice to click on other applications to select
regardless if it has support. That way we could indirectly be able to use
G'MIC indirectly via scripts and such. So this should change from a bug to
a feature request.

**Comment by AtsusaKaneytza** [comment]
Same issue happens with Windows.

**Comment by achadwick** [comment]
Gtk.AppChooserDialog looks pretty smart for this on Linux (better than maintaining our own code), but is super-crashy and broken right now on Windows (see #531) despite supposedly being portable.

I want a simple interface for this, ideally just select "Edit in app" and launch the right program We're too complex already (see #98).

\*Sigh\*. I guess we're going to need two commands...

* Edit Layer in System Default App
* Edit Layer in Chosen App...

The first command would launch the system default app immediately, allowing us to use `os.startfile()` on Windows. That turns out to be a great way of working around broken GLib on that platform. On Linux, where GLib/Gio tends _not_ to be completely broken, we could use the equivalent calls to get and then launch the default app. These defaults can be overridden by the user of course, but you have to use the 

The second command might launch a dialog, which could contain os-specific and complicated parts. It could embed a standard Gtk.AppChooserWidget on non-broken platforms. It could sport an additional "custom" tab with a `[+][-]` buildable list of known executables and scripts which wouldn't be refined in any way by MIME type or file extension.

Experimental code drops showing what you want, or UI mockups would be great.

**Comment by jeisner** [comment]
How about moving the choice of PNG and SVG editors to Edit Preferences / Load&Save?
Then there's only one command -- Edit Layer in External App -- which launches the preferred application immediately, just as you want.
It's ok if the preferences tab has a more complex interface, such as radio buttons for "System default app" / "Other registered app ..." / "Browse filesystem for app ..."

**Comment by achadwick** [comment]
@jeisner 
Non-PNG bitmap layers, and generic file layers are supported too, for forward compatibility and file structure preservation reasons.

I don't want to clutter the central prefs with too much. Better to have configuration for a feature be part of the UI flow for the feature. That way it's discoverable when the need arises. In this case, there would be a choice from a list of registered editor executables, so IMO it would be better practice to add `[+][-]` icons to that list.

Such added editors might just be scripts, which might operate on more than one type of layer. The only requirement is that they should overwrite their argument with a file of the same type (at some future time after being forked or started) in order to make a new layer revision.

**Comment by jeisner** [comment]
+1 for discoverability.  But it would sure be nice to be able to open one's standard external app with a single command assigned to a keystroke, without having to go through a dialog to select one every time.  I don't know how to merge that convenience with discoverability.

It's true that if you didn't have a standard app but a collection of scripts, you'd want the ability to choose the right script -- but in principle, a master script could launch a chooser of its own.

**Comment by achadwick** [comment]
> But it would sure be nice to be able to open one's standard external app with a single command assigned to a keystroke, without having to go through a dialog to select one every time. I don't know how to merge that convenience with discoverability.

Well, if that app is the system default one, you'd have a bindable keystroke that just does the thing. Otherwise you'd be able to bind the fancy-edit dialog, and I guess that could remember your last choice for the list? A sequence of two keystrokes seems fine to me for your usecase: `Ctrl+thingy` then `Return` to bash on through the dialog.

**Comment by jeisner** [comment]
Fancy-edit dialog defaulting to the last chosen setting is a good idea.
With the system default app being the initial choice.

In this case, is it really necessary to have a separate command for the system default app?
The single fancy dialog could list all options: system default + registered executables, plus/minus any past user edits (the [+][-] icons you suggested).

**Comment by achadwick** [comment]
Fixing this would also help with #598.

**Comment by odysseywestra** [comment]
@jeisner Could you move this thread over to https://community.mypaint.org/c/feature-requests? I'm working on cleaning up the issue tracker by move all feature requests there so we can get community feedback. If you can also set your post as a wiki that way we can edit the scope of the feature request that would be awesome as well. Don't forget to link back to here as well so I can keep track of it incase we need to reopen the issue. Thanks.

**Comment by AesaraB** [comment]
Closed in favour of #1217
