### ISSUE TITLE
Ugee 1910 tablet + MyPaint w64: strokes frequently glitch to top left corner of screen

### ISSUE THREAD

**Issue by monbetsu** [mypaint/mypaint#483]
I recently downloaded the MyPaint w64 on windows 10. It worked fine the first time I opened it, but the next time I opened the program and tried to start sketching my lines started to glitch.
![jhh](https://cloud.githubusercontent.com/assets/15673487/10972674/7ee0ee14-8397-11e5-81cd-c61945c5571e.png)
I used the Ugee 1910 graphic tablet, at first I thought it was a problem with my tablet, but it works fine on other programs. 
I haven't found any solutions to this does anybody know how to fix it? I have re-installed this many times, nothing is working.

**Comment by achadwick** [comment]
Hi - thanks for reporting.

Did you restart your computer at all during these tests?

What version of MyPaint is this? Looks like a recent beta. Can you go to the About box and tell me that number in full?

What version of the Ugee drivers are you using? Are they the latest ones available from the manufacturer?

Is pressure working in MyPaint?

How does the device appear in the Devices tab of the prefs window? How many entries are there?

This *might* be fixed in the recent ab2bb78ae81efeebd563f5759239c41ccfaa82f8 if my hunch about what's causing this is correct, but that commit is not in any release yet (watch this space...!)
We have some instructions for making test builds if you're interested.

**Comment by achadwick** [comment]
Also, excerpts of a console debugging session might be useful (there's an entry in the Start menu, at least on Win7). Are there more "device change" events than there should be?

```
[...]
DEBUG: gui.device: Device change: name='SYNAPTICS Synaptics Large Touch Screen' source=GDK_SOURCE_TOUCHSCREEN
[...]
DEBUG: gui.device: Device change: name='DLL060A:00 06CB:2734' source=GDK_SOURCE_TOUCHPAD
[...]
```

Plese paste anything useful you see there, or in Help → Debug → Test Input Devices, between backtick fences:

    ```
    [blah]
    ```

and it'll come out nice in github.

**Comment by achadwick** [comment]
Oh, and (as if I'm not asking enough questions) - would you say that the lines due to the glichies are always pointing at the top-left of the screen, or of the whole display area if you use lots of screens? Could just be the Ugee driver burping out a (0, 0) every so often. Help → Debug → Test Input Devices will record any times that happens so you can see/paste.

**Comment by AtsusaKaneytza** [comment]
Windows 8.1 64-bit user here, just wanting to add that pen pressure has always glitched in the 64-bit versions of MyPaint. Even when tablet drivers are up to date. I don't know (or remember, since I've reported it before) what the deal is with why.

**Comment by achadwick** [comment]
@AtsusaKaneytza Thanks for the reminder. @tumagonx mentioned it too, over in #493, part of which is a duplicate of this one.

@monbetsu Are your tablet drivers UC-Logic ones? I'm not sure how you'd tell, perhaps by finding the driver files and inspecting them, perhaps in the Remove Programs list.

General workaround for people to try: please try a MyPaint-w32 build if you are affected by a glitch looking like the one reported here ☺
It seems to primarily affect non-Wacom tablets using UC-Logic electronics and drivers. As mentioned in jeremyb796's [MonoPrice/Huion/UC-Logic Tablet FAQ on deviantart](http://jeremyb796.deviantart.com/journal/MonoPrice-Huion-UC-Logic-Tablet-FAQ-For-Win8-10-383719351), this tech is used in "many brands, including MonoPrice, Huion, and SOME Yiynova tablets and screens", and typically the stylus will have a battery inside it.
Right now, this is looking more and more like an upstream issue in the proprietary drivers for this kind of tablet, and there is not much we can do about that in MyPaint. We generally add workarounds for the issue with these tablets, which do some notably weird things under the Linux drivers too, and there is one on its way in ab2bb78ae81efeebd563f5759239c41ccfaa82f8, which will make it into the next build.

I will hopefully be releasing a new beta build soon for Windows users to try, with a mypaint-w32 version available.

Maybe I should offer round an Amazon wishlist and start building myself a hardware library :stuck_out_tongue_winking_eye:

**Comment by AtsusaKaneytza** [comment]
Okay, I THINK I know what part of the problem is concerning this issue
I noticed that when installing any UC-logic manufactured drivers, for Monoprice and Yiynova tablets anyway, they only install 32-bit based Tablet drivers (WinTab32? There's no WinTab64 drivers, as far as I know) and that MAY be part of the issue, with why tablets don't work with correct pen input in MyPaint's 64-bit version? 

It may also explain why Wacom tablets work fine with MyPaint 64-bit (if I remember correctly...?) I'm not very tech savvy and it could just be a shot in the dark. Especially since drawing with pen pressure in other applications works fine as long as the drivers are up to date. This is just speculation though.

**Comment by tumagonx** [comment]
Their installer are buggy indeed, but you still can install the 64bit wintab32 manually, it will detect the tablet but with no pressure or have haywire issue AFAIK.

**Comment by achadwick** [comment]
@monbetsu Is this problem still happening with MyPaint's v1.2.0 stable build? Please respond.

@AtsusaKaneytza I'm not sure I've ever seen a wintab64.dll on any system, but I have to confess I'm not that familiar with Windows tablet stuff really. Anyway, reasons like this are why we build for two architectures.

**Comment by achadwick** [comment]
@monbetsu Any updates? Please try the most recent stable release. Thanks.

**TRIAGE NOTE:** unknown mypaint version, unknown GTK libs. Cannot say for certain where the issue lies. Stale issue, and it's had long enough. Close after a week if no further feedback.

**Comment by achadwick** [comment]
No feedback, report has gone stale and original reporter has vanished. Closing.
