### ISSUE TITLE
Idea to Speed Up Translations

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/mypaint#487]
Maybe we could help speed string Translations by using Google translator and mark it as fuzzy. That way we could get those who are native speakers but don't understand English an opportunity to revise it so it makes sense in their language.

Google translator may not be the best in the world, but it doesn't cost anything to use it. Just an idea I guess.

**Comment by achadwick** [comment]
I'm opposed to it. Machine translation has happened in the past for zh_CN (I think), and the results were by all accounts pretty awful.

I realize that fuzzy translations wouldn't be shown by default.

* Who would own the copyright? (partly solved, [here's the Wikimedia Foundation's preliminary perspective](https://meta.wikimedia.org/wiki/Wikilegal/Copyright_for_Google_Translations)
* What are the technical requirements for doing this?
* What languages should this be done up front for?
* How to distinguish a language with only a machine translation from one without, so that we can see at a glance what needs work?

This functionality is built in to the Weblate service we use (e.g. <https://hosted.weblate.org/translate/mypaint/mypaint/el/?type=untranslated#machine>). You have to click on-screen buttons to invoke it, and it is part of a manual workflow, but perhaps that's OK.

**Comment by odysseywestra** [comment]
>Who would own the copyright? (partly solved, here's the Wikimedia Foundation's preliminary perspective

That was what I though as well since the source strings are technically owned by the project. Even when I research google Translate API they said they do not claim ownership of content submitted or translated. Remember the google translation android app translates voice conversations as well and can translate signs. https://cloud.google.com/translate/v2/terms?hl=en

>What are the technical requirements for doing this?

Basically would just require web browser with the google translate page up. No google account is needed. Plus also having the weblate hosted page up too.

>What languages should this be done up front for?

I would say the ones google translate can do well on. https://en.wikipedia.org/wiki/Google_Translate

>How to distinguish a language with only a machine translation from one without, so that we can see at a glance what needs work?

I don't think that would matter since both would be marked fuzzy. In the end they both would have to be reviewed. Plus since Weblate uses git, the name of the translator is post on git log. So in essence we could create an account for google translate use. And have a idea of what strings it translated.

>This functionality is built in to the Weblate service we use (e.g. https://hosted.weblate.org/translate/mypaint/mypaint/el/?type=untranslated#machine). You have to click on-screen buttons to invoke it, and it is part of a manual workflow, but perhaps that's OK.

Yeah, that what I meant when I said to mark the translation string as fuzzy.

**Comment by achadwick** [comment]
I'm going to say "no" on this one because I don't really have the time myself to do this for every language we might support, nobody else is picking up this issue and doing anything with it, and we already have a machine translation solution in place (!)

I must confess I'm highly dubious about the merits of mass machine translation. That strikes me (still) as more of a source of unchecked errors than a positive benefit for MyPaint.

I'm much more confident that machine-translating individual strings has merit, providing our translators can and do correct the machine translation immediately, while in the process of their regular, informed, nuance- and context-aware workflow.
