### ISSUE TITLE
Yiynova tablet (UC LOGIC drivers) + MyPaint w64: multiple issues

### ISSUE THREAD

**Issue by stkopp** [mypaint/mypaint#493]
So, there are 4 main problems:

1) When I am trying to draw on a canvas, MyPaint seems to start messing with buttons. It "turns on" moving tool while I am painting.

2) Second issue appears after some seconds of drawing. MyPaint starts to make strokes towards the infinity :) see attachment
 ![issue](https://cloud.githubusercontent.com/assets/11293909/11112683/9460f7a4-8926-11e5-8512-369e3e502da2.png)

3) There is no pressure sensitivity :( 

4) Menu do not responce to my action correctly. I can not pick a colour or select brush.

Also, when I disable "3 buttons stylus pen (Pressure)" and delete actions for left mouse click - first 2 issues disappears but third and fourth issues still in place

Also, if it will help you, yiynova (as I understand) uses UC LOGIC drivers.

I am using Windows7 x64

**Comment by tumagonx** [comment]
64bit MyPaint? If so, this is well known issue. Basically tablet got recognized but not works with mypaint well (including Gimp 64bit I guess).
Try 32bit version, UC-Logic-based tablets should work well.

This is upstream issue whichever GDK(Mypaint component)/UC-Logic that bring compatibility first.

**Comment by stkopp** [comment]
Wow, thanks that helps.
But new issue is appeared.

Now Mypaint starts painting with offset. Seems like program is trying to paint over my 2 monitors instead of tablet one. I turned off the first monitor and MyPaint respond correctly.

**Comment by tumagonx** [comment]
That's another known issue I think something like #410

**Comment by achadwick** [comment]
@tumagonx gtk-3.18.3 is built upstream by msys2 now, and the build issue has evidently been fixed too - we now have i686 and x86_64 builds. I should make some more MyPaint builds soon featuring those for both platforms, since it hopefully rolls up the tab dragging showstopper that's been delaying us.

----------------------------------------------------

@stkopp Thank you for reporting. Please report one problem per issue if you can. It makes it simpler to close issues once the problems are solved or determined to be duplicates :smiley:

* The [(new) offset problem](https://github.com/mypaint/mypaint/issues/493#issuecomment-156038002) is a known issue: #410, so that emergent part is presumably a duplicate?
* The glitches problem (original 2.) is already reported, I think: #483.
* Pressure sensitivity on Win64 Mypaint (original 3.) is mentioned by @AtsusaKaneytza [here](https://github.com/mypaint/mypaint/issues/483#issuecomment-154962137) in issue #483 - I think that's for a non-Wacom tablet, since pressure works fine for me with 64-bit Mypaint+Windows+drivers.

That leaves two:

* What _seems_ to have been random bad button presses (original 1., because panning is bound to middlebutton+drag by default) under Win64 + Mypaint-w64 has a) seems to have been solved by using MyPaint-w32 instead, and b) has never been reported as far as I can tell. This looks very much like a fault in the proprietary driver, given the differing behaviours, so there's not much we can do.
* The original report's 4. has (AFAICT) never been reported either, and it's a bit vague (sorry). *Can you confirm that this too has gone away by using MyPaint-w32 instead?*. It does sound like the sort of thing that might be related to 1. though.

**Comment by stkopp** [comment]
@achadwick 
Everything (except offset problem) was fixed by installing x32 bit version of MyPaint (no glitches and correct pressure sensitivity). 

Offset is still an issue. Everything works correctly if I turn off one display
![offset](https://cloud.githubusercontent.com/assets/11293909/11119233/17c5bcf6-8959-11e5-9fb3-e9270e43d332.png)
![no offset](https://cloud.githubusercontent.com/assets/11293909/11119237/1bc93a80-8959-11e5-8abe-30f8b7881fee.png)

I tryed to run your gdk-screen-layout-tester.py but, am so lame :) I did not figure out how to run python scripts.

**Comment by achadwick** [comment]
@stkopp Thanks for the confirm, glad the faults seem to be fixed! You may find the offset goes away with the latest build too (see the conclusion to #410)!

Some people report the 64-bit build works better, others the 32-bit build. I guess we'll just ahve to continue to make both and tell people to try one then the other for tablet issues.

The tester is really just my proof of concept (that GDK knows about displays), no need to get it running or anything.

Closing now, think we've wrapped up all the sub-issues ☺
