### ISSUE TITLE
Redo unsaved work dialogues (bad translation)

### ISSUE THREAD

**Issue by zb13y** [mypaint/mypaint#503]
Is it possible to redo unsaved work dialogues? Discard - bad answer, at least in russian. Better to use questions with basic answers - yes, no, cancel.

Example:
Do you want to resume(quit) without saving? - Yes, save as scrap, cancel.

Not critical, can be done after 1.2.0.

P.S. Unable to traslate word 'discard' using weblate.

**Comment by achadwick** [comment]
The whole way that dialog is constructed looks a little dubious to me...

https://github.com/mypaint/mypaint/blob/v1.2.0-beta.3/gui/filehandling.py#L309

patches welcome, I suggest "Yes", "No", "Save as Scrap…", and to ensure that all the questions it asks are "Do you want to (verb) without saving?" ones, with context. Let's avoid using stock too, because mixing stock responses and translatable ones is probably bad for i18n.

I guess it would make sense to look at this together with #501.

**Comment by achadwick** [comment]
This issue should be closed with those recent commits. Expect new strings on Weblate shortly ☺
