### ISSUE TITLE
Eyedropper tool picks wrong color

### ISSUE THREAD

**Issue by loentar** [mypaint/mypaint#504]
When using eyedropper tool in Background->Color picked color is not always the same as visible when you trying to pick color from canvas or docked color chooser. When picking standard controls, the color is OK.

Looks like it works properly with canvas only when you reset view. If you move or scale canvas the picked color is always like the canvas view is not moved/scaled.

Also when you pick color from docked color chooser you always get green palette, no matter color you see in chooser.

Here is screencast (please sorry for sketch :)
https://drive.google.com/file/d/0BwvdX1pBENi1eXBiS2ZrZUZrWW8/view

Do this problem related to video overlay?

Additional info: Ubuntu 15.04 x86_64, Video adapter Intel HD 4500.

**Comment by achadwick** [comment]
Seems this one has sat around without a response for some time. Sorry, I should have said something.

The colour picker you're using in the video is one we only half-support. It's part of a deprecated GTK colour chooser that we only keep around because users have asked for the ability to type in hexadecimal colours and similar things. Because the implementation is buried deep in GTK's code, and upstream have already deprecated it, I don't think we can do anything about this in the MyPaint code.

Luckily, MyPaint has other eyedropper tools built in. They only pick from the canvas, but the transformations should be spot on. Try holding the "R" key down, or using the eyedropper on the toolbar, or the one in the bottom left corner of the screen.

**Comment by achadwick** [comment]
I'll close the issue on the assumption that it's the one in the video you're reporting only. If it's one of ours (the "R" key one, or the ones in the main MyPaint UI) and you're using a recent build, please shout at me and get me to reopen this as a bug :smiley:

**Comment by achadwick** [comment]
You might to try "gcolor2" too - it's an independently maintained bit of code that shows the old GTK colour dialog. Colours can be dragged into MyPaint's main window from external apps, so that'd be a quick way of sharing.

**Comment by 0ion9** [comment]
@achadwick [gcolor3](https://bbs.archlinux.org/viewtopic.php?id=158663) is analogous but actively maintained, GTK3 based, supports hex, and is otherwise nicer, so it might be a better option. [GPick](https://github.com/thezbyg/gpick/) is much more ambitious but provides similar functionality as well as other things that are helpful for drawing (measuring, gradient generation, scheme generation).

**Comment by earcanal** [comment]
"Colours can be dragged into MyPaint's main window from external apps".  How do you do that?
