### ISSUE TITLE
Progressbar for loading and saving big files?

### ISSUE THREAD

**Issue by nekohayo** [mypaint/mypaint#509]
So I've been drawing with a file that is ~7200 x 10,800 pixels for the past few days, and even on a pretty beefy machine (8 cores, 32 gigabytes of RAM), loading and saving that 100-200 MB .ora file is slow (10, maybe 20 seconds, didn't verify with a stopwatch).

It works well, but I would like to have some indication of progress, since it "disables" the app during the process and I end up sitting and staring at the screen to see that subtle statusbar text change. A progressbar widget (that shows up only when needed) would be much easier to watch from the corner of the eye while I multitask, and it would also make me more patient from a psychological standpoint :)

From a technical standpoint, the heuristic behind such a progressbar might be something as simple as using the amount of layers saved/loaded vs the total amount of layers (I noticed that mypaint loads layers one by one…).

**Comment by clessley** [comment]
@achadwick @jimmac  @deejay1 @jonnor 

The file sizes I will be dealing with are similar to @nekohayo ~ 16K x 10K @ 300 dpi. CPU core utilization seems to be an issue?

I am spec'ing out a new machine for use with MyPaint (and Krita) specifically. I was considering an 8 core Xenon or an [i7 setup](http://pcpartpicker.com/list/2xvkd6) both with 64 RAM and at least a Nvidia GTX 960.

Thoughts on files that might be pressing ora files 1GB each?

**Comment by 0ion9** [comment]
@clessley 
AFAIK, there are difficulties with parallelizing compression  because of the way zip files (and also PNG files) are structured.
* We are trying to store a compressed (png) file -- the layer content -- in a zipfile
* Because the file we want to add must be compressed, we can't predict its exact size.
* Since we can't predict its exact size, we cannot predict where the next file's data should start.
* So we can't compress more than one layer at a time

It's possible to parallelize compression of an individual PNG, but [definitely complicated](http://stackoverflow.com/questions/10827247/parallelization-of-png-file-creation-with-c-libpng-and-openmp). AFAICS we do not currently do this (but correct me if I'm wrong, Andrew).

I'm not sure whether it's possible to disable PNG compression entirely when saving projected-to-be-large ORA files. That might be a bad idea, but it ought to open up the possibility of encoding N layers in parallel (one per core), since we could accurately predict the size of the output PNG.

**Comment by achadwick** [comment]
Working on this, just chasing through a few final bugs in the implementation.

![Progress bar screenshot](https://user-images.githubusercontent.com/61299/28734337-5f772998-73d8-11e7-8e0b-2620c7b0ca57.png)
