### ISSUE TITLE
White panels background in Ubuntu 14.04

### ISSUE THREAD

**Issue by flyasky** [mypaint/mypaint#525]
MyPaint 1.2.beta3
Theme Ambiance, GTK 3.10, Unity, Ubuntu 14.04 (Theme Ambiance, GTK 3.14, Unity, Ubuntu 15.04)
Top toolbar is dark, but other panels are white.
Panel in Nautilus is dark, but in MyPaint is white - changing theme has no effect
![screenshot from 2015-12-07 02 33 06](https://cloud.githubusercontent.com/assets/213282/11616709/0410f97e-9c8b-11e5-810e-13dc7115f61c.png)

**Comment by achadwick** [comment]
This is normal for the Ambiance theme, and MyPaint sidebars and Nautilus side panels are different things.

What did you change the desktop theme to? Light/dark mode in the MyPaint prefs only works with themes that support it. Try Adwaita if Ubuntu offer it.

**Comment by achadwick** [comment]
**Triage note:** probably nothing to do here. We don't promise a specific look for the program because we rely on a toolkit which can be themes by the user. The light/dark toggle is a hint to the theme, no more.

Close after 2 weeks if no feedback, or if this discussion doesn't uncover anything that needs fixing.
