### ISSUE TITLE
Horizontal/snowflake symmetry

### ISSUE THREAD

**Issue by android272** [mypaint/mypaint#529]
The current symmetry tool is very nice especially now that you can move it and delete the line.  But you can not make your image symmetrical horizontal or choose the angle of the line or add more than one line.  It would be really nice if you we had more lines of symmetry.

Horizontal symmetry would work exactly like vertical symmetry does now.  You select it and it mirrors what ever you draw on one side of the line to the other. You can also move the line and delete it as you can with vertical symmetry. the icon could be something like a mountain reflecting in a lake.

![Image of mountains](http://thumb7.shutterstock.com/photos/display_pic_with_logo/411121/411121,1256579078,1.jpg)

Then there is snowflake symmetry where you have many lines of symmetry.  I don't know how you would handle adding and subtracting more lines of symetry. The icon would be a snowflake.

![Image of snowflake](https://cdn0.iconfinder.com/data/icons/good-weather-1/96/weather_icons-68-512.png)

**Comment by achadwick** [comment]
I're reported the brush engine aspects of this as mypaint/libmypaint#27. Although we may end up doing it in MyPaint itself if axes get very complex: perhaps one active brush state object per reflection, and one original. We'll have to see what's possible.

Even if libmypaint is updated to allow fancier symmetrical painting, there will still be user-interface aspects to implementing it. Those can go in this issue.

**Comment by odysseywestra** [comment]
Closing since Pull Request #720 and mypaint/libmypaint#57 has addressed and added this Feature.

**Comment by Shnatsel** [comment]
Is rotating the symmetry axis implemented in this PR? 

I could really use symmetry mode in the picture I'm currently working on, but the character's head is tilted so I need to rotate the symmetry axis.

**Comment by odysseywestra** [comment]
As it now stands, that hasn't been added. @ShadowKyogre could you look into maybe adding this?

**Comment by ShadowKyogre** [comment]
@Shnatsel @odysseywestra - Hey there! Sorry for the long wait for the reply. Was trying to get the hang of my new job before picking up coding again.

Anyway, I've worked out the math for supporting it in my graphics-playground repo.

Code for the raw math is here: https://github.com/ShadowKyogre/graphics-playground/blob/87ac39ba8b58524ce27213168d1bed653b0c9aaa/examples/slanted-reflect/cairo.py

Does this image reflect what you need? The arrow looking things represent hypothetical brush dabs to make sure I'm adjusting the angle correctly with the axis tilt.

![image](https://user-images.githubusercontent.com/673620/46384157-11f5fe80-c669-11e8-829c-24413c4423c2.png)

If it is, I'll get to exporting this code over to MyPaint.

It also looks like this addition affects the vertical, horizontal, and vertical and horizontal symmetry modes the most since they don't calculate any angles.

**Comment by Shnatsel** [comment]
The image you've attached It's hard to judge it by the arrow because it's so short and the direction is rather hard to read. Krita's multibrush tool seems to do exactly what I want, so that can be used for reference.

Here's my use case: I have [this sketch](https://shketch-a-day.tumblr.com/image/174052261304) on which I want to redraw the lionesses' face using symmetry mode. To achieve that I would need to rotate the symmetry axis. Right now this is impossible in MyPaint, so I had to draw in symmetry mode in a separate image and then try to put it back into the main one. I want to draw [this image](https://shketch-a-day.tumblr.com/image/174116429610), but in-place instead of having to create a new file and losing context.

**Comment by android272** [comment]
I don't think so no. So currently we have the ability to mirror horizontally only. What we need is control over this mirror line. I don't know the technical term for them so that is what I am going to call them. I think we need a new issue for what @Shnatsel wants to do so maybe I will make a new one for what they want as I have a solution there.

Bellow is an image of what I am talking about for this thread. On the left, you have the end result. On the right the red lines represent mirror lines, The purple line represents a line that the user just painted, The blue lines are brush strokes that MyPaint paints for the user.

![fbd8d3_0](https://user-images.githubusercontent.com/5912527/46446731-f6175900-c74b-11e8-9ad1-2705a041959c.png)

What I would like to see is in the tool options panel is a slider, text box, dropdown or something that would give us the ability to create more mirror lines. For now, these lines can be evenly distributed around the center point.

Let me know if you have any more questions.

**Comment by android272** [comment]
@Shnatsel does [Issue 947](https://github.com/mypaint/mypaint/issues/947) sound to you?

**Comment by Shnatsel** [comment]
Issue 947 sounds like exactly the thing I need. I've copy-pasted my use case description there for reference. Thanks!

**Comment by jplloyd** [comment]
Since most of the requests here are already implemented and there is a separate issue for adjusting the symmetry line angle, I'll close this again.
