### ISSUE TITLE
Perhaps selecting a brush should change the "edit" mode "from flood" fill back to "freehand"/other

### ISSUE THREAD

**Issue by dannielsoares** [mypaint/mypaint#530]
Since the bucket fill isn't affected by the choice of brush, choosing a different one likely presumes not wanting to fill anything (possibly the whole layer) in the following action. 

Maybe it shouldn't necessarily default to freehand, but go back to the previously used non-bucket-fill tool/mode.

That may conflict with future plans of having the flood fill actually being affected by the choice of brush, though, I don't know. In this case I'd suggest as an alternative improvement to have the bucket cursor indicator somewhat ridiculously larger, perhaps optionally blinking, along with the floating text "THAT'S THE BUCKET FILL, YOU IDIOT".

**Comment by achadwick** [comment]
WONTFIX on walling our users idiots... :smiley:

I've no real plans here, but I do quite like the idea that clicking a brush in the selector could make the tool choice "right" for painting.

**Comment by snan** [comment]
"Maybe it shouldn't necessarily default to freehand, but go back to the previously used non-bucket-fill tool/mode."
Yes to this, rather than go to freehand always.
Love the bucket fill btw

**Comment by achadwick** [comment]
I vote for the making it the last drawing tool, defined as "any tool you use brushes with".

Sounds like a job for the mode stack, which is already fairly smart about mode intercompatibility (too smart?) It's messy code, but the stack is the reason you get back into linemode tools or frame-edit mode and not the default freehand tool when you move the view with the middle button.

Alg: when the user clicks a brush, begin popping (removing items from the top of) the mode stack till it's empty. For each mode about to be popped, stop if it is a drawing tool. If the stack becomes empty, push a new FreehandMode so its top mode is valid again. Then assign the new brush settings to the main painting brush as normal.

**Comment by ydahhrk** [comment]
I'd like to work on this in the near future.

Question: Should we also reset the painting mode?

My vote is HELL YES. I hate it when it stays in lock alpha or eraser when I'm trying to pick a pen; _a pen is not an eraser_.

**Comment by ydahhrk** [comment]
@achadwick: as stated in the commit message above, the mode stack replaces the drawing tool instead of stacking the fill bucket on top. This means the selection of brush always falls back to freehand mode, since the stack is empty.

Would you rather have tools always stack on top of each other (and if so, how do we prevent MyPaint from exhausting the RAM after a trillion years) or make an exception out of the flood fill tool?
Or something else?

**Comment by ydahhrk** [comment]
Proposed algorithm:

Whenever a tool is going to be added to the stack, first check if an instance of the tool already exists in the stack. If so, pop stuff until the tool is on top. Otherwise stack the tool without removing anything.

This should look as it currently does, but will always retain the last brush tool close at hand, and even other tools for future functionality. It will also never run out of memory because there's a limited number of tools in existence.

**Comment by achadwick** [comment]
I'm liking the look of the code in pull #789. I must playtest it, because I'm always assuming that clicking a brush gets me out of move-layer mode. _Aargh!_ :fearful:

I'll see what can be done about that construction order question. The approach in the PR seems a little backhanded to me.

**Comment by ydahhrk** [comment]
Ok.

> I'll see what can be done about that construction order question.

Oh, you mean the brush manager vs document construction order? Yeah, not sure what's the right approach there. In my mind it makes more sense to initialize the document first, but I dunno. Maybe I'm missing something. :p

I'm still around if you want me to tweak something.

(Ugh. I just realized I misspelled "Internal". What the hell.)
