### ISSUE TITLE
Merge Layer Down not working properly

### ISSUE THREAD

**Issue by Skydancer9** [mypaint/mypaint#536]
I noticed that "Merge Layer Down" button in Layers side panel is not working properly. Sometimes it works OK, then other times you click it and it begins to flicker, or it doesn't do anything. (Menu command and keyboard shortcut still work fine.)

- Mypaint version: 1.2.0-beta.3.18+git.c8c7358
- OS: Manjaro Linux (Arch-based)

**Comment by achadwick** [comment]
What is flickering, exactly? Just the button or something more?

Do you have an example of the failed results?

Merge Layer Down can't always be applied. See <https://github.com/mypaint/mypaint/wiki/v1.2-Layer-Merging-and-Normalization#merge-layer-down> for details. The button is greyed out when the command isn't available.

But maybe it's not that?

I really need a detailed set of instructions telling me how to reproduce this problem before I can start investigating. Can you provide?

**Comment by Skydancer9** [comment]
OK, I finally managed to reproduce it and record it. I had 2 layers with picture frame enabled. As I was playing around Mypaint (sorry, I can't tell you exactly what I did as it seems it doesn't always produce the same glitch), I got this glitch when I tried to merge the two layers. It took me multiple clicks to actually succeed in activating the button. Take a look at this desktop recording: http://shrani.si/f/1W/yy/2FNEBpK0/anim.gif

**Comment by achadwick** [comment]
The screencap .gif is really useful, thanks! Can you inline it here on github just in case the link goes dead please?

That's *really* weird. The first few clicks just aren't doing anything other than wobble the layout containers in the sidebar's widget tree. Something's demanding extra width and redraws!

It's especially weird that you're getting a down-arrow when you try to click the button on the end those first few times. Almost as if the inline toolbar needs extra space when you either hover it or for one of its animations, or begin to click it. It's a fast video, so it's difficult to understand the timing. Toolbars sometimes do that if they haven't enough space.

Looks almost like a GTK theme glitch. What theme and DE are you using?

Can you let me know what version of GTK Manjaro Linux uses, and what version/release of Manjaro Linux this is please?

Does it change anything if the options panel is at the bottom of the sidebar? Only asking because that one is the only widget with a dynamic height.

Finally, this *might* be alleviated by widening the sidebar. Does that change how reproducible this glitch is?

For my part, I'll take another look at that inline toolbar and try to ensure it never attempts to do the down-arrow thing.

**Comment by achadwick** [comment]
Yep. The inline toolbar factory function (`gui.widgets.inline_toolbar()`) needs changing. Faking more buttons onto the toolbar in `gui/layerswindow.py` reveals the arrow, and evidently this is only a thing with particular themes / desktop environments / resolutions / text scalings ☺

**Comment by achadwick** [comment]
I think that's a fix. Can you re-test please? Ideally with your current sidebar width, seeing as you can reproduce it right now.

**Comment by Skydancer9** [comment]
> Looks almost like a GTK theme glitch. What theme and DE are you using?

I use Vertex GTK3 theme on Cinnamon 2.8.6 desktop

> Can you let me know what version of GTK Manjaro Linux uses, and what version/release of Manjaro Linux this is please?

It uses GTK version 3.18.6. Manjaro version is 15.09 Bellatrix (64-bit)

> Does it change anything if the options panel is at the bottom of the sidebar?

I think that might solve the issue, yes.

> Can you [EDIT: update your MyPaint to the latest HEAD and] re-test please?

Like it is described in "README_LINUX.md" in "Updating to the latest source"?

**Comment by achadwick** [comment]
Yes, that's the usual procedure. Then follow *Testing (interactive)* if you don't want to install, or want to compare it with a previously installed version. Hope that makes sense! :smiley:

**Comment by Skydancer9** [comment]
Tested it. Works fine now. Thanks!
