### ISSUE TITLE
Cannot run w/o libmypaint-tests.so in /usr/lib?

### ISSUE THREAD

**Issue by ShadowKyogre** [mypaint/mypaint#539]
Possibly related issues: #535

# Steps to reproduce

1. Package the current git master in a manner similar to `package()` of https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mypaint-git , sans the copying of libmypaint-tests.so
2. Install the created package (whether it be on Debian, Arch, etc.)
3. Run mypaint.

# Expected result
Runs normally

# Actual result
~~~~
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix u'/usr'
INFO: mypaint: There is an old-style configuration area in u'/home/shadowkyogre/.mypaint/'
INFO: mypaint: Its contents can be migrated to $XDG_CONFIG_HOME and $XDG_DATA_HOME if you wish.
INFO: mypaint: See the XDG Base Directory Specification for info.
INFO: lib.i18n: POSIX: LANG='en_US'
INFO: lib.i18n: POSIX: LANGUAGE=None
Traceback (most recent call last):
  File "/usr/bin/mypaint", line 462, in <module>
    main.main(datapath, iconspath, old_confpath, version=version)
  File "/usr/share/mypaint/gui/main.py", line 95, in main
    from gui import application
  File "/usr/share/mypaint/gui/application.py", line 48, in <module>
    import lib.document
  File "/usr/share/mypaint/lib/document.py", line 37, in <module>
    import lib.helpers as helpers
  File "/usr/share/mypaint/lib/helpers.py", line 26, in <module>
    import mypaintlib
  File "/usr/share/mypaint/lib/mypaintlib.py", line 28, in <module>
    _mypaintlib = swig_import_helper()
  File "/usr/share/mypaint/lib/mypaintlib.py", line 20, in swig_import_helper
    import _mypaintlib
ImportError: libmypaint-tests.so: cannot open shared object file: No such file or directory

shell returned 1
~~~~

**Comment by ShadowKyogre** [comment]
Is there a way I can get a more in-depth trace of why it's attempting to use libmypaint-tests.so? Especially since when scons sets up an install in a sandbox, it doesn't copy that libmypaint-tests.so automatically.

**Comment by achadwick** [comment]
Patches welcome for getting MyPaint to build and run against sharedlib: see mypaint/libmypaint#28 and more importantly #535 here.

**Comment by achadwick** [comment]
@ShadowKyogre This is what I did with a normal static build:

You can look at the scons output to see why libmypaint-tests.so is needed by _mypaintlib. Look for the line that gives the command used to build _mypaintlib.so. On my Debian box it looks something like:

`g++ -o _mypaintlib.so -O3 -Wl,-z,origin -fopenmp -pthread -fopenmp -shared -Wl,-rpath=\$ORIGIN lib/mypaintlib_wrap.os lib/fill.os lib/eventhack.os lib/gdkpixbuf2numpy.os lib/pixops.os lib/fastpng.os -Lbrushlib -lmypaint-tests -lmypaint -lm -ljson-c -lpng12 -llcms2 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lpython2.7`

So I tried issuing that command without the `-lmypaint-tests`. And it builds! But it doesn't run when invoked from the command line as `./mypaint -c /tmp/whatever.cfg.$$`. When Python tries to resolve all of libmypaint's symbols at runtime, it backtraces differently:

```
Traceback (most recent call last):
[...]
  File "/home/andrewc/Development/MyPaintProject/mypaint/lib/mypaintlib.py", line 20, in swig_import_helper
    import _mypaintlib
ImportError: /home/andrewc/Development/MyPaintProject/mypaint/_mypaintlib.so: undefined symbol: mypaint_test_surface_run
```

Well, OK. Where is that function invoked from?

```
$ rgrep mypaint_test_surface_run 
lib/tiledsurface.hpp:    int retval = mypaint_test_surface_run(0, NULL,
brushlib/tests/mypaint-test-surface.h:mypaint_test_surface_run(int argc, char **argv,
brushlib/tests/mypaint-test-surface.c:mypaint_test_surface_run(int argc, char **argv,
brushlib/tests/test-fixed-tiled-surface.c:    return mypaint_test_surface_run(argc, argv, fixed_surface_factory, "MyPaintFixedSurface", NULL);
brushlib/tests/gegl/test-gegl-surface.c:    int retval = mypaint_test_surface_run(argc, argv, gegl_surface_factory, "MyPaintGeglSurface", NULL);
```

Okay, I guess we can ignore the brushlib invocations, but the `lib/` one is surprising. Chasing it through, it seems it's needed by `run_brushlib_tests()`, tacked onto the end of `lib/tiledsurface.hpp`, which in turn is invoked only one of MyPaint's test runners:

```
$ rgrep run_brushlib_tests 
lib/tiledsurface.hpp:run_brushlib_tests(void)
tests/test_brushlib.py:sys.exit(mypaintlib.run_brushlib_tests())
```

So that's why, and it means a patch like

```patch
diff --git a/lib/tiledsurface.hpp b/lib/tiledsurface.hpp
index de5bf5b..a07cf64 100644
--- a/lib/tiledsurface.hpp
+++ b/lib/tiledsurface.hpp
@@ -8,7 +8,6 @@
  */
 
 #include <mypaint-tiled-surface.h>
-#include <mypaint-test-surface.h>
 
 static const int TILE_SIZE = MYPAINT_TILE_SIZE;
 static const int MAX_MIPMAP_LEVEL = MYPAINT_MAX_MIPMAP_LEVEL;
@@ -149,14 +148,3 @@ mypaint_python_surface_factory(gpointer user_data)
 }
 
 } // extern "C"
-
-int
-run_brushlib_tests(void)
-{
-    int retval = mypaint_test_surface_run(0, NULL,
-                                          mypaint_python_surface_factory,
-                                          "MyPaintPythonTiledSurface",
-                                          NULL);
-
-    return retval;
-}
```

would indeed remove the need for that `-lmypaint-tests` at MyPaint runtime.

----------------------------------------------------------

But of course then the tests won't run, and the Travis build will break:

```
$ tests/test_brushlib.pyTraceback (most recent call last):
  File "tests/test_brushlib.py", line 15, in <module>
    sys.exit(mypaintlib.run_brushlib_tests())
AttributeError: 'module' object has no attribute 'run_brushlib_tests'
```

**Comment by achadwick** [comment]
For obvious reasons, I'm not prepared to accept any PR against MyPaint which removes `run_brushlib_tests()` without also ensuring that these tests get run somehow by MyPaint's Travis. Perhaps that means adding an `enable_brushlib_tests` flag to the main MyPaint build and invoking `tests/run_all_basic_tests.sh` separately. Or maybe `use_sharedlib` is already doing double duty?
