### ISSUE TITLE
Website doesn't open from program

### ISSUE THREAD

**Issue by zb13y** [mypaint/mypaint#551]
Help - About MyPaint - Website

Could not show link
Failed to execute helper program (invalid argument)

I can open online help.

Beta 4 x64, Windows 10 x64.

**Comment by tumagonx** [comment]
This work my build using gtk 3.14.15 (opening IE to http://mypaint.org/), maybe this still related to #531 ? in this case protocol association.

@zb13y does it works with beta1?

**Comment by zb13y** [comment]
Yes, its work in beta 1.

**Comment by achadwick** [comment]
Is the the HCY wheel's help button is broken too?

**Comment by zb13y** [comment]
Yes, broken too. No reaction, in debug mode i have this message:

```
(python2.exe:6008): Gtk-WARNING **: Unable to show 'https://github.com/mypaint/mypaint/wiki/v1.2-HCY-Wheel-and-Gamut-Mask-Editor': ═х єфрыюё№ т√яюыэшЄ№ тёяюьюурЄхы№эє■ яЁюуЁрььє (Invalid argument)
```

**Comment by tumagonx** [comment]
ugh, why it looks like that? Now I'm unsure if this share the same culprit as #531, but still is upstream issue.

**Comment by tumagonx** [comment]
sorry, took me a while to realize if that was cyrillic message

**Comment by tumagonx** [comment]
Hmm I can't reproduce this with gtk3-demo 3.18.6 > Links > click on the google hyperlink 
It works fine! But again is it the same thing? (text markup feature that trigger url association)

used glib: 2.46.2

**Comment by achadwick** [comment]
The ones that are working from the MyPaint UI use the Python `webbrowser` module. Can't really use that type of workaround this time, but at least it isn't segfaulting ☺

**Comment by danpla** [comment]
Maybe because `gspawn-win32-helper-console.exe` (or `gspawn-win32-helper.exe`, or both of them) is missing in distributions.

**Comment by achadwick** [comment]
@danpla thanks for the hint. We can bundle those too.

**Comment by tumagonx** [comment]
@danpla Did you reproduce it in 1.2.0 release? It works fine here.

Windows mechanism itself don't need custom launcher (like gspawn) to
just launch associated apps. Gspawn used when glib need fine-grained
control over its child process which is not the case here. This bug is
directly related to glib regression in registry association.

Personally I take care what needed and whatnot, I'm quite picky at
this. Sure for practical reason (since they are small) it can be
bundled, no problem.

On 4/16/16, Andrew Chadwick <notifications@github.com> wrote:
> @danpla thanks for the hint. We can bundle those too.
>
> ---
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/mypaint/mypaint/issues/551#issuecomment-210611754


-- 
!tuma

**Comment by danpla** [comment]
@tumagonx Yes, links work in 1.2.0, but not in the recent 1.2.1-beta.0 testing builds.

For the 64 bit test build, copying gspawn from my MSYS2 installation solved the problem. The "console" version of gspawn needed for `python2.exe`, the "normal" one - for `python2w.exe`.

However, it is not possible to test the 32-bit build, because the current 32-bit glib from MSYS2 is somewhat broken: after clicking on a link, it always crashes an app (MyPaint or `mingw32\bin\gtk-demo.exe`) with with this assertion:
```
Warning: unquote_string_inplace: assertion 'err == NULL || *err == NULL' failed
```

I don't know about GTK internals, but I can assume that gspawn dependency can be controlled by compile-time flags used to build glib/gtk for Windows.

The reason why I'm remember gspawn is that I had some experience of packing GTK+ apps for Windows, and I had exactly the same problem, which was solved by including it. However, I used Python 3 with [PyGObject for Windows](https://sourceforge.net/projects/pygobjectwin32/) and cx_Freeze.

**Comment by tumagonx** [comment]
That's why I asked your confirmation with 1.2.0 : ) which don't have
gspawner for both 32/64bit
 AFAIK unless your app use dbus there is no need for it.

After I checked it again glib starting with 2.46 changed from using
ShellExecuteExW (win32 api) to gspawn (see gwin32appinfo,c). So you're
right things has changed. :D

On 4/16/16, Daniel Plachotich <notifications@github.com> wrote:
> @tumagonx Yes, links work in 1.2.0, but not in the recent 1.2.1-beta.0
> testing builds.
>
> For the 64 bit test build, copying gspawn from my MSYS2 installation solved
> the problem. The "console" version of gspawn needed for `python2.exe`, the
> "normal" one - for `python2w.exe`.
>
> However, it is not possible to test the 32-bit build, because the current
> 32-bit glib from MSYS2 is somewhat broken: after clicking on a link, it
> always crashes an app (MyPaint or `mingw32\bin\gtk-demo.exe`) with with this
> assertion:
> ```
> Warning: unquote_string_inplace: assertion 'err == NULL || *err == NULL'
> failed
> ```
>
> I don't know about GTK internals, but I can assume that gspawn dependency
> can be controlled by compile-time flags used to build glib/gtk for Windows.
>
> The reason why I'm remember gspawn is that I had some experience of packing
> GTK+ apps for Windows, and I had exactly the same problem, which was solved
> by including it. However, I used Python 3 with [PyGObject for
> Windows](https://sourceforge.net/projects/pygobjectwin32/) and cx_Freeze.
>
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/mypaint/mypaint/issues/551#issuecomment-210780800


-- 
!tuma

**Comment by tumagonx** [comment]
gspawn is mandatory part glib, it just that i'm picky at removing
unused stuff (which is true for glib 2.44). It happened that both me
and achadwick don't include gspawn and so I thought it was another
upstream regression. duh

OT btw i'm maintainer of https://sourceforge.net/projects/pygobjectwin32

On 4/16/16, Bakhtiar Hasmanan <mr.tiar@gmail.com> wrote:
> That's why I asked your confirmation with 1.2.0 : ) which don't have
> gspawner for both 32/64bit
>  AFAIK unless your app use dbus there is no need for it.
>
> After I checked it again glib starting with 2.46 changed from using
> ShellExecuteExW (win32 api) to gspawn (see gwin32appinfo,c). So you're
> right things has changed. :D
>
> On 4/16/16, Daniel Plachotich <notifications@github.com> wrote:
>> @tumagonx Yes, links work in 1.2.0, but not in the recent 1.2.1-beta.0
>> testing builds.
>>
>> For the 64 bit test build, copying gspawn from my MSYS2 installation
>> solved
>> the problem. The "console" version of gspawn needed for `python2.exe`,
>> the
>> "normal" one - for `python2w.exe`.
>>
>> However, it is not possible to test the 32-bit build, because the current
>> 32-bit glib from MSYS2 is somewhat broken: after clicking on a link, it
>> always crashes an app (MyPaint or `mingw32\bin\gtk-demo.exe`) with with
>> this
>> assertion:
>> ```
>> Warning: unquote_string_inplace: assertion 'err == NULL || *err == NULL'
>> failed
>> ```
>>
>> I don't know about GTK internals, but I can assume that gspawn dependency
>> can be controlled by compile-time flags used to build glib/gtk for
>> Windows.
>>
>> The reason why I'm remember gspawn is that I had some experience of
>> packing
>> GTK+ apps for Windows, and I had exactly the same problem, which was
>> solved
>> by including it. However, I used Python 3 with [PyGObject for
>> Windows](https://sourceforge.net/projects/pygobjectwin32/) and cx_Freeze.
>>
>> ---
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub:
>> https://github.com/mypaint/mypaint/issues/551#issuecomment-210780800
>
>
> --
> !tuma
>


-- 
!tuma

**Comment by achadwick** [comment]
[MyPaint v1.2.1](https://github.com/mypaint/mypaint/releases/tag/v1.2.1) has been released. Please can you try it out and see if this bug is still happening?

The current stable MyPaint build has a deletion exclusion `mingw*/bin/gspawn-*-helper.exe` according to my styrene config file :smile:

**Comment by zb13y** [comment]
1.2.1+gitexport.bcf5a28d (Python 2.7.13, GTK 3.22.7, GdkPixbuf 2.36.4, Cairo 1.15.4, GLib 2.50.1)

Still can't open website.

**Comment by zb13y** [comment]
Oops! Sorry, it works. My browser (self-protection, like HIPS) was blocking mypaint.

**Comment by achadwick** [comment]
Confirmed that it's working with mine too. Thanks!
