### ISSUE TITLE
adjust view rotate in beta 4 x64

### ISSUE THREAD

**Issue by Jen01** [mypaint/mypaint#553]
beta 4 x64 version the counterclockwise and clockwise actions work in reverse.  a minor fix.  
clockwise rotates counterclockwise,  and clockwise rotates counterclockwise.

**Comment by achadwick** [comment]
@Jen01 Could you clarify which buttons or commands do this please?

Also, are you using a translation (any language that is not US English)?

**Comment by cortexer** [comment]
I think the two toolbar icons (circular arrows) and the two menu entries for rotate left/right.
This is also present in the english translation.

Example to reproduce:
The toolbar icon with the circular arrow pointing left, is indeed rotating the canvas to the right.
In my opinion this might indeed be a bit counter intuitive.

The question is whether these buttons/menu entries are meant to show the canvas rotation (then they are wrong direction) or to show the "viewer's head rotation" (then they are correct as they are).

**Comment by achadwick** [comment]
@Jen01 , @cortexer 
I think you're right. **The only time it makes a kind of sense** is when the Preview dockpanel is open AND when you're zoomed in so that the preview shows a viewfinder rectangle. Then the design of the arrows in these toolbar icons:

![image](https://cloud.githubusercontent.com/assets/61299/12217677/aab8cbf6-b6ff-11e5-9b70-0d14a2960c18.png)

makes it look like you might be rotating the **viewfinder rectangle** in the Preview panel:

![image](https://cloud.githubusercontent.com/assets/61299/12217695/40fb4184-b700-11e5-8740-236bca1da74e.png)

But the Preview panel is not open all the time, and the viewfinder rectangle is only shown in it when you're zoomed in.

Compare with other toolbar buttons:

* ![image](https://cloud.githubusercontent.com/assets/61299/12217708/ac2bfdf4-b700-11e5-9012-eafa7cbaec32.png)

  The left one (zoom in, marked `+`) makes the **canvas** bigger within the viewing rectangle and the left one does the opposite. It does not make the viewing rectangle bigger.

* ![image](https://cloud.githubusercontent.com/assets/61299/12217730/337dbc20-b701-11e5-9d3e-aea06065bb66.png)

  The left one (marked `1`) makes the **canvas** 1:1 within the viewing rectangle. The right one makes the **canvas** fit the viewing rectangle, and I think that's the best way of presenting it.

So I agree with what you're saying. I think the step-rotate buttons on the toolbar should probably be swapped too, so the easiest way is probably just to switch the icons. :smile:

**Comment by americogobbo** [comment]
The rectangle on viewfinder is still working in the inverse rotation applied by user.

**Comment by achadwick** [comment]
@americogobbo Can you explain more, ideally in a separate issue?

**Comment by achadwick** [comment]
@americogobbo
This is behaviour which was changed in 5cb8aa081a0697f06325e247f02868adcbb707bf, which is the fix for this issue. Are you suggesting some sort of regression? Do you have a commit or a bug reference?

Thanks for the detailed write-up and video (#557), but I don't want to revert 5cb8aa081a0697f06325e247f02868adcbb707bf right now. It's more important that the toolbar buttons are consistent than it is that some of the toolbar buttons are consistent with a fairly obscure dockpanel. See my thoughts above.

It's unfortunate that the icons make it look as though you're turning the rectangle you see in the viewport dockpanel. So maybe all the toolbar icons which change the view could be modified to make the distinction clearer? Those toolbar buttons are unrelated to the Preview dockpanel, except as it merely reflects what they do.

**Comment by Jen01** [comment]
sorry, i posted that online, and forgot completely about the ubuntu studio group. i "m using mypaint w64 Beta 4 on a lenova tablet. 

1. the rotate icon on the toolbar works properly. 
2. From the view menu, "rotate" itself moves whichever direction I move it with my pen. 
3. Fom the view menu, "adjus" - "rotate" appears to work in the opposite direction. clockwise rotates counter clockwise, and counter-clockwise turns clockwise. that is when viewing directly straight at the screen. 

i had beta 3 on my laptop for a bit, and the view menu "rotate" command (above "adjust") didn't work at all so I started using the command as listed in the view-adjust- rotate. 

I hear what you are saying on the viewfinder - might try that (zoom in) and rotate it....see if that works. 


toolbar and view-rotate are most conventient because the user can choose the amount of rotation. 

another thing I noticed was that all rotate options, rotate all layers at the same time (even with layer locked). would be handy to be able to rotate a layer similar to how you can move a layer. i read about using control rotate, but that didn't work for me. 

thanks for looking checking it out. 


, 

----- Original Message -----

**Comment by achadwick** [comment]
@Jen01 
Do I need to re-open this issue?

Replies to each point below.

----------------------------

> sorry, i posted that online, and forgot completely about the ubuntu studio group.

I don't know what the "ubuntu studio group" is. Is this something I should know about?

> i "m using mypaint w64 Beta 4 on a lenova tablet.
> 
> 1. the rotate icon on the toolbar works properly.
> 2. From the view menu, "rotate" itself moves whichever direction I move it with my pen.

I think these have been working correctly for ages, and are unrelated to the adjust commands.

> 3 . Fom the view menu, "adjus" - "rotate" appears to work in the opposite direction. clockwise rotates counter clockwise, and counter-clockwise turns clockwise. that is when viewing directly straight at the screen.

These were fixed in 5cb8aa081a0697f06325e247f02868adcbb707bf.

> i had beta 3 on my laptop for a bit, and the view menu "rotate" command (above "adjust") didn't work at all so I started using the command as listed in the view-adjust- rotate.

Whatever was going on here, was it fixed in 1.2.0-beta.4? Please raise a new issue about it if it isn't.

> I hear what you are saying on the viewfinder - might try that (zoom in) and rotate it....see if that works.

The behaviour here will have *reversed* since 5cb8aa081a0697f06325e247f02868adcbb707bf. You will most probably see 1.2.0-beta.4 as "correct" and 1.2.0 as "wrong" if you are expecting the adjust buttons to adjust the *viewfinder*. Sorry, but this was a last minute change.

> toolbar and view-rotate are most conventient because the user can choose the amount of rotation.

I thought you meant the optional one-shot rotate buttons on the toolbar
<https://github.com/mypaint/mypaint/wiki/v1.2-Main-Toolbar#view-alternativesecondary>

These were changed in 5cb8aa081a0697f06325e247f02868adcbb707bf, probably to do what you want. You will see this layout in v1.2.0. Is this what you wanted?

> another thing I noticed was that all rotate options, rotate all layers at the same time (even with layer locked). would be handy to be able to rotate a layer similar to how you can move a layer. i read about using control rotate, but that didn't work for me.

The canvas (view) rotation commands do not rotate layers.: <https://github.com/mypaint/mypaint/wiki/FAQ-Is-rotation-real>.

You have two options if you want to rotate a layer relative to all the other layers.

1. Use an external program like GIMP to do the job. An external app can be invoked from the Layers dockpanel.
2. Wait for #31 to be fixed ☺

**Comment by Jen01** [comment]
i'm not sure that the explanation around why the clockwise goes counterclockwise and vice versa in view-adjust-rotate makes sense to me as an artist using this program - I thought it was code written reversed. However, the other two methods also work so there are alternatives. 
If everyone is okay with it, I'll use the other options. In the instruction manual, it might need to be noted why rotate under view-adjust-rotate counterclockwise, etc. rotates clockwise (and vice versa) so people don't think it's code reversed. 
If there were no other rotation options, I'd say reopen, but there are currently 2 other options, so I'm fine with it not being reopened. 

----- Original Message -----
