### ISSUE TITLE
How to create shortcuts in 1.2.0?

### ISSUE THREAD

**Issue by edelinet** [mypaint/mypaint#607]
In version 1.1, I loved the way I could create shortcuts by hovering the mouse over items in a menu and assigning a keyboard shortcut to them.
Is there a way to do something similar in 1.2?

I'm a Newbie (will break into cold sweat if answer gets too technical) & Windows 10 user
Just downloaded MyPaint v1.2.0 (2016-01-15)

**Comment by achadwick** [comment]
Hi there - thanks for the feedback!

This issue tracker is not for direct user support really. We try to limit it so that each thread is a single fixable issue which can be closed by changing the MyPaint code.

Answer to your question: Edit → Edit Preferences → Keys.

You may find you get more useful feedback in future from the [MyPaint Community Forums][http://community.mypaint.org/], from Twitter ([@MyPaintApp][https://twitter.com/MyPaintApp], `#mypaint`), on IRC ([#mypaint on freenode](irc://freenode/mypaint)), or on the [MyPaint mailing list][https://mail.gna.org/listinfo/mypaint-discuss].
