### ISSUE TITLE
How to crop document to frame?

### ISSUE THREAD

**Issue by edelinet** [mypaint/mypaint#608]
Is there a way to crop the document to the frame in MyPaint 1.2? Thanks!

**Comment by cyborgcassowary** [comment]
@edelinet 

Use the edit frame button. 

![editframe](https://cloud.githubusercontent.com/assets/1065658/13197156/38c51020-d7b3-11e5-8dfb-00aeb3b956a0.jpg)

**Comment by achadwick** [comment]
Hi there - thanks for the feedback, and for the direct user supoort!

This issue tracker is not for direct user support. We try to limit it so that each thread is a single fixable issue which can be closed by changing the MyPaint code.

You'll get more useful feedback in future from the [MyPaint Community Forums](http://community.mypaint.org/), from Twitter ([@MyPaintApp](https://twitter.com/MyPaintApp), #mypaint), on IRC ([#mypaint on freenode](irc://freenode/mypaint)), or on the [MyPaint mailing list](https://mail.gna.org/listinfo/mypaint-discuss).
