### ISSUE TITLE
MyPaint can't run

### ISSUE THREAD

**Issue by chombor** [mypaint/mypaint#612]
Win10, last version MyPaint w64, double click.... and nothing

Compatibility mode and admin flag — doesn't help

_after 10 min_

32bit version start fine, but presure sensetive not working and crashing a lot

**Comment by achadwick** [comment]
Hi there - thanks for the report!

There's not quite enough information in your original report to move this issue forward, however. Please read the [bug reporting guidelines](https://github.com/mypaint/mypaint/wiki/Reporting-Bugs). We need more information about your system, and more information about your MyPaint installation if this report is going to be useful to us.

This issue tracker is not for direct user support really. We try to limit it so that each thread is a single fixable issue which can be closed by changing the MyPaint code. I won't close this report straight away though because sometimes we can help, often the feedback is useful anyway, and sometimes support requests can turn into stuff programmers can actually do something about!

We may not be able to help you straight away here, but don't be discouraged if we can't. You may find you get more useful feedback from the [MyPaint Community Forums](http://community.mypaint.org/), from Twitter ([@MyPaintApp](https://twitter.com/MyPaintApp), #mypaint), on IRC ([#mypaint on freenode](irc://freenode/mypaint)), or on the [MyPaint mailing list](https://mail.gna.org/listinfo/mypaint-discuss).

**Comment by achadwick** [comment]
**TRIAGE NOTE:** looks like a user support request.
This is the wrong forum for direct user support, reporter has been redirected to better places to ask.
This issue should be closed after one week if no further information is forthcoming that would allow it to be progressed to `bug` or `enhancement` status.

**Comment by achadwick** [comment]
No feedback from the reporting user, sadly, so we can't fix this.
