### ISSUE TITLE
Remove Some Keybaord Shortcuts

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/mypaint#626]
I notice that a few of the keyboard shortcuts do not need to be listed. Basically they are duplicates, but only reveal the panel instead of toggling it to be revealed and hidden. I think they should be removed from being able to be assigned a shortcut unless we have a reason to keep them.

I have them marked down in the spreadsheet I mentioned in #622 in yellow. Are there any other keyboard mapping shortcuts we should remove from this list as well?

**Comment by achadwick** [comment]
Ah, yes. these are there because assigning a toggle command to the commonly used L key would cause the UI to be rearranged (that's a real shortcoming of the workspace shell, sadly).

The white equivalents of these should be removed from the user-visible list, and new "Show"/Reveal commands that use reveal_dockpanel_cb() should be introduced in their place.

**Comment by odysseywestra** [comment]
Closing issue to be continued on our [Community Forums](http://community.mypaint.org/t/remove-some-keyboard-shortcuts/293) to help our Issue tracker focus on bugs.
