### ISSUE TITLE
Color picker behavior in 1.2

### ISSUE THREAD

**Issue by darkstalker** [mypaint/mypaint#632]
In 1.1, you could use the color picker to pick any visible color on the screen by selecting the MyPaint window and pressing R with the cursor outside it. That was useful for color picking references and other stuff. But noticed that on 1.2 you can't do that anymore, when trying that it justs selects the canvas background color.
Also since 1.2 the numeric color inputs are gone so it looks like there is no way to manually input colors into the program.

Using MyPaint 1.2.0 on Gentoo Linux x86_64

**Comment by achadwick** [comment]
@darkstalker 
Hi there - thanks for the feedback!

This issue tracker is not for direct user support really. We try to limit it so that each thread is a single fixable issue which can be closed by changing the MyPaint code. I won't close this report straight away though because sometimes we can help. Often the feedback is useful too, and sometimes support requests can turn into stuff programmers can actually do something about!

We may not be able to help you straight away here, but don't be discouraged if we can't. Issue trackers don't get that many views, sadly. You may find you get more useful feedback from the [MyPaint Community Forums](http://community.mypaint.org/), from Twitter ([@MyPaintApp](https://twitter.com/MyPaintApp), #mypaint), on IRC ([#mypaint on freenode](irc://freenode/mypaint)), or on the [MyPaint mailing list](https://mail.gna.org/listinfo/mypaint-discuss).

**Comment by achadwick** [comment]
@darkstalker 
The colour picker behaviour was removed in 1.2.0 because the old behaviour was too buggy to support. See 83a9e7b27b1623c326168b66d4ad5e89a52e9fe0 and #444. It will not be reintroduced. Please use a program like gcolor2, gcolor3, or gpick.

**Comment by achadwick** [comment]
@darkstalker 
Click on this icon in the footer if you want to manually enter hex codes into the program.

![footer icon](https://cloud.githubusercontent.com/assets/61299/14176036/dce45a3c-f746-11e5-95ff-6b01145f5ab8.png)

**Comment by achadwick** [comment]
I think all aspects of your support request have been answered, so I'm closing this issue. Please ask on the MyPaint Community Forums next time.

**Comment by darkstalker** [comment]
Thanks for the reply, didn't know there was a community forum. Also I thought this was a bug so I posted it here.
