### ISSUE TITLE
Collaborating with Opentoonz - libbrush, ORA, etc?

### ISSUE THREAD

**Issue by blurymind** [mypaint/mypaint#635]
Opentoonz has just been released as open source. It is a big big animation application that is almost on the same level as toonboom harmony.

After trying it out, I was immensely impressed by the features.

Now this is where I would like to direct a few questions to the mypaint developers.
- on ORA - Opentoonz community is looking for an open file format for storing 2d animations - an alternative to the proprietary one that opentoonz uses. Would it be possible for ora to become that file format? Do you think it could also support animations? This is a question that would be appropriate for the Krita developers as well. They recently implemented bitmap animation in krita as well. That said - ora will need to also store vector layers that open toonz uses. Do you think it's a good idea to use ora for this task. What modifications of the file format need to be done?
https://github.com/opentoonz/opentoonz/issues/114

- on libbrush - Given that Opentoonz uses a BSD license, is it possible to integrate libbrush into it's raster brush tool? That tool currently lags behind mypaint because it cant do anything but basic thick or soft lines. So it's not very good for sketching as compared to tvpaint. But if mypaint's brush engine was made part of it - that would be a different story altogether :)

- Do you think that mypaint and opentoonz development can collaborate? For one to take from the other and give back? Or would the licensing be an issue in this case?

**Comment by 0ion9** [comment]
* The suitability of a single-archive format for animation is not clear to me. I tend to think that multi-file formats like GIMP-GAP uses, scale better and minimize save/load times. However, a model that uses .oras in the same way that GIMP-GAP uses .xcfs, is perfectly possible. The question that I'm unsure about is whether it would fit the design of .ora to extend it in that way.
* We already support vector layers to some extent. Is there some aspect of OpenToonz vectors that MyPaint would need to specifically support? Otherwise, the current level of support would work IMO.
* Licensing [appears to be BSD-like](https://github.com/opentoonz/opentoonz/blob/master/LICENSE.txt) for OpenToonz, while MyPaint is GPL2 and libmypaint is ISC (which is a BSD-like). Ergo: 
  * MyPaint can take code from OpenToonz
  * OpenToonz cannot take code from MyPaint (GPL2 licensing conditions not satisfied)
  * OpenToonz can take code from libmypaint.
    * Note that this is **different** from linking to libmypaint, which is also permitted and is probably what OpenToonz would want to actually do. "Integrating" libmypaint would only be needed if changes to libmypaint were needed and those changes were not acceptable to libmypaint maintainers.

**Comment by odysseywestra** [comment]
@blurrymind I'm sorry to make you do this again, but when I ment the the MyPaint Community, I was referring to the Community Forums in the developers Area category. Just like in openToonz issue tracker, we're trying to keep the issue tracker focused on bugs. Plus you'll get more eyes and feedback there. I'm sorry if I wasn't clear about that. 😓

**Comment by blurymind** [comment]
@odysseywestra  done, but waiting moderator approval ;)

**Comment by achadwick** [comment]
Closing, since this isn't related to mypaint development.

**Comment by blurymind** [comment]
http://community.mypaint.org/t/collaborating-with-opentoonz-libbrush-ora-etc/280
