### ISSUE TITLE
Huion 1060 pro drawing pad under Windows 10: glitch lines, as if painting in 2 places at once

### ISSUE THREAD

**Issue by somecraft** [mypaint/mypaint#677]
when I plug in my drawing pad I had some issues with the  Mypaint, when I put the pen in the pad is like I'm touching in two places at once, and this problem just happens with this programme

**Comment by achadwick** [comment]
Hi there - thanks for the report!

There's not quite enough information in your original report to move this issue forward, sadly. Please read the [bug reporting guidelines](https://github.com/mypaint/mypaint/wiki/Reporting-Bugs). We need more information about your system, and more information about your MyPaint installation if this report is going to be useful to us.

**Comment by achadwick** [comment]
Screenshots in particular would be helpful for this one.

**Comment by somecraft** [comment]
![bug2](https://cloud.githubusercontent.com/assets/19241244/15093249/b6a10fa0-1479-11e6-94b5-91b55a01620e.png)
![bug](https://cloud.githubusercontent.com/assets/19241244/15093250/bb88394e-1479-11e6-8960-66e4bca0aa31.png)
I installed the MyPaint today in the MyPaint.org site, and when I plug in my drawing pad Huion and tried to draw I had some issue I can't draw because when I put the pen in the pad it draw a line up like if I was touching the up buttons

**Comment by achadwick** [comment]
What kind of Huion? Exact model number please.
Make sure you are using the latest drivers from Huion. What version?
What version of MyPaint? Exact number please. Please look in Help → About MyPaint.
This is Windows 10?

This is _very likely_ to be an upstream issue, which we will be unable to do nothing about. Sorry.

Please can you exclude possibilities like touching the tablet surface with your fingers while drawing, if your graphics tablet is a Pane and Touch (giant touchpad) model.

Are all these lines going to the same point on the canvas, or the same point on the screen?

What does "touching the up buttons" mean?

**Comment by achadwick** [comment]
This report needs a better title. Please summarise your problem as well.

**Comment by somecraft** [comment]
is the huion 1060 pro, the windows 10 and 1.2.0 MyPaint.

**Comment by achadwick** [comment]
@somecraft 
Thanks for the partial info.

This is important: make sure you are using the latest drivers from Huion. What version of the drivers are you using?

**Comment by achadwick** [comment]
@somecraft
Sorry, I can't help at all here. I'm simply not getting enough information to address this as a bug.

This issue tracker is not for direct user support. We try to limit it so that each thread is a single fixable issue which can be closed by changing the MyPaint code. I won't close this report straight away though because sometimes we can help. Often the feedback is useful too, and sometimes support requests can turn into stuff programmers can actually do something about!

We may not be able to help you straight away here, but don't be discouraged if we can't. Issue trackers don't get that many views, sadly. You may find you get more useful feedback from the [MyPaint Community Forums](http://community.mypaint.org/).

**Comment by achadwick** [comment]
**TRIAGE NOTE:** This is the wrong forum for direct user support, reporter has been redirected to better places to ask araound.

But. There is a heavy upstream feel to this report. If this has any sort of bug-nature at all, it is going to be a problem with either the proprietary drivers or with GDK. After all, MyPaint just does what GDK tells it to do, and that's only an interpretation of the user's painting strokes via a series of events.

Our goal here should be to confirm where the problem lies, and make a good upstream bug report. @somecraft, are you up for that?

**Comment by achadwick** [comment]
### Please report upstream (GTK+/GDK)

This is probably a bug in the GTK+/GDK libraries. We don't maintain these components ourselves. This bug should be reported in the GNOME bugtracker, against the “gtk+” component so that their developers know about it.

* [Search GNOME Bugzilla for this bug first](https://bugzilla.gnome.org/buglist.cgi?bug_status=__all__&content=KEYWORDS+HERE&no_redirect=1&order=Importance&product=gtk%2B&query_format=specific). It may already have been reported!
* Use this form if you can't find it: [Enter Bug: gtk+](https://bugzilla.gnome.org/enter_bug.cgi?product=gtk%2B). You may need to create an account.
* Please post links to relevant upstream bugs here :smile:

The GNOME Bugzilla is quite technical, but don't be discouraged. We can help you get it right here, and we have a few guides for reporting good bugs in our own wiki. See [our wiki's Contributing section](https://github.com/mypaint/mypaint/wiki/Contributing) for details.

**Comment by achadwick** [comment]
@somecraft
Is this still happening with the latest MyPaint beta?

**Comment by achadwick** [comment]
@somecraft 
Please respond. [MyPaint v1.2.1](https://github.com/mypaint/mypaint/releases/tag/v1.2.1) is now out, and it may fix this issue. Can you test?

**Comment by AesaraB** [comment]
Closed as stale
