### ISSUE TITLE
MyPaint HiDpi for Windows

### ISSUE THREAD

**Issue by Sineaggi** [mypaint/mypaint#686]
Hello, how does one enable hidpi scaling in mypaint?
I have GDK_SCALE set as a global env variable, but I can't get the gui to scale.

**Comment by achadwick** [comment]
Hi there - thanks for the feedback!

This issue tracker is not for direct user support really. We try to limit it so that each thread is a single fixable issue which can be closed by changing the MyPaint code. I won't close this report straight away though because sometimes we can help. Often the feedback is useful too, and sometimes support requests can turn into stuff programmers can actually do something about!

We may not be able to help you straight away here, but don't be discouraged if we can't. Issue trackers don't get that many views, sadly. You may find you get more useful feedback from the [MyPaint Community Forums](http://community.mypaint.org/), from Twitter ([@MyPaintApp](https://twitter.com/MyPaintApp), #mypaint), on IRC ([#mypaint on freenode](irc://freenode/mypaint)), or on the [MyPaint mailing list](https://mail.gna.org/listinfo/mypaint-discuss).

**Comment by achadwick** [comment]
**TRIAGE NOTE:** looks like a user support request. This is the wrong forum for direct user support, reporter has been redirected to better places to ask. This issue should be closed after one week if no further information is forthcoming that would allow it to be progressed to `bug` or `enhancement` status.

**Comment by odysseywestra** [comment]
Might be an upstream problem with HiDPI support on windows since it is working as intended on Linux.

**Comment by palob** [comment]
As far as I know GTK+ just received backported Windows HiDpi support some 3.22 point release (3.22.4 or .5). So maybe building the Windows binaries with the latest 3.22 release could fix the issue.

**Comment by achadwick** [comment]
[MyPaint v1.2.1](https://github.com/mypaint/mypaint/releases/tag/v1.2.1) has now been released. Please can you confirm whether or not this bug is still happening in that version? We're bundling GTK 3.22.7 now.

**Comment by achadwick** [comment]
I've been using `GDK_SCALE` with... increasing... degrees of correctness while testing for the upstream bugs below in MSYS2.

* <https://bugzilla.gnome.org/show_bug.cgi?id=778835>, probably the root cause of
  * https://bugzilla.gnome.org/show_bug.cgi?id=778508
  * https://bugzilla.gnome.org/show_bug.cgi?id=778834

Backstory: HiDPI support was merged in Windows really quite recently, later than for X11/Wayland, and 3.22.7 as bundled with MyPaint-w{32,64} 1.2.1 right now contains it.

**Comment by thekyriarchy** [comment]
>Might be an upstream problem with HiDPI support on windows since it is working as intended on Linux.

MyPaint does not scale along with the rest of my desktop/apps on Fedora 27.
