### ISSUE TITLE
Layer list drag exception, possibly causing "Pen Color smudging with a semi-transparent layer on top" (drawing to wrong layer?)

### ISSUE THREAD

**Issue by drdurrible** [mypaint/mypaint#713]
#### Description of the problem

Colour of the pen merged with the semi-transparent level above it. 
#### Basic system details

MyPaint version: [1.2.0+git.f62444e.dirty]
Operating system: [Windows 10]
Desktop environment: [Default Windows 10 layout??]
#### Steps to reproduce

[☞ Tell us how to reproduce the bug in clear, numbered steps.]
1. Start MyPaint
2. Started Painting
3. Painted underneath a layer that was semi-transparent
4. Got error and this is what the colouring had the layer underneath blended with the current colour.
   as seen here: https://gyazo.com/9a0c74ae1bff79f33fcb315c99a18a48
   and also clearer here: https://gyazo.com/fd6c7faa86d2a21921a268dcc78eaf98
#### Backtraces or error messages

``````
[✍ Paste any error messages here between the ``` lines.]
```python
Mypaint version: 1.2.0+git.f62444e.dirty
System information: Windows-8-6.2.9200
Traceback (most recent call last):
  File "C:\Program Files\MyPaint\share\mypaint\gui\layers.py", line 523, _drag_motion_cb(self=<RootStackTreeView object at 0x8791cf0 (gui+layers+RootStackTreeView at 0x41ba5c0)>, view=<RootStackTreeView object at 0x8791cf0 (gui+layers+RootStackTreeView at 0x41ba5c0)>, context=<gtk.gdk.Win32DragContext object at 0x6d12ea0 (GdkWin32DragContext at 0xa765460)>, x=85, y=16, t=8704812L)
        def _drag_motion_cb(self, view, context, x, y, t):
            dest_treepath, drop_pos = self._get_checked_dest_row_at_pos(x, y)
            self.set_drag_dest_row(dest_treepath, drop_pos)
  variables: {'drop_pos': (None, []), 'self._get_checked_dest_row_at_pos': ('local', <bound method RootStackTreeView._get_checked_dest_row_at_pos of <RootStackTreeView object at 0x8791cf0 (gui+layers+RootStackTreeView at 0x41ba5c0)>>), 'x': ('local', 85), 'y': ('local', 16), 'dest_treepath': (None, [])}
  File "C:\Program Files\MyPaint\share\mypaint\gui\layers.py", line 504, _get_checked_dest_row_at_pos(self=<RootStackTreeView object at 0x8791cf0 (gui+layers+RootStackTreeView at 0x41ba5c0)>, x=85, y=16)
                # Can't move a layer to its own position, or into itself,
                elif lib.layer.path_startswith(dest_path, src_path):
                    dest_treepath = None
  variables: {'lib.layer.path_startswith': ('global', <function path_startswith at 0x000000000533F828>), 'dest_path': ('local', (0,)), 'src_path': ('local', None)}
  File "C:\Program Files\MyPaint\share\mypaint\lib\layer\tree.py", line 2049, path_startswith(path=(0,), prefix=None)
        """
        if len(prefix) > len(path):
            return False
  variables: {'len': ('builtin', <built-in function len>), 'path': ('local', (0,)), 'prefix': ('local', None)}
TypeError: object of type 'NoneType' has no len()
``````

**Comment by achadwick** [comment]
Please fill in these details too: MyPaint version, Operating system, Desktop environment. Thanks!

**Comment by achadwick** [comment]
@drdurrible I can't reproduce this with the current development code (at 4275f1a711af6cd6075c50ae9e37531b0fe17a74). Please can you tell me some more details?

* How did you create the semi-transparent layer?
* Does that mean "a layer with Normal mode and an opacity < 100%"?
* Does this always happen when you take these actions?
* Can this be be reproduced with a fresh config (if you care to back up and reset your config folder - see the wiki FAQ)

Thanks :smile:

**Comment by drdurrible** [comment]
1) Just pressed the plus to add in an extra layer
2) Yes, the layer that was causing the error had an opacity of about 10 or so % 
3) No, it was just the once. I tried it again and everything seems to be working alright. 
I drew something on one layer, added in a second and lowered the opacity, added in some white over it to make the lines on the previous layer less visible, and when i went back to draw on the first layer created everything was fine.

**Comment by achadwick** [comment]
@drdurrible 
Looks (to me) like the top layer had the effect you wanted? No obvious breakage there (like random tile absences, no effect when you draw after that...?)

* Or did what you painted end up on the _wrong_ layer? I don't see any semitransparent black.

I don't think this thing is a transparency thing. That backtrace is telling me that somehow a layer drag in the layer list was active. That's the sort of drag you do to move a layer up or down in the pile (when it works¹)

* Hey, did you get the exception and *only then* get the "merged with the semi-transparent level above it"? I'm still not quite sure what that means, TBH.

(If there's some sort of lingering grab from the drag, that also explains why it's a one-off. Probably *felt* weird as heck too; pointer grabs that last longer than they should always freak me out. YMF that hitting Escape cancels such a thing. And that cute exception dialog of ours doesn't really help when new windows appearing may disrupt grabs because windowing system seasons.)

-- 
¹ We have had So. Many. Problems. with layer drag code, thanks to upstream cockups. That's what the move buttons are for. If anyone can come up with a recipe for reproducing this exception in the layers tree, I would be Most Obliged.

---------------------------------------

Anyway, 'nuff speculation. We have to refine these issues to stuff we can actually fix. That motion handler code needs fixing up. There's obviously some code of ours that isn't checking that all the data that gets thrown around and comared during a drag makes sense.

**Comment by AesaraB** [comment]
Closed as stale
