### ISSUE TITLE
Pressure not working: Wacom Intuos Draw, Wacom Intuos Pro M

### ISSUE THREAD

**Issue by Tealerd** [mypaint/mypaint#717]
#### Description of the problem

The pressure sensitivity is not working with my new Wacom Intuos Draw tablet , even though it is working on other drawing software.
![image](https://cloud.githubusercontent.com/assets/20239715/16516878/40cdb74e-3f83-11e6-8315-2f1fe1fe5034.png)
#### Basic system details

MyPaint version: 1.2.0 stable
Operating system: Windows 8.1
Desktop environment: Windows 8.1 default desktop
#### Steps to reproduce
1. Start MyPaint
2. Attempt to draw in MyPaint
3. Pressure fails to work in MyPaint
4. Attempt to fix the pressure through the Wacom Tablet Properties
5. Pressure still is not working

**Comment by achadwick** [comment]
@Tealerd Some more questions:

* What driver version is installed please? Make sure you're using the latest version from <http://www.wacom.com/en-us/support/intuos-support-detail>.
* What other software did you try?
* Please paste the full MyPaint version number from Help → About MyPaint, including GTK library versions etc. if available (... they may not be with 1.2.0 ...).
* Have you tried any more recent beta releases of MyPaint? Do you get pressure at all with those?

**Comment by achadwick** [comment]
In all likelihood, this is another upstream issue with GDK.

**Comment by Tealerd** [comment]
I did download the latest Drivers for Intuos (Driver 6.3.16-2) from the moment I began to use the tablet.
I have tried software like Krita 3.0, MediBand Paint Pro and ArtRage Lite. The pressure sensitivity works in these programs .
The full number version of the MyPaint I used is 1.2.0+git.f62444e.dirty ,I had also tried using an older version of MyPaint (v1.1.0) , but the pressure did not work there either.
I haven't yet tried any newer beta releases of MyPaint, since I believed using a stable release would be more effecient. Should I proceed to download the latest beta release to see if that will work?

**Comment by achadwick** [comment]
@Tealerd
Yes please, sorry about this. I don't have access to that model of tablet myself, so somebody will need to confirm that it's still happening with a recent build.

MyPaint Windows releases ship with quite different versions of GDK. That's the lib that pulls in your driver's wintab.dll and translates wintab input events into the cross-platform GDK events that MyPaint can process. GDK has been buggy recently because not enough people are testing it with art programs under Windows (sigh), but I'm not ruling out wintab just yet. For me, the Wacom wintab.dll has been pretty well-behaved for my old Intuos 5.

Recent MyPaint betas will report their GTK/GDK version in the about box. We'll need that info.

(None of the programs you mention use GDK, but we've ruled out hardware issues for now at least! They may or may not be using wintab.)

**Comment by Tealerd** [comment]
I downloaded the v1.2.1-beta.1 and here is the full information I got : 
1.2.1-beta.1+gitexport.3198e3f

(Python 2.7.11, GTK 3.20.3, GdkPixbuf 2.34.0, Cairo 1.15.2, GLib 2.48.0)

**Comment by achadwick** [comment]
@Tealerd 
Thanks. Does pressure work with GTK/GDK 3.20.3?

**Comment by Tealerd** [comment]
It still does not work.

**Comment by DanySnowyman** [comment]
Hi everyone!

I have the same pressure issue with my Intuos Pro M. No matters what version I use (I tryed from version 1.0 to 1.2.1 beta). The tablet not even shows itself on Preferences/Devices tab. USB or wireless connections was tested too. I use Win10 but I checked the problem on Win7 and Win8 with the same results. I also have an older Wacom Pen tablet that works fine on any version of myPaint. I have no problem with the pressure using Krita, but myPaint problems happen also on Gimp 2.8.16.

Is difficult for my to express myself in english, but I wanted to help a little about this.

**Comment by bobvanderlinden** [comment]
I had the same problem, but was running 1.2.0-beta.3. I just upgraded to 1.2.1-beta.1 
(Python 2.7.11, GTK 3.20.3, GdkPixbuf 2.34.0, Cairo 1.15.2, GLib 2.48.0) and the issue was solved for me. It now also shows `WACOM Tablet Pressure Stylus` in the Preferences, whereas it wasn't listed before upgrading.

While upgrading I did open up the Wacom Desktop Center and opened Wacom Tablet Properties, but didn't change any of the settings. I'm using Wacom Driver version 6.3.15-1 (from Wacom Tablet Properties -> About).

**Comment by DanySnowyman** [comment]
I upgraded to 1.2.1-beta.1 too, but still doesn't work and doesn't show it in Preferences tab either. My Intuos Pro M is simply invisible to MyPaint. My Wacom Driver version is 6.3.17-3.

I tested it on 32 bits version. 64 bits doesn't launch.

**Comment by achadwick** [comment]
There are a lot of reports on this bug, and not a lot I can do about it.

Who would be up for testing with an MSYS2 installation? Because this is sounding very much like an upstream problem in GDK that cannot be fixed here ("it works with one Wacom tablet model, it doesn't work with another Wacom tablet model..." (this is useful info and thank you for mentioning that)).

MSYS2 is the open source development environment we use. It is self-contained and safe for your computer if you deploy it alongside your existing programs.

* Install instructions at: <https://msys2.github.io/>.
* Upgrade it **fully** per the instructions on that page
* Start its **MSYS64** shell, and in it:
  * Type `pacman -S --noconfirm mingw-w64-x86_64-gtk3` and press :leftwards_arrow_with_hook: (Enter or Return).
  * Let the _pacman_ tool install gtk3 and all its dependencies
  * Type `gtk3-demo --run=event_axes` (and press return/enter again).
     * **Tell us**: do you have pressure blobs in the tester window? I think they're red-on-blue, from memory...
  * Close the two windows belonging to gtk3-demo.
  * **Tell us**: the version of GTK3 which that was (you can find out from the installation step, or by typing `pacman -Qi mingw-w64-x86_64-gtk3`.
* Then  please repeat with the **MSYS32** shell. The package name for this is `mingw-w64-i686-gtk3`.

(Note that the MyPaint prefs can be a bit of a red herring. You have to try and use the tablet before it becomes listed on Windows. gtk3-demo 's little axis tester is far more responsive.)

**Comment by DanySnowyman** [comment]
Hi again. I installed MSYS2 and I followed carefully the instructions given on https://msys2.github.io/ but then, after I typing "pacman -S --noconfirm mingw-w64-x86_64-gtk3" some error occured and I have obtained nothing from the order "gtk3-demo --run=event_axes" after it. I already checked one by one all the steps, looking for some mistakes, but I didn't solved it yet.

I'm sorry, I'm not a dev or nothing similar, but I wanted to help. It looks like I'm a little useless here.

**Comment by achadwick** [comment]
@DanySnowyman 
I'm sorry, there were some upstream changes in MSYS2 which meant my instructions stopped working. It's not you, it's my lack of testing combined with an unforeseen MSYS2 installer omission msys2/msys2.github.io#31

The workaround is to create the "native" roots manually before installing gtk3. Again, sorry about this.

```sh
# Installer addendum for msys2-x86_64-20160921.exe --
pacman -Sy pacman   # then close the window if needed
pacman -Syu     # then close the window if needed
pacman -Su
mkdir -p /mingw64 /mingw32

# Testing GTK3 event axes in mingw64.exe --
pacman -S --noconfirm mingw-w64-x86_64-gtk3
gtk3-demo --run=event_axes

# Testing GTK3 event axes in mingw32.exe --
pacman -S --noconfirm mingw-w64-i686-gtk3
gtk3-demo --run=event_axes
```

The goal here is to get somebody with the hardware in question to quickly test whether it's GTK or MyPaint that's at fault here.

**Comment by achadwick** [comment]
Testing so far:

Reporter | OS ver | MyPaint ver | Drivers ver | Tablet model name | Tablet model # | Pressure in MyPaint? | Pressure in GIMP?
-------- | ------ | ------- | ------- | --------- | ------------- | ----------- | -----------
@Tealerd |   | 1.1.0 | 6.3.16-2 | Intuos Draw |  | no |  
@Tealerd | Win 8.1 | 1.2.0 | 6.3.16-2 | Intuos Draw |   | no |  
@Tealerd | Win 8.1 | 1.2.1-beta.1 | 6.3.16-2 | Intuos Draw |   | no |  
@DanySnowyman | Win7 … Win 10 | 1.0.0 … 1.2.1-beta.1 | 6.3.17-3 | Intuos Pro M |   | no | no
@bobvanderlinden |   | 1.2.0-beta.3 | 6.3.15-1 |   |  | no | 
@bobvanderlinden |   | 1.2.1-beta.1 | 6.3.15-1 |   |   | YES | 

Please help me fill in the blanks!

**Comment by achadwick** [comment]
@ everyone
Also, when you have uncovered the model number of your tablets, can you try searching the upstream (GTK+) bug tracker? [Start by editing this query](https://bugzilla.gnome.org/query.cgi?bug_status=__all__&content=Intuos&no_redirect=1&product=gtk%2B&query_format=specific).

Please paste any upstream bugs you find which are relevant.

**Comment by achadwick** [comment]
Common factor so far is Windows, making it extra-likely that this/these is/are upstream GDK issues.

**Comment by DanySnowyman** [comment]
Hi again! This MSYS2 thing worked well this time. I simply obtained grey circles on the testing screen. They not seem to have pressure response. The size and color of the circles didn't change no matter how much pressure that I apply with the pencil. I tryed both 32 and 64 bits versions of MSYS2. The model number of my Wacom Intuos Pro M is PTH-651. Hope it helps. And again, sorry about some mistakes, my english is only basic.

**Comment by bobvanderlinden** [comment]
Just for some extra info to complete the testing results.

OS: Windows 10
Model: Intuos Pen & Touch Medium (CTH-680)
Driver version: 6.3.15-3

Steps to reproduce a working condition on my system:

* I connect the device.Open up MyPaint.
* Notice there is no pressure sensitivity.
* Close MyPaint.
* Open Wacom Desktop Center -> Touch Settings -> Open Touch input & gesture settings -> Tab "Pen".
* Notice that the pressure is visualized correctly there.
* Open up MyPaint again.
* Notice that pressure sensitivity is working correctly.

**Comment by DanySnowyman** [comment]
Unfortunately, my Wacom Intuos Pro M doesn't work even if I do that bobvanderlinden says. I forgot to tell that the pressure issue is the same either if the tablet is plugged via USB cable or through the wireless module.

But I can add a little more info to the problem. I also own a Wacom Intuos Pen Small (Model CTL-480). I tested it on the same PC. The pressure works fine either in MyPaint or both versions of MSYS2 (32 and 64 bits).

I hope that this helps a bit. I love MyPaint and I'm very sad about can't be able to use it with my new hardware.

**Comment by achadwick** [comment]
I've updated the table.

@DanySnowyman 
It seems the drivers are different for Intuos Pro and Intuos Pen models, in that the Intuos Pen only has  6.3.15-2  available, and Intuos Pro has 6.3.17-3 available. But you are using the most recent version, the drivers seem to be for the same product _range_, and your testing split works in the opposite way to what I expected. Ugh, what a mess! :disappointed: 

However, thank you for testing in MSYS2. This gets us somewhere. Please can you tell me what **version of GTK it was using** when you tested? This is very important information. Please use the commands below to find out, only the version bit matters :smile: 

```
pacman -Qi mingw-w64-i686-gtk3
pacman -Qi mingw-w64-x86_64-gtk3
```

If you could also doubly confirm that you are using the latest available driver version, `WacomTablet_6.3.17-3.exe`, that would be useful.

**Comment by achadwick** [comment]
(The GTK version is likely to be 3.22.1, if it was recently updated MSYS2)

**Comment by DanySnowyman** [comment]
Yes, the GTK version is 3.22.1-1 for both 32 and 64bits versions, and the WacomTablet driver, you're right, is the last 6.3.17-3 version. The MyPaint pressure problem is the main reason why I'm always looking for the last driver updates xD

**Comment by kaiKitsune** [comment]
Reporter 	                me
OS ver 	 	 	Win7x64 sp1
MyPaint ver 	 	1.2.0+git.f62444e.dirty [think a tumagonx build, portable by me]
GIMP ver 	 	        GIMP-CCE 2.9.5 [Partha x64 build portable]
Drivers ver 	 	3.1.0.3
Tablet model name 	Intuos 4
Tablet model #         PTK-840
Press in MyPaint? 	yes
Pressure in GIMP?    yes

**Comment by achadwick** [comment]
@Tealerd 
[MyPaint v1.2.1](https://github.com/mypaint/mypaint/releases/tag/v1.2.1) has now been released. Please can you test whether or not this bug is still happening in that version?

There have been quite a few GTK updates bundled into this MyPaint build. It's now using GTK 3.22.7, which should be a pretty major improvement for Windows tablet support. Oh, and it bundles GTK3-Demo too, so you can test against that too ☺

**Comment by DanySnowyman** [comment]
I was excited about this update. I installed it fastly when I saw it. Unfortunately, the problem remains. I tested all combinations of Intuos Pro M, plugged or wireless, with the 32 and 64bits versions. Nothing has changed. I don't have pressure and the tablet still is missing in the devices tab. I am expecting anxious for a solution, because I love this program and I'm not capable for use it for a long while, except with my little Intuos Pen Small, that works pretty well but is not the same.

Thank you for still trying to solve it.

**Comment by achadwick** [comment]
@DanySnowyman 
Please can you test with our bundled GTK3-demo?

![2017-01-21 new testers](https://cloud.githubusercontent.com/assets/61299/22183870/c2437c4a-e0bf-11e6-8eea-2a3d88cb2ab4.png)

![2017-01-22 gtk3-demo event_axes screenshot](https://cloud.githubusercontent.com/assets/61299/22183869/c23f0430-e0bf-11e6-8f50-fb99870cded0.png)

* Please make sure you are using the latest drivers from <http://www.wacom.com/en-us/support/product-support/drivers> first, and reinstall them to be sure that wintab is correctly set up.
* Do you use Lazy Nezumi or any other smoothing software? Turn it off or uninstall. Any difference?
* I noticed I was getting an oddity where the 1st time launching MyPaint or GTK3-Demo in a session didn't get pressure, but the 2nd did.

This looks likely to be an upstream issue. Hopefully the support matrix is *considerably* better now though!

**Comment by achadwick** [comment]
Strictly for extra credit in debugging this with MyPaint v1.2.1 on Windows:

1. Go to `C:\Program Files\mypaint-w64\usr\bin` or `C:\Program Files (x86)\mypaint-w32\usr\bin`, i.e. the bin folder of where you installed it.
2. Run the `bash.exe` you see there by double-clicking it.
3. In the bash session, type (very carefully, this is unforgiving of typos!)

    ```shell
    $ cd /
    $ mingw64/bin/gtk3-demo.exe --gdk-debug=input --run=event_axes
    ```

It's the console output that you *should* see after "wintab init: doing delayed initialization" that we need to see. To copy, you need to go to the console menu, Edit→Mark, scroll back to top and click-drag from the top-left to the bottom right. You can then paste that into Notepad and attach it here. Here's an example: 
[debugout_example.txt](https://github.com/mypaint/mypaint/files/722082/debugout_example.txt). It looks like the stuff below, but I'm truncating it to avoid flooding you all.

```
bash-4.3$ cd /
bash-4.3$ /mingw64/bin/gtk3-demo.exe --run=event_axes --gdk-debug=input
wintab init: doing delayed initialization
Wintab interface version 1.4
NDEVICES: 1, NCURSORS: 6
Device 0: WACOM Tablet
Using device-specific default context
Default context:
[... Initialization stuff here ...]
_gdk_input_set_tablet_active: Bringing Wintab contexts to the top of the overlap
 order
[... This is where your tablet becomes active in a GTK application ]
[... There's lots more if you start moving the stylus, so avoid doing that! Just exit using a mouse.]
bash-4.3$
```

**Comment by DanySnowyman** [comment]
Hi again! I tryed again, but no results. No red dots with the bundled GTK3-demo. I was done that before but I tested again, just in case.

Here you are the debugout.txt you asked me. I didn't touch the tablet in the process, just as you said. I hope it's that you wanted.

[debugout_danysnowyman.txt](https://github.com/mypaint/mypaint/files/722256/debugout_danysnowyman.txt)

**Comment by Tealerd** [comment]
In my case, the pressure problem has been fixed ! (Regarding most brushes)  So thanks to everyone who worked on the new version.
I am only concerned on wether or not one can lock the alpha of a layer, since I cannot seem to find that option anywhere.

**Comment by Vestrond** [comment]
Win 7
1.2.1+gitexport.bcf5a28d
Intuos  Draw (CTL-490)
Pressure dont working in test and in MyPaint.
bash.exe dont write anything after _**wintab init: doing delayed initialization**_

**Comment by achadwick** [comment]
@Vestrond:
This is definitely an upstream issue (hah, i'm the one who added that "wintab init: doing delayed initialization" line).

### Please report upstream (GTK+/GDK)

This is a bug in the GTK+/GDK libraries. We don't maintain these components ourselves. This bug should be reported in the GNOME bugtracker, against the “gtk+” component so that their developer know about it.

* [Search GNOME Bugzilla for this bug first](https://bugzilla.gnome.org/buglist.cgi?bug_status=__all__&content=KEYWORDS+HERE&no_redirect=1&order=Importance&product=gtk%2B&query_format=specific). It may already have been reported!
* Use this form if you can't find it: [Enter Bug: gtk+](https://bugzilla.gnome.org/enter_bug.cgi?product=gtk%2B). You may need to create an account.
* Please post links to relevant upstream bugs here :smile:

The GNOME Bugzilla is quite technical, but don't be discouraged. We can help you get it right here, and we have a few guides for reporting good bugs in our own wiki. See [our wiki's Contributing section](https://github.com/mypaint/mypaint/wiki/Contributing) for details.

**Comment by achadwick** [comment]
@Tealerd 
It's a brush option, "lock alpha".

**Comment by AesaraB** [comment]
[Added to compatibility table](https://github.com/mypaint/mypaint/wiki/Device-support-table)
