### ISSUE TITLE
using color picker crashes with segmentation fault on centos.

### ISSUE THREAD

**Issue by cg-cnu** [mypaint/mypaint#719]
#### Description of the problem

using color picker (ctrl+ left click) causes crash with the error Segmentation fault (core dumped).
#### Basic system details

MyPaint version: 1.2.1-beta.1+gitexport.3198e3f
Operating system: CentOS Linux release 7.2.1511 (Core)
Desktop environment: KDE 4.14.8
#### Steps to reproduce
- ctrl+left click on the canvas.
- mypaint crashes with segmentation fault.
#### Backtraces or error messages

```
DEBUG: gui.freehand: Remove motion event compression workaround: restoring event_compression to True (<TiledDrawWidget object at 0x3dcce60 (TiledDrawWidget at 0x3e0e6f0)>)
DEBUG: gui.mode: BrushworkModeMixin: leave()
WARNING: py.warnings: /home/salapati/Downloads/mypaint-1.2.1-beta.1/gui/tileddrawwidget.py:605: PyGIDeprecationWarning: idle_add is deprecated; use GLib.idle_add instead
  gobject.idle_add(self.update_cursor)

DEBUG: gui.document: Mode changed: <ModeStack [FreehandMode, ColorPickMode]>
Segmentation fault (core dumped)
```

A bit of further info... since oxygen is buggy with gtk apps my current mypaint launch command is this..

`MYPAINT_DEBUG=1 GTK_THEME=Adwaita ./mypaint -c /tmp/cfgtmp_throwaway_1`

Let me know if any info needed.

**Comment by achadwick** [comment]
Yes please! This one will need a `gdb` backtrace because it is a segfault. Sadly we don't have much documentation for CentOS users there, but I'll try to explain now the best I can.

* Generic Instructions: https://github.com/mypaint/mypaint/blob/master/DEBUGGING.md#debugging
* Also relevant: [some more spelled-out instructions for Windows](https://github.com/mypaint/mypaint/wiki/Debugging-crashes-on-Windows). Ignore the MSYS2 nonsense, it's the gdb info that's relevant.

---------------------------

## Debugging segfaults on CentOS 7

For CentOS 7, you need to enable the DebugInfo repository to gain access to the [*-debuginfo packages](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Developer_Guide/intro.debuginfo.html). Edit the relevant `.repo` file as root:

    $ sudo yum install nano    # or vim, or emacs...
    $ sudo nano /etc/yum/repos.d/CentOS-DebugInfo.repo

Change `enabled=0` to `enabled=1`, save, and exit. After this, you can do

    $ sudo yum install gdb
    $ sudo yum install python-debuginfo gtk3-debuginfo

and any of the other debuginfo packages that might be needed for the _gdb_ debugging sessions. After this, generic GDB instructions should start making sense. Well, maybe.

----------------------

Debugging's a bit of an art for sure, but it's the output of `bt` or `bt full` that's needed here. Good luck!

**Comment by achadwick** [comment]
Can you let us all know what version of gtk3, glib2 you're using too? Thanks!

**Comment by QuLogic** [comment]
I think you should use `debuginfo-install` instead of manually enabling the repo.

**Comment by achadwick** [comment]
@QuLogic 
I read about that too, but it seems to be either a Red Hat ~ism, or something that isn't present in my typical minimal CentOS installs. What package does it reside in?

**Comment by QuLogic** [comment]
It appears to be in `yum-utils`.

**Comment by achadwick** [comment]
@cg-cnu 
Please respond. We cannot do anything about segfaults without a backtrace.

[MyPaint v1.2.1](https://github.com/mypaint/mypaint/releases/tag/v1.2.1) was released recently. Please could anyone affected by this bug please test with either that or git master, and let us know whether the bug is still happening?

**Comment by cg-cnu** [comment]
@achadwick Sorry for MIA. I have moved away from mypaint for a while and don't have the same setup anymore. We can close this if no one else faced the issue. Sorry for the trouble. 
And thanks so much for the amazing MyPaint 🙂
