### ISSUE TITLE
[Win7] Recovery File Cache hit by CCleaner

### ISSUE THREAD

**Issue by KirshD** [mypaint/mypaint#729]
Finally had mypaint crash on me (1.2.0, flash ad in chrome ate up system resources) and went to use the Recovery option. I found that the autosaves it had been making were removed by CCleaner when it cleared out the Temporary Internet Files. Might be a good idea to move the Autorecover cache to a different directory.

**Comment by achadwick** [comment]
The autorecovery cache is designed to be deletable, if that makes sense. It is supposed to be located somewhere you can do that: ~/.cache on Linux systems, Temporary Internet Files on Windows systems.

Don't rely on the auto-recovery cache persisting indefinitely. It doesn't, and shouldn't. In particular, CCleaner can be expected to delete cache files.

As for the choice of location: this is a more general GLib issue because we use [g_get_user_cache_dir()](https://developer.gnome.org/glib/stable/glib-Miscellaneous-Utility-Functions.html#g-get-user-cache-dir). IMO what we are doing right now is correct, both in terms of the call we use, and in terms of the effect it has on Windows.

There may be more sensible locations for this folder on the Windows platform that I don't know of, however. If anyone knows of one, it should be reported to the GLib maintainers in [upstream bug 659349](https://bugzilla.gnome.org/show_bug.cgi?id=659349).
