### ISSUE TITLE
downloads windows version x32 and x64 beta 1

### ISSUE THREAD

**Issue by Jen01** [mypaint/mypaint#733]
#### Description of the problem

download windows 64 and 32 bit 1.2.1 beta 1 goes to 23.7 kb/sec; i tried both; download time estimated at 2 hours for 80mb.  am downloading open office at regular speeds - 50 mb in about 1 minute. the download takes so long it "fails". can you let me know what the download speed is set at for your site?  is anyone else having an issue?  was using 1.2.0 and am simply trying the newer beta version.   was trying to download for at least an hour.  

After posting this, I was able to download the 1.2.1 beta 0 and then I tried the beta 1, and the whole program downloaded in a normal (very short) time. 

this is a good program.  appreciate the work you are all doing on it. @

**Comment by achadwick** [comment]
Hi there - thanks for the feedback! Sorry, but this is the wrong place for this discussion.

* If you tried from https://github.com/mypaint/mypaint/releases ...
  * It sounds like a temporary problem with github, which we do not control, or your networking, which we also do not control.
  * Try again, and if the problem persists report it via https://github.com/contact
* If you tried from literally anywhere else:
  * This is not "our site" in any sense at all. Contact the site owner instead please.

This issue tracker is not for direct user support. We try to limit it so that each thread is a single fixable issue which can be closed by changing the MyPaint code. I won't close this report straight away though because sometimes we can help. Often the feedback is useful too, and sometimes support requests can turn into stuff programmers can actually do something about!
