### ISSUE TITLE
Crash on pen input

### ISSUE THREAD

**Issue by Karkalicious** [mypaint/mypaint#736]
Sorry if I'm not posting this to the right place, I'm new to this.
I just downloaded MyPaint onto my Windows 10 laptop, and was using it with my Ugee graphics tablet. For the first twenty minutes or so, it was working just fine, but then it crashed. Now, whenever I open it and so much tap the pen to the surface of my tablet, it crashes, no matter what I've tried.

MyPaint version is 1.2.1-beta.1.
Operating system is Windows 10, 64-Bit
Desktop environment is... I'm not sure what this means? But I have a Toshiba Satellite L875-S7108 laptop, if that's what you mean.

Steps to reproduce are pretty straightforward...
1. Start MyPaint.
2. Touch stylus to tablet.
3. Bam, crash.

Backtraces or error messages

For the crash, all there is this:

If any additional information is needed, do tell. This program was so nice for the little time I could use it. I'm eager to use it without a crash getting in the way. Thanks in advance.

![image](https://cloud.githubusercontent.com/assets/22651793/19140283/a3d08390-8b59-11e6-8f74-aec6d7e61bb4.png)

**Comment by achadwick** [comment]
Hi there - thanks for the report!

We'll need a backtrace to do figure this one out, so standard response first: please read <https://github.com/mypaint/mypaint/wiki/Reporting-Bugs> if you haven't already.

I need you to make sure this is a bug, first. Please try: restarting your computer, reinstalling MyPaint, (re)installing the latest tablet drivers, restarting again, and _then_ seeing if the issue is still present.

If that doesn't work, please then try resetting your MyPaint configuration as well. Instructions here: <https://github.com/mypaint/mypaint/wiki/FAQ-Factory-reset>. This is less likely to make the problem go away: it's the wrong sort of crash, really. But it's worth a try.

If that doesn't fix it, somebody with this hardware, or someone experiencing the same fault, needs to debug the underlying code and find the faulty function.

:pill:  :rabbit:  :hole:  :straight_ruler:

If you're willing to start digging, please try the techniques documented in <https://github.com/mypaint/mypaint/wiki/Debugging-crashes-on-Windows>. This involves getting a copy of our dev environment onto your computer, building a working copy of MyPaint yourself, and trying to break it while its running inside the low-level debugger. It's pretty involved stuff if you go all the way, but you can start off small by seeing whether one of the utilities inside that dev environment crashes too. We have pretty good instructions on the Debugging wiki page for this - do you feel up for it?

We've had a lot of random issues with Ugee tablets in the past, just search the tracker. Many sort of inconclusive. You might be able to help out a lot of people if you have a decent amount of technical skill

:neutral_face:  I must write that "Debugging tablet issues" page in the wiki, but every case is just a little bit different.

**Comment by gerroon** [comment]
get python2w crash as well on my Surface

**Comment by achadwick** [comment]
@Karkalicious --

[MyPaint v1.2.1](https://github.com/mypaint/mypaint/releases/tag/v1.2.1) was released recently. Please could anyone affected by this bug please test with either that or git master, and let us know whether the bug is still happening?

(My hopes are raised for this one. I've been putting in some time fixing tablet stuff in the GDK we bundle...)

(Not ignoring @gerroon, but theirs is a very separate case... :smile:)

**Comment by Karkalicious** [comment]
@achadwick

I'll check for you.

**Comment by AesaraB** [comment]
Closed as stale
