### ISSUE TITLE
Make the AppImage available on GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [mypaint/mypaint#746]
Right now an [AppImage](http://appimage.org/) is uploaded to transfer.sh for each build. But for users this is a bit inconvenient, since they need to look up the transfer.sh download URL in each Travis CI build log. Hardly anyone will look for it there.

Hence it would be nice if for releases and possibly also for continuous builds, the AppImage could be downloaded to the GitHub Releases page as well.

Personally I am using https://github.com/probonopd/uploadtool for this. Could easily be adapted to your needs.

**Comment by duckdodger** [comment]
I'm also interested in this. My distribution doesn't provide the latest mypaint (currently on 1.1.0), so I'd appreciate if there were an AppImage available. @achadwick ?

**Comment by probonopd** [comment]
@duckdodger an AppImage already gets build now for each commit and stored for 14 days. You can find the transfer.sh download URL toward the end of the Travis CI build log (e.g., [here](https://travis-ci.org/mypaint/mypaint/builds/188100605#L8765)). This ticket is about making this AppImage accessible right on the [GitHub Releases page](https://github.com/mypaint/mypaint/releases).

**Comment by duckdodger** [comment]
Oh, cool! Yeah, I found it. Thanks!

**Comment by duckdodger** [comment]
I think it would be better to only (or also) include the AppImage of the stable release in the releases section. And I seem to be having a small problem with the latest build, where the UI is just ugly (picture below). It's probably due to the fact that I'm on KDE and it's not using the GTK theme properly. But the version provided for my distro (openSUSE) has a consistent UI. Could it be a problem with the AppImage? 
![screenshot_20170104_193457](https://cloud.githubusercontent.com/assets/17142033/21644738/eccba230-d2b4-11e6-91e1-8f2beb8aa54f.png)

**Comment by probonopd** [comment]
Yes, stable releases should also be uploaded.

It could be that the Qt in your distribution uses a different theme engine such as QGtkStyle which the AppImage does not bundle. I am unfortunately not an expert in Qt but I assume that some theme engine would have to be bundled with the AppImage. Also, it seems like Qt 5.7 has dropped the support for GTK 2 themes if I am not mistaken and GTK 3 themig for Qt is not there yet. I might be wrong though.

**Comment by karai17** [comment]
I would definitely appreciate AppImages for MyPaint. As stated above, Fedora hasn't been updated since v1.1.0, which really shows why AppImage is so useful... Distros can be very slow up update the software in their repos and it is largely a volunteer effort. Having developers release AppImages that will run anywhere is just plain useful.

**Comment by odysseywestra** [comment]
We're in the process of changing how we build and distribute. Once that is done, we'll have the appimages available in github releases due to automating the build process via Appveyor and Travis. Till then you will have to look at the bottom of the Travis Logs to find the link to download the appimages.

**Comment by karai17** [comment]
Thanks, I'll do that. One thing I noticed is that the AppImage does not seem to be reading my system theme. Is this a known issue?

**Comment by manuq** [comment]
@karai17 you can now install MyPaint stable in Fedora from [flathub.org](http://flathub.org/):

    flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

After that use the Software application to install MyPaint from flathub source. Or:

    flatpak install flathub org.mypaint.MyPaint

**Comment by probonopd** [comment]
Reference:
https://github.com/AppImage/AppImageHub/issues/15

**Comment by odysseywestra** [comment]
For the most part appimage is now our default builds now and is part of the release cycles. Closing since this is accomplished. Thank you @probonopd for putting up with us.

**Comment by probonopd** [comment]
Thank you very much. I tried it and it is working well for me. 👍
