### ISSUE TITLE
Enhancement: Brush Shortcut Keys restore LAYER

### ISSUE THREAD

**Issue by borfo** [mypaint/mypaint#756]
**Use case**:  One of the things I'm using mypaint for a lot these days is as a brainstorming notepad - I choose a lined or graph paper background, save a "pen" brush (sometimes a couple for different ink colors) and a couple of "highlighter" brushes, and use the infinite canvas basically as you'd use a paper notepad with a wacom tablet.  Mypaint is *almost* the perfect application for this use - it feels great when drawing/writing, and the infinite canvas is perfect for this application.

**Problem**: It's a minor problem, but I wonder if the effort required to fix it would be just as minor...  I set up one layer for the notes I write with my "pen" brush, and one or more other layers behind that one to hold the "highlighting" colors.  This way, I can edit the ink layer without erasing the highlighting behind it, or change highlighting without erasing ink.  The problem is that I'll often forget to change layers when doing highlighting, or write ink on a highlighting layer.

**Solution**:  If mypaint's saved brushes could remember layers (just like they already can remember colors) this problem would be solved - switching to a highlighter would automatically switch to the right layer, etc.  I can think of other use cases where this would be useful as well.
_________________________
Would that be a relatively simple thing to implement, given mypaint's current architecture?  If it's easy and someone feels inclined to make this change that'd obviously be great.  If not, I might take a stab at doing this myself at some point - to that end, if anyone could point me to the code sections I'd want to look at that would be greatly apprectiated - that would save me a lot of looking through code I'm not familiar with...

edit: I just found the "pick stroke and layer" shortcut (w), which gets a long way towards what I'm looking for...  Cool.  Still, brushes that could save their layer would be useful.

_________________________
Another feature I'd find useful is an eraser that can erase multiple (or all) layers (so I can erase ink and highlighting at the same time) - is this currently possible?

**Comment by 0ion9** [comment]
👍  Simple, efficient, would be able to be applied to the initial stages of a lot of different workflows. I agree that Pick Stroke and Layer doesn't quite meet the potential that this idea has. Great idea. 

The existing color restoration code is pretty simple. Implementing this would probably be equally simple -- selecting active layer does not interact with undo stack, right?

> Another feature I'd find useful is an eraser that can erase multiple (or all) layers (so I can erase ink and highlighting at the same time) - is this currently possible?

Also a great idea. More complicated to implement IIRC: we'd need to render N dabs to each of N layers in turn, update display only after all N dabs have been applied, sort that out into some kind of sensible unit Undo-wise. Stroke splitting would probably also need to be modified to be aware of it. We might want to make the dab exactly the same (ie. random or time-based inputs should be fixed across the set of N) so that 'partial cutouts' cannot be left on different layers.

Then, probably people would want to *paint* to multiple layers at once. Same thing really, but might be a bit confusing when certain things like smudging get involved.

**Comment by achadwick** [comment]
Looks like the reporter has found an efficient workaround for the original complaint.

This is not a simple thing to implement in MyPaint's current architecture, because how do you save a persistent reference to a layer in a brush? You could write a layer uuid into the brush, but that only refers to one layer in one file, meaning your hotkey brushes won't work the same from one file to another (no, the context that gets saved should not include the file path :wink:)

We don't have truly persistent layer uuids yet. Even though layers are autosaved to disk during a session using a uuid for a filename, that uuid is generated afresh on each document load.

The other suggestion needs more work, and it would need work in libmypaint to achieve, as @0ion9 mentioned. It's exactly equivalent to painting to multiple layers, with brush engine state saving and restoration between each slice of brushwork. We don't have API in libmypaint for that.
