### ISSUE TITLE
How do I resize an image?

### ISSUE THREAD

**Issue by yngvark** [mypaint/mypaint#757]
How do I resize an image? I want to resize an image, and it would be nice if the width height ratio was preserved (although I want to choose).

I have looked everywhere in the program, and googled a lot, and I cannot find out how to do it.

**Comment by odysseywestra** [comment]
The Github issue tracker for MyPaint is not for user support. Please ask your support questions on our [community forums user support category](https://community.mypaint.org/c/support/).

**Comment by calston** [comment]
@odysseywestra Responses like this in Github projects are really starting to irritate me.

You read as: A dumb user is trying to do something and should go ask somewhere else.

Reality is that non-obvious usability *is* a software issue and *should* be a bug, otherwise the problem gets worked around and you end up with GIMP - full of horrific flaws and arrogant developers.
