### ISSUE TITLE
copy pasting?

### ISSUE THREAD

**Issue by StephVulpix88** [mypaint/mypaint#758]
I wanted to copy paste a picture so i can draw on it because i wish to draw clothing but i cannot draw a body so i wanted to copy paste a body but i cant...

I cant find a way to copy paste pictures
I need it to help me design clothes

Thank you for listening to my problem

**Comment by achadwick** [comment]
Hi there - thanks for the feedback!

This issue tracker is not for direct user support really. We try to limit it so that each thread is a single fixable issue which can be closed by changing the MyPaint code. I won't close this report straight away though because sometimes we can help. Often the feedback is useful too, and sometimes support requests can turn into stuff programmers can actually do something about!

We may not be able to help you straight away here, but don't be discouraged if we can't. Issue trackers don't get that many views, sadly. You may find you get more useful feedback from the [MyPaint Community Forums](http://community.mypaint.org/), or from Twitter ([@MyPaintApp](https://twitter.com/MyPaintApp), #mypaint).

**Comment by achadwick** [comment]
You *should* be able to open a file in another program, press Ctrl+C, and paste it into a MyPaint layer with Ctrl+V. I'm pretty certain I've tried this with GIMP on Linux, and MS Paint on Windows. So this *might* be a bug in MyPaint. What exactly did you try (from what, to what, how, what steps)?

**Comment by achadwick** [comment]
**TRIAGE NOTE:** looks like a user support request, but it **could** be a report of something breaking that shouldn't be breaking. This is the wrong forum for direct user support, reporter has been redirected to better places to ask (if it's more of a "how do I...?").

This issue should be closed after one week if no further information is forthcoming that would allow it to be progressed to `bug` or `enhancement` status.
