### ISSUE TITLE
Strange ability to move window with close button (can occur problems with closing mypaint). Windows 10 x64.

### ISSUE THREAD

**Issue by zb13y** [mypaint/mypaint#761]
#### Description of the problem
1. Click and hold over close button (all 3 buttons in right corner) of mypaint.
2. Move mouse.
3. Window moves, mypaint not closed. (Mostly all windows in mypaint moves with close buttons)

#### Basic system details
MyPaint version: [1.2.1+gitexport.bcf5a28d (Python 2.7.13, GTK 3.22.7, GdkPixbuf 2.36.4, Cairo 1.15.4, GLib 2.50.1)]
Operating system: [Windows 10 x64 1607 14393.693]

**Comment by achadwick** [comment]
Remarkably, I can reproduce this one! :rofl: 

This is not MyPaint's fault, however. I can reproduce it with GTK3-Demo as bundled with MyPaint v1.2.1's Windows build. It is a "problem" with GTK upstream, and it should be reported on the GNOME Bugzilla

→ https://bugzilla.gnome.org/

The behaviour is different to GNOME/X11, although the window surrounds look very similar.

### Please report upstream (GTK+/GDK)

This is probably a bug in the GTK+/GDK libraries. We don't maintain these components ourselves. This bug should be reported in the GNOME bugtracker, against the “gtk+” component so that their developer know about it.

* [Search GNOME Bugzilla for this bug first](https://bugzilla.gnome.org/buglist.cgi?bug_status=__all__&content=KEYWORDS+HERE&no_redirect=1&order=Importance&product=gtk%2B&query_format=specific). It may already have been reported!
* Use this form if you can't find it: [Enter Bug: gtk+](https://bugzilla.gnome.org/enter_bug.cgi?product=gtk%2B). You may need to create an account.
* Please post links to relevant upstream bugs here :smile:

The GNOME Bugzilla is quite technical, but don't be discouraged. We can help you get it right here, and we have a few guides for reporting good bugs in our own wiki. See [our wiki's Contributing section](https://github.com/mypaint/mypaint/wiki/Contributing) for details.
