### ISSUE TITLE
[Minor][Win7 Both][1.2.1] Maximize with Task bar @ top or left of screen creates gap

### ISSUE THREAD

**Issue by KirshD** [mypaint/mypaint#770]
Just installed 1.2.1 x64 and the window maximizes to the right dimensions but not to the right position. Also tried the 32-bit version, same thing. It can be temporarily remedied by moving the taskbar to the bottom of the screen or to the right while maximized then moving it back, but it wears off with a new instance loading, or switching to normal windowed and back to maximized. Oddly enough restoring from minimized to maximized works right. Included are screenshots. (Maybe a window size variable needs a +/- swapped?)

Experimented with re-enabling the fancy frame buffer-centric aero theme, exact same gap size, too. Have some pictures!

![what_a_gap](https://cloud.githubusercontent.com/assets/17104051/22321855/262e4932-e355-11e6-933b-83440fb8f9a6.PNG)

![what_a_left_gap](https://cloud.githubusercontent.com/assets/17104051/22321943/db51d8ce-e355-11e6-921c-3aab6597245d.PNG)

**Comment by achadwick** [comment]
* I can't reproduce this in Windows 7 Enterprise 64-bit with Aero bells and whistles when using the Windows 7 Basic theme. The maximize button operates correctly in both MyPaint and GTK3-Demo, regardless of whether the taskbar is at the bottom or the top of the screen.
* I tried in the Windows 7 Basic theme, and it's reproducible in `mypaint` and `gtk3-demo-application.exe` on the MSYS2 command line. Both of these use "standard" window surrounds, i.e. not GtkHeaderBar. It is NOT reproducable with `gtk3-demo.exe`, but that used GtkHeaderBar.
* Looks like this does not present with Aero effects turned on when using the Windows 7 theme. In this case, GTK apps display difefrent window surrounds to the ones above, which resemble the ones used on the GNOME desktop. The position bug is absent with these.

### Please report upstream (GTK+/GDK)

This is a bug in the GTK+/GDK libraries. We don't maintain these components ourselves. This bug should be reported in the GNOME bugtracker, against the “gtk+” component so that their developer know about it.

* [Search GNOME Bugzilla for this bug first](https://bugzilla.gnome.org/buglist.cgi?bug_status=__all__&content=maximize+win32&no_redirect=1&order=Importance&product=gtk%2B&query_format=specific). It may already have been reported!
* Use this form if you can't find it: [Enter Bug: gtk+](https://bugzilla.gnome.org/enter_bug.cgi?product=gtk%2B). You may need to create an account.
* Please post links to relevant upstream bugs here :smile:

The GNOME Bugzilla is quite technical, but don't be discouraged. We can help you get it right here, and we have a few guides for reporting good bugs in our own wiki. See [our wiki's Contributing section](https://github.com/mypaint/mypaint/wiki/Contributing) for details.

**Comment by achadwick** [comment]
@KirshD 
Looks like an instance of upstream's <https://bugzilla.gnome.org/show_bug.cgi?id=765161>. Please sign in and comment over there. I will do my bit and report our findings here, but I would like someone else to really take charge and chase this one upstream.
