### ISSUE TITLE
Kabyle locale for MyPaint

### ISSUE THREAD

**Issue by belkacem77** [mypaint/mypaint#787]
Hi,
We want to start Kabyle localization of MyPaint as we are using it. Please would you like enable kabyle language on https://hosted.weblate.org/projects/mypaint/.

Kabyle iso code: kab.
Kabyle is a north african Language. A latin-based alphabet.

Thanks,

**Comment by odysseywestra** [comment]
@belkacem77 I believe you can actually start a new translation. You just need to have an account and logged in on the site. It should be under `Tools > Start new translation`

**Comment by belkacem77** [comment]
@odysseywestra Thanks. I have just started it. I also shared it in FB with My community to accelerate translation and bring the tool into Kabyle. Let me know at what level (translation rate) we could get Kabyle available in mypaint?

Thanks again for you support

**Comment by odysseywestra** [comment]
@acadwhick is usually the one who merges in the translation changes from webpage. For sure you will see it in the next release (1.3), unless you build from source then it will be whenever the changes are merged into Master.

**Comment by achadwick** [comment]
I can see Kabyle being added on weblate for `mypaint`. Thanks!

I have just updated libmypaint's translator instructions, and allowed translators to create new translations of libmypaint. This wasn't working before: it needed the `libmypaint.pot` template file to be kept in the repository to allow automation. That's fixed now, and I have added `kab.po` on weblate for people to work on.

@belkacem77
If possible, please could you work on the translation of `libmypaint` too? That covers the technical brush settings strings found in the MyPaint brush settings edittor, and it will help projects like GIMP too. It is a much smaller project than MyPaint: 106 message only.

The “minimum standard” is 0% right now, because any translation is better than nothing!

**Comment by achadwick** [comment]
Other people who can work on Kabyle: https://translations.launchpad.net/+languages/kab (found when I was considering adding it manually and needed info about plural forms :smile:)

**Comment by belkacem77** [comment]
Hi, yes i invited some of them. I will ask again for contiribution

**Comment by achadwick** [comment]
Closing this issue, since the underlying problem has been fixed. Good luck with the translation effort, and thank you for the contributions so far :smiley:

**Comment by belkacem77** [comment]
Thanks again
