### ISSUE TITLE
UI in wrong language

### ISSUE THREAD

**Issue by wareya** [mypaint/mypaint#795]
The windows function GetUserDefaultUILanguage is not a function for getting the UI language. This function is used in i18n.py as a backup way to get the user's UI language.

Yes, the name of this function is wrong. GetUserDefaultUILanguage gets a setting under Region and Language → Formats, which is not a place for setting the UI language, it's a place for internationalization settings that control the format of dates, numbers, etc. and the *locale* of *non-unicode programs*.

There are legitimate reasons to have the setting under Region and Language → Formats set to a localization region different than the UI language. The correct way to get the actual UI language under windows is to use the registry (because microsoft).

Modern windows applications should only use application-specific user settings or the registry to determine what language their UI should be in.

**Comment by achadwick** [comment]
Does this affect you personally? The current title kinda implies you have an example.

Patches welcome. I would need an open-source approach to reading the relevant registry key on the Windows platform OR a way of overriding the language via preferences that will work at application startup.

Myself I think it's a decent fallback approach, since it's a setting the user can change quite easily. It's that one other apps use.

**Comment by wareya** [comment]
>Does this affect you personally? The current title kinda implies you have an example.

Yeah. I need to set Region And Language -> Formats -> Format to "Japanese (Japan)" or a certain non-unicode program I use crashes whenever it tries to display graphics.

**Comment by achadwick** [comment]
We can't account for bugs in other software, particularly not proprietary ones. It's something you need to address through their support channels, not ours. \</standard-spiel\>

That said, we do have an open request to make translations selectable within the program: see also issue #772. This could be tricky to achieve since gettext has to be initialized before libgtk.

@wareya Can you research this for me? You seem to be more of a Windows expert than I am. If there's a single API call (or a single registry key) that returns a global setting for "UI language for all apps" that can be thrown at gettext, *and* if it can be tested from Windows 7, *and* if Windows 7 users can conveniently set it, then I'm OK with switching away from GetUserDefaultUILanguage() to that approach.

What I am *not* going to do [in the short term] is bodge MyPaint to store its settings in the registry on the Windows platform just because Microsoft generically say that it should be used [well, not without a _lot_ of cross-platform thought that involves completely restructuring our configuration engine and using [GSettings](https://developer.gnome.org/platform-overview/unstable/tech-gsettings.html.en). Happy to use known registry keys as a read-only source for "what language am I?" questions, however.

(GSettings might not be too awful tbh, and it can be loaded and used before GTK at least. It's just a deeply un-Pythonic way of doing things. Also it has gettext entanglements of its own.)

**Comment by wareya** [comment]
Okay, actually, the problem is locale.getdefaultlocale(), not GetUserDefaultUILanguage(). Just make the code not use locale.getdefaultlocale() at all, it gets the localization format region, not anything language related.

I'm honestly kind of offended by the response about """other software""" so I'm not going to stick around. Bye.

**Comment by achadwick** [comment]
@wareya
Please may I know more? I want to give the sincerest apology that I can, and walk back what is necessary.

There are a lot of technical levels to disentangle around i18n, and we're got going to get a clear understanding of this without a clear and open line of communication.

Let me start by apologising for the simple fact that I have caused offence. Sorry. That's not enough, I know, but I'd better start, especially since I have been ignoring this reply for nearly two weeks. I'm sorry for that too. Long hours at work over the past few months, and then a vacation spent looking after a family member have meant that I've let MyPaint work slide too much recently.

FYI, I consider myself to be bound by our [Code of Conduct](https://github.com/mypaint/mypaint/blob/master/CODE_OF_CONDUCT.md) as much as any other maintainer or contributor. We do not tolerate abusive, discriminatory, or harassing behaviour, and take it upon ourselves to be welcoming and respectful, and to accept constructive criticism.

**Comment by achadwick** [comment]
We call `locale.getdefaultlocale()` in a couple of places, but one is just for debugging. I'm trying to dissuade myself of the notion that it's OK to call the other one to get a language as a fallback. As you've correctly pointed out, it only gets the _Region and Language → Formats_ setting. However, for Win7 Professional or Win7 Enterprise/Ultimate users without language packs, it's the only reasonable way for a user to influence software like MyPaint.

Using it to derive language could be made conditional on Windows version.

Looking at the code, I'm pretty sure that the order is wrong if we're going to use it as a fallback (and there's a comment to that effect). Let's let chosen UI language override any story we try to infer from the user's formats settings.

**Comment by wareya** [comment]
Thanks for the apology.

Making locale.getdefaultlocale() the fallback instead of the other way around seems like a good idea. It's the closest thing to a UI language on posix-like platforms anyway.

**Comment by achadwick** [comment]
The UI languages (user, then system if different) are now the default fallback, followed by anything gleaned from the Formats settings. Both can be overridden by POSIX-style LANG and LANGUAGE if they are defined.

Looks like I'm a case where the Formats language is set differently to the UI language too! There's only one variant of English available for the UI in Windows 7, and it's US English. But every English speaker outside the US fixes the date order.

**Comment by achadwick** [comment]
The right fix for this is probably to have UI for selecting the language you want MyPaint to appear in, and use the setting early. And now I have an incentive to fix it ☺

The tricky bit will be getting the startup order right - prefs have to be loaded before doing anything related to gettext init for this to work.

**Comment by jplloyd** [comment]
Language settings are now available in master - there is a dropdown menu in the preferences under the "View" tab. The startup order did indeed require a bit of refactoring.

[Windows build](https://ci.appveyor.com/project/achadwick/mypaint/build/job/62kj1tw7av0vw57c/artifacts)
[Linux appimage](https://github.com/mypaint/mypaint-appimage/releases/tag/continuous)
