### ISSUE TITLE
Packaging script should be more configurable for other CHOSTS and install locations

### ISSUE THREAD

**Issue by alown** [mypaint/mypaint#799]
I was putting together a new package manifest for my distribution for trunk, as you have moved off of Scons, and ran into a few items that need to be exposed from the setup.py to be able to usefully hook in at the distribution level, where these may be being cross-compiled etc.

1) pkg-config is build-target dependent, (normally indicated by prefixing) ($CHOST equivalent)
2) Install may be using any prefix, but the root may not be "/" ($DESTDIR equivalent)

I have put together a commit for each alown/mypaint@953c4f257277f284e3f0bac9dca87ffa9ef0a177 alown/mypaint@d59c8228f9c8f3c50ad07ccfd1ffa6a395a06d7b which simply exposes these from the setup.py in environment variables I can set to override. Not sure if you would rather go about this a different way, or if I should just be sending in PR?

Ali

**Comment by QuLogic** [comment]
Why differ from autotools/cmake/meson? Use `PKG_CONFIG` for custom pkg-config and `DESTDIR` for the root.

**Comment by alown** [comment]
These could indeed be changed if we agree that using environment variables (rather than flags) is the correct way to pass this information in? Does it make sense to have '--prefix' as an argument to install, but use DESTDIR as an environment variable?

(I chose HOST, as one can use that or --host to tell configure the compiler prefix string, and ROOT as the setup script already referred to the destination directory as root)

**Comment by achadwick** [comment]
It's setuptools, so setuptools `--root` and `--prefix` apply.

**Comment by achadwick** [comment]
Sorry, flailing with the touchpad there, and I accidentally closed it.

I've just realized that this is for `managed_install` and `managed_uninstall`. Those commands are user-facing tools, and a temporary hack till we can get pip installation management working. This last bit relies on having some Python lib installed to the normal search path, at which point it can get its egg-info in the right place, but we will need to install all the code into the `mypaint.lib` and `mypaint.gui` namespaces. Just `lib` and `gui` are way too generic for global installs.

Package developers should be using the one-way `install` command, because they know what they're doing, and because yum/pacman/uninstall.exe/apt will be doing the cleanup :smile:

Right now, I don't think regular users need to set anything other than `--prefix` for `managed_*` commands.

**Comment by achadwick** [comment]
The right way to set compiler options is using the environment vars, I believe. That's one of our major reasons for dropping SCons after reading the diatribes from the Arch and Debian folks.

Before I close this, does just using `python setup.py --root=A --prefix=B install` solve the problem for `trunk`? [er, I'm not sure what "trunk" is, sorry]

**Comment by alown** [comment]
Using the `install` target with --root and --prefix commands does perform as expected, so resolves any need to adjust `managed_install`

As for the other half of this issue: changing which `pkg-config` binary is called, seems like an environment variable is preferred. How about alown/mypaint@94b1561082c98537ec81ce8ffa7bc4ac92bc32a3 ?

(Sorry, I switch between SCMs too much: I meant to say `master` instead of `trunk`)

**Comment by jplloyd** [comment]
@alown
Support has been added for the pkg-config configuration in b510bfc3c5f580104209746994bebb85025bcecb

Same approach as you suggested, but factored out since pkg-config is called in two places now.
