### ISSUE TITLE
travis-ci tests being skipped

### ISSUE THREAD

**Issue by briend** [mypaint/mypaint#832]
24 of 29 tests are being skipped
python setup.py test
...
Saved and reloaded documents look identical ... skipped 'matplotlib not available'
...
test_0x10 (tests.rendering.Scroll) ... skipped 'no GUI or unable to import TDW class'

**Comment by achadwick** [comment]
This is expected because not every environment we run the tests on has the DISPLAY variable set. Travis is one such environment.

The conformance tests are sometimes dependent on the HEAVY_DEBUG setting too.

PRs to improve the test coverage are welcome, but skipping tests is not a bug: it's a feature.

**Comment by briend** [comment]
That makes sense, and I guess I really shouldn't trust those green check boxes so much :)
