### ISSUE TITLE
Pick H,C and/or Y from canvas

### ISSUE THREAD

**Issue by briend** [mypaint/mypaint#835]
Demo here:
https://www.youtube.com/watch?v=ZLt8DrzDUlc&lc=z12bezzhnvayfpimx23ahhbydqizyr4do
I made a branch here
https://github.com/briend/mypaint/tree/pickHCY

The idea is, say you have some colors on your canvas.  You want a yellow color that sorta matches (coordinates with) a blue color on the canvas.  You can just pick any yellow color from palette and then alt+r and/or shift+r to modify the yellow color to have the same chroma and/or luma as the blue on the canvas.  Kinda cheating!

Or maybe you already have a scene on your canvas and you want to paint a section that has diminished chromacity and a brighter luma (like something in the distance).  So you might be able to paint one element in the distance and use that as the springboard/model to pull foreground colors into the background space by grabbing foreground colors (R) and then plucking the C and/or Y (alt+R, shift+R) from your distant model.

Or maybe your paint brush already has a color that you like, but you want to change the hue of it to match something else on your painting, but preserve the chroma and luma.  Just press Ctrl+R now instead of trying to rotate the hue wheel around to the approximate color.

Or maybe this doesn't make any sense at all :-D

Making color ramps like this is really really simple and flexible by just using the hot keys to grab the luma and chroma of the previous swatch to paint the next one.  Previously it would be just about impossible.
![screenshot from 2017-07-12 18-48-57](https://user-images.githubusercontent.com/6015639/28147109-1c9b4a48-6733-11e7-8293-017217610939.png)

Here's a youtube clip demonstrating a bit:
https://www.youtube.com/watch?v=_YySR2PQJ30

**Comment by achadwick** [comment]
Sort of like the idea, but I think it should be integrated with the existing colour picker somehow. There's a lot of duplicated code and commented-out stuff in that branch too.

Would you mind moving the branch to your personal area and doing a PR for this one? I don't want to clutter up the main repository with test code branches.

**Comment by briend** [comment]
Sure, I just moved it.  I thought it'd be easier to get some help on it if it was in the main repo, and I didn't want to clutter up the PRs! ;-).  I totally agree it needs to be just colorpicker.py with some paramters but I probably need some help extending that.

**Comment by briend** [comment]
I think that commented out stuff was already there.  Of course it's impossible to tell because I made whole new files :-(.   The bulk of what I changed is on lines 88-99.  I just switcharoo the color components:

https://github.com/briend/mypaint/commit/8ae8030320527ef1703164e1aeaea0b434a639f8#diff-02ffd899939d835b33a40aeff7f635f4R88

**Comment by briend** [comment]
There is a problem though...   colors without any chroma will flip the hue to red if you grab just Chroma.  Likewise, colors with chroma that are pure black or pure white will also flip the hue to red if you grab Luma.  This kinda already happens with the current color picker but not as noticeable.

I wonder if we could check for that situation and preserve the previous hue somehow in these situations

**Comment by briend** [comment]
So, I'm looking into adding parameters to colorpicker.py.
I guess I should keep add a parameter to ColorPickMode and just have ColorPickModeH C and Y call that with a parameter (all in colorpicker.py).  It doesn't sound like gtk-action allows parameters so is this the way to go?

**Comment by 0ion9** [comment]
Just throwing my ideas into the hat here:

* Personally I would use GPick's variations tool to do the particular task you show. However, typically I view same-value colors as a mistake (IMO all basic spot colors should sort into a value scale that's well segmented -- all colors having a noticably different value. This may just be my pixel art background speaking, however)
* I consider the diminished chromaticity or similar hue scenarios more generally applicable than the value scenario.

* Have you considered the possibility of a weighted combination of old and new colors? Having a GUI with a checkbox and a slider 0%->100% for each component? The checkbox would be equivalent to treating the value as 0% (channel is not factored in at all). Then you could have a single action that just picked with this weighting, rather than one per channel. I'd consider this scenario -- mixing some but not all of an existing color into your current color -- as one of the most generally common.

* Just my opinion, but I'd suggest that picking two channels and leaving one is going to be a more common task than the converse. If we stayed with a three-hotkey setup, I think making them 'pick everything BUT channel X' might be more practical.

**Comment by briend** [comment]
I didn't know about GPick, that looks pretty cool.  But, it would take a lot more steps and planning, creating a palette even?

I agree about lightness not being a great thing to pick when dealing with different hues-- but HCY is "supposed" to address that issue.  In the demo the columns should be "perceptually" uniform in brightness, whereas if I used HSV they would be very different.  Here is GIMP's conversion to greyscale based on "lightness":
![image](https://user-images.githubusercontent.com/6015639/28197298-c487793e-680a-11e7-9d98-7acf97fe8ef7.png)

And here is GIMP's conversion to greyscale using the "luminosity" method.  For some reason the right two columns worked out just about perfectly but the left two didn't... maybe HCY isn't perfect or I messed up something.  It's still a lot more uniform than the previous image, though.
![image](https://user-images.githubusercontent.com/6015639/28196738-69abbb22-6807-11e7-98b6-4f3a7c8d402e.png)

I like your weighted mixing idea, that would be seriously slick.  You'd be able to tap the R key a bunch to incrementally mix in the color (in whatever component ratios you described with the sliders).  I wonder what would happen when you drag the pick brush though, it would probably sample way too often unless you kept the sliders at like 5% (or changed code to sample less).  

Picking two channels is exactly what I was doing (with alt-r then shift-r) in the demo, C and Y to match the previous swatch.  So you're probably right it would be very common.  BUT, if we always pick two channels that would totally preclude picking *just* chroma, which is possibly the most exciting thing about this :-)

**Comment by 0ion9** [comment]
> I didn't know about GPick, that looks pretty cool. But, it would take a lot more steps and planning, creating a palette even?

Less steps to make the palette (much, much quicker IME), add a few steps to get the generated palette back into MyPaint. Either by editing an existing palette and getting MyPaint to reload, or by dropping individual colors on MyPaint.

If you set up a scratch palette ahead of time, it's pretty easy.
But if you don't care about factoring your palette carefully (== have to plan anyway), then yeah, on-canvas is probably more approachable.

> but HCY is "supposed" to address that issue.

Your results look right, because HCY is better than HSV, but still not 'correct'. Even LCH, which should be more reliably 'correct' than HCY, isn't truly accurate to how we see things. Nobody has actually solved this properly yet, just polished off the worst rough bits.

(The world probably would need to standardize display reflectance characteristics just to start properly addressing this)

> mixing in too fast

Yeah, excessive speed of mixing was a concern, but the idea was premised on it too (hold key and move, wait until 'enough' color is mixed in). If floating point rounding errors don't prevent it, using an exponential scale would help ( eg halfway point on scale -> 0.5**2 == 25% weight).

An alternative would, I guess, use motion to control how much color got mixed in (so the action would pick the color once only, and display the mixed color at the ratio determined by motion distance.) That would be incredibly comfortable IME, but obviously would take more effort to implement.

**Comment by briend** [comment]
> But if you don't care about factoring your palette carefully...

That would be me, and probably a lot of other lazy people.  But I do want a coherent limited palette. I just want it now now now :-)

> pick the color once only, and constantly display the mixed color at the ratio determined by motion distance.

This sounds a lot like the smudge_lock setting I made in my smudge tweaks branch.  I wanted to pick the canvas color once, then mix it w/ brush color via pressure or other settings like distance (stroke) without re-sampling the canvas at all.  Sounds like what you described but on the brush itself.  Sort of a shortcut alternative to using a palette mixing scratch area.  Sounds cool :-D

I don't want to bite off too much at once though.  I'm going to try to clean this branch up and simplify it, and I need to integrate the Hue and (I just realized) Chroma preservation between color picks.  Not only will your hue "reset" to red when C is 0 or Y is 1 or 0, but your chroma will reset to 0 when you have a luma of 0 or 1, so that's bad, but should be simple to handle.

**Comment by briend** [comment]
@0ion9 I implemented a distance-based mixing method as you described.  It even uses a pigment model  that is sort of like real paint.  Thanks!!

> An alternative would, I guess, use motion to control how much color got mixed in (so the action would pick the color once only, and constantly display the mixed color at the ratio determined by motion distance.) That would be incredibly comfortable IMO, but obviously would take more effort to implement.
