### ISSUE TITLE
MacOS Y-Tilt values are reversed

### ISSUE THREAD

**Issue by briend** [mypaint/mypaint#851]
Can anyone else confirm this?  Launch MyPaint (MacPorts, Xquartz), Test Input Devices.  Then compare the X and Y tilt values between a Linux/Windows host and a  MacOS host.  X tilt is consistent but Y tilt is reversed.

This doesn't affect the actual Tilt result (declination) but it does totally mess up Ascension.  If your brush is using the new offset settings that use ascension, they will be very broken.  We might want to consider adding a preference to flip the values (ytilt =* -1 ).

Possibly relevant: https://github.com/thinkyhead/TabletMagic/issues/9

**Comment by achadwick** [comment]
Pretty corner-case while we have no regular macOS testers.

It goes without saying that it is ultimately the responsibility of GTK/GDK and the tablet drivers to get this right, not ours. We have however implemented little fixes where it's obvious what to do: value clamping, de-NULLing, input sequence degapping interpolations, that sort of thing.

I tend to be pretty cautious about adding in too many settings for this sort of thing. Let's prove the need for it first.

**Comment by briend** [comment]
I need to sit down and compare all three platforms.  At this moment I'm not even sure if Windows and Linux report the same Y tilt direction.

**Comment by briend** [comment]
Ok I verified with xinput that the values are inverted, which contradicts the developer's guide here (http://www.wacomeng.com/mac/developers%20guide.htm).  Linux is fine, Windows is fine.  I've submitted a bug report to XQuartz because I can only imagine that is where the issue is?  Or do you think GDK should handle exceptions like this?

**Comment by achadwick** [comment]
@briend
GDK can't know for certain whether whether any value it's getting is flipped or not; its backends have to trust their underlying windowing/driver/OS layers. So it's more that there's nothing the GDK people can do about this unless the platform is documented as doing that all the time: note that (speculation!) the direction of the display Y axis could plausibly vary from system to system, and an earlier bug caused by such a thing could be baked into an API.

GTK/GDK is supposed to provide the same client interface on all platforms, so a tracker bug could be raised there too, just in case, and to keep them informed.

Please be sure to link all the bugs together so that people can find them more easily too. This one isn't us though. We don't need to keep issues open in our tracker if they're definite upstream bugs, and the bugs are linked from here.

Thank you for chasing this one :smile:

**Comment by briend** [comment]
Thanks @achadwick 
Here's the bug submitted to XQuartz:

https://bugs.freedesktop.org/show_bug.cgi?id=102471
