### ISSUE TITLE
Free the Modifier keys

### ISSUE THREAD

**Issue by briend** [mypaint/mypaint#852]
If you delete all the button mappings so that Shift, CTRL, and/or ALT do nothing at all, you still can't use them while freehand drawing.  Pressing any of these keys will interrupt your freehand drawing stroke even though they don't do anything.  This aspect seems to be a bug.

I would like to use the modifier keys to allow real-time control of brush settings like hue, saturation, etc but right now only "first class" single-key mappings support that.  It seems unfair that Color Picker and Line Mode monopolize the usage of these modifier keys, doesn't it?

**Comment by achadwick** [comment]
There may still be some old code from the monolithic (pre mode stack!) input handling stuff in gui.freehand. 

Can you track down where this is coming from and maybe test out a fix of your own devising please? I have very little time to spare at the moment.

I think https://github.com/mypaint/mypaint/blob/fad5f81c27af14e9324c89d227c5569dc918bcb3/gui/freehand.py#L440 may well be the culprit here, but I'm not sure :pensive: That'll be where to start looking, at least.

**Comment by briend** [comment]
Thanks for the lead, @achadwick.  And thanks for all the work you've put into this project!
