### ISSUE TITLE
Brush paints without input with wrong settings

### ISSUE THREAD

**Issue by cromachina** [mypaint/mypaint#863]
#### Description of the problem
Some non-obvious brush settings cause the pen to paint without input, specifically "Hardness" and "Pixel Feather", but not "Stroke Threshold".

#### Basic system details

MyPaint version: 1.3.0-alpha+git.70ce73d9
Operating system: Windows 10

#### Steps to reproduce

1. Use the attached brush. [brushes.zip](https://github.com/mypaint/mypaint/files/1309400/brushes.zip)
2. Observe that it begins painting without clicking or pen pressure.
3. Adjust the "Stroke Threshold" setting and observe no difference in this behavior.
4. Increase both the "Pixel Feather" and "Hardness" settings to prevent it from painting without input. The descriptions for neither of these settings indicates such a behavior should occur, whereas "Stroke Threshold" does.

**Comment by briend** [comment]
"Opacity Multiply" is what you probably want to use to stop painting.  Check out the description on that one.  Note you have the base value for that 1.0, so basically you are always painting.  You should probably have that set to 0 for the base value, and assign pressure some value.  When you adjust pixel feather or hardness you can essentially make your stroke disappear, but it is still painting.  I guess it is always painting, really.  Funny, huh?

The Stroke Threshold description tries to make it clear that it affects the "stroke input" only. So if you want to use the stroke input for something you can set the threshold to something >0 so that the stroke starts with pressure only.  But "stroke" has nothing to do with whether you are painting or not.  I know, there are definitely some confusing bits here.

**Comment by cromachina** [comment]
That is certainly confusing, but clears up my issue. I feel that there should be a single checkbox that says "Prevent drawing when no input pressure or mouse click", as I can imagine 99% of brushes do not want that, or at least a glaring sign that points to "Opacity Multiply".

Thanks for the help!

**Comment by briend** [comment]
A checkbox would make things simpler, but at the same time more limiting.  Notice there really aren't any checkboxes in the brush settings, almost everything can be tweaked with inputs, etc.  That's what makes it so flexible.  I think what we need is better tutorials, etc.  I'll go ahead and close this issue.
