### ISSUE TITLE
Snapping MyPaint to sides window doesn't work in XFCE

### ISSUE THREAD

**Issue by GroundJet** [mypaint/mypaint#865]
#### Description of the problem
When the MyPaint window is dragged to the top it maximizes if it isn't already, but when dragged to either corners of the screen it doesn't snap to left or right.

#### Basic system details
MyPaint version: 1.2.0+gitexport.f62444e
Operating system: Xubuntu 17.04
Desktop environment: XFCE 4.12

#### Steps to reproduce
1. Start MyPaint
2. Drag the window from its titlebar to either left or right of the screen
3. The window doesn't snap to either side

#### Backtraces or error messages
When launching the program from terminal these messages are shown:
```
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix u'/usr'
INFO: lib.i18n: POSIX: LANG='en_IN'
INFO: lib.i18n: POSIX: LANGUAGE='en_IN:en'
INFO: gui.device: New device 'Wacom Intuos S 2 Pad pad' (GDK_SOURCE_PEN, axes:6, class=X11DeviceXI2, vendor='056a', product='033b')
INFO: gui.device: New device 'Wacom Intuos S 2 Pen stylus' (GDK_SOURCE_PEN, axes:6, class=X11DeviceXI2, vendor='056a', product='033b')
INFO: gui.device: New device 'SynPS/2 Synaptics TouchPad' (GDK_SOURCE_MOUSE, axes:4, class=X11DeviceXI2, vendor='0002', product='0007')
INFO: gui.device: New device 'Virtual core XTEST pointer' (GDK_SOURCE_MOUSE, axes:2, class=X11DeviceXI2, vendor=None, product=None)
INFO: gui.document: Initialized background from u'/usr/share/mypaint/backgrounds/10_soft_yellow.png'
WARNING: gui.keyboard: Ignoring keybinding for '<Actions>/BrushModifierActions/BlendModeMenu'

(mypaint:12820): Gtk-WARNING **: Theme parsing error: <data>:5:50: The style property GtkMenuBar:internal-padding is deprecated and shouldn't be used anymore. It will be removed in a future version
INFO: lib.document: Using u'load_ora' to load u'/home/user/.local/share/mypaint/scratchpads/autosave.ora' (kwargs={'feedback_cb': <function gtk_main_tick at 0x7f3e18d9a6e0>})
INFO: lib.document: load_ora: u'/home/user/.local/share/mypaint/scratchpads/autosave.ora'
INFO: lib.document: 0.093s load_ora total
INFO: gui.filehandling: Loaded scratchpad from u'/home/user/.local/share/mypaint/scratchpads/autosave.ora'
WARNING: gui.accelmap: Not listing '<Actions>/DocumentActions/RotateLeft' (no tooltip, fix before release!)
WARNING: gui.accelmap: Not listing '<Actions>/DocumentActions/RotateRight' (no tooltip, fix before release!)

(mypaint:12820): IBUS-WARNING **: Unable to connect to ibus: Could not connect: Connection refused
/usr/lib/python2.7/dist-packages/pygtkcompat/pygtkcompat.py:180: TypeError: Passing arguments to gi.types.Boxed.__init__() is deprecated. All arguments passed will be ignored.
  rect = Gdk.Rectangle(0, 0, 0, 0)
```
I have no idea how to debug something other than running the program through `strace` and hoping to understand something, so any instructions will be greatly appreciated if more error codes or debugging is necessary.

**Comment by achadwick** [comment]
Hi - thanks for the report!

Can reproduce, but only on smaller monitors. In that case, the only issue here is the normal xfwm4 behaviour. I think the variation has to do with minimum window sizes for the app, but I may be wrong.

Xfwm calls this behaviour "tile" rather than "snap", apparently.

* If you are using a 1280x1024 monitor, you cannot tile MyPaint with a sidebar to the sides or corners of it.
* If you are using a bigger monitor (I have a 1920x1080 monitor here), you **can** tile to the sides and corners.

I am using Xfwm 4.12.4-1 from Debian testing.

Thanks for the report. I don't see any pressing urgency for MyPaint to fix this. MyPaint needs a reasonably large canvas area to draw on, and so we request this. Monitor pixel sizes are increasing rapidly at present, and 1080p ("Full HD") may be considered rather small fairly soon.

You may wish to work with the Xfwm team instead on getting the snapping issue resolved. I'm not sure I completely understand it, but I occasionally notice it with other apps: most notably, Xfce's graphical settings editor. That that's an odd case: the window can be resized smaller than 1/4 the screen size on 1280x1024. Huh.

**Comment by GroundJet** [comment]
Thank you so much for taking time to give such detailed review, I already plan on upgrading the system so if the resolution is the limiting factor than better not bother with a fix.
