### ISSUE TITLE
There is a problem that needs to be solved 

### ISSUE THREAD

**Issue by dsvds** [mypaint/mypaint#871]
There is a problem that needs to be solved in the program for studio owners
 1- add Clone tool  and You must activate (set the origin point) using the right mouse button instead of ctrl 
2 - zoom The zoom must be activated using the mouse roll
 + Enable zoom orientation towards the tool point

According to my experience as a photographer I used many programs such as Photoshop Corol Drew This change will benefit Mac users who lost Corel Drew on Mac

**Comment by achadwick** [comment]
Hi there - thanks for reporting!

Unfortunately I can't take this report any further because there are too many problems bundled into this single issue. This issue tracker only operates effectively when there's a single problem in each issue thread. Please can you split out each of the following topics, and make a fresh issue report about each one?

* The request to add a clone tool.
* The request to make zoom go towards the "tool point" (you need to clarify what a "tool point" is, do you mean the "mouse cursor" or "pointer"?)
* The request to make zoom acivated by the "mouse roll" (do you mean the "mouse wheel"?)

You need to give each one a better title than "There is a problem that needs to be solved".

Read the [issue reporting guidelines](https://github.com/mypaint/mypaint/wiki/Reporting-Bugs) before you split these topics out, and don't forget to search the tracker just in case someone has already reported the problem.

You can mention this original issue as `#871` in your split-out issue reports. However, because we cannot deal with piggybacked issue reports sensibly and in a timely fashion, I am closing this original report.

Thanks for the feedback, and I hope our (somewhat strange) policy isn't too scary. We only ask that topics get split up so that they can be dealt with and closed meaningfully.
