### ISSUE TITLE
Autohide of the interface in fullscreen mode doesn't work (Win 10)

### ISSUE THREAD

**Issue by zb13y** [mypaint/mypaint#874]
#### Description of the problem
 
1. Autohide doesn't work while drawing (both - pen and mouse). So it just doesn't work, reason - user always draws.
2. Autohide doesn't work while moving cursor etc., so most of the time.
3. Autohide works only when user rises pen over tablet, and leaves mouse. Mostly never happens.

So autohide just doesn't work, triggers are wrong. Maybe it is only in windows.

#### Basic system details

MyPaint version: [1.2.1+gitexport.bcf5a28d (Stable) and last alpha 1.3.0 from AppVeyor]
Operating system: [Windows 10x64 1703 15063.674]
Tablet: Wacom Bamboo Pen & Touch (CTH-470)

#### Steps to reproduce

1. Start MyPaint
2. Tick "Hide Controls in Fullscreen" 
3. Go to fullscreen
4. Draw and move cursor (interface doesn't hide)
5. Rise pen or leave mouse
6. Interface hided

**Comment by briend** [comment]
This is what I noticed, too.  There might be a different issue though; I noticed that if I hit TAB to hide the panels right at the beginning of a stroke, part of the stroke can get messed up and offset by the width of the panel that was just hidden.  So, with that in mind, making sure the stylus is *away* from the drawing pad might be a work-around for that issue.  This is just a guess.

**Comment by achadwick** [comment]
This is intentional and it has been like that for a long time. I figured that it would be mega distracting if the interface started changing around while you were actually drawing, so the timers that control show and hide are turned off while the cursor moves within the canvas. For the automatic hide to work, the cursor must be un-moving, and positioned over the canvas for a short while.

The same is not true when you move the cursor off the main canvas and onto e.g. a sidebar. Then the interface stays open. Hiding it while you are clicking/dragging in a sidebar would be _even worse_!

What do people expect here?


@briend 
> hit TAB to hide the panels right at the beginning of a stroke, part of the stroke can get messed up and offset by the width of the panel that was just hidden. 

I'm not surprised, given how it's implemented! If the sidebar/toolbar/statusbar containers were implemented as the overlay children of a GtkOverlay, with the canvas being the main child, all would be quite different.  However, GtkOverlay was not available back when `gui.workspace` was written.

**Comment by briend** [comment]
Given all that, maybe this issue should be closed and the other issue #870 could be re-opened if my idea of adding another timer has merit?

**Comment by zb13y** [comment]
> I figured that it would be mega distracting if the interface started changing around while you were actually drawing
Ah... so autohide can be annoying. I haven't thougt about it. Not bug, feature. Then it can be closed.

**Comment by briend** [comment]
Re-opened the other issue #870.  I think behaving like Firefox does in full screen might be a good option
