### ISSUE TITLE
MyPaint is very slow and strokes. Can barley draw

### ISSUE THREAD

**Issue by LadyLilligant** [mypaint/mypaint#876]
[⚠ This tracker is for fixing and improving MyPaint.]
[☞ Use our Community Forum for support queries, or to suggest new features: https://community.mypaint.org.]
[☞ Please search before posting to avoid duplicates.]

#### Description of the problem
I 

downloaded the correct version of my paint and its very slow with strokes and slow overall 
[✍ Fill in this section with a clear description of **ONE** problem.]
[☞ Stay on topic. Separate problems go in separate issues.]
[☞ Read https://github.com/mypaint/mypaint/wiki/Reporting-Bugs first.]
[⚠ If you don't give us enough detail to allow us to reproduce your issue, we cannot help and your report will be closed.]
[☞ Check the title is short but useful. It should echo this description.]
[☞ Pictures and videos help us a lot. You can paste screenshots.]

#### Basic system details

MyPaint version: [✍ 1.2.0 stable, 1.2.1-beta.1, git revision NNNNNNN, …]
1.2.1
Operating system: [✍ Debian 8.3, Ubuntu 16.04, Windows 7, …]
windows 7
Desktop environment: [✍ GNOME, Xfce, …]

#### Steps to reproduce

[☞ Tell us how to reproduce the bug in clear, numbered steps.]

1. Start MyPaint
2. i start trying to draw and its very slow
3. [✍ third step]

#### Backtraces or error messages

```
[✍ Paste any error messages here between the ``` lines.]
```

**Comment by odysseywestra** [comment]
Closing issue since user didn't fill out the issue template, plus having a really broad statement doesn't really help us figure out what is going on. However don't fret. I suggest that you fist post on our Community Forums at https://community.mypaint.org. That way we can help you diagnose the problem and then post here once we have a more solid issue we can address.
