### ISSUE TITLE
Cursor not accurate

### ISSUE THREAD

**Issue by gbr2060** [mypaint/mypaint#882]
[⚠ This tracker is for fixing and improving MyPaint.]
[☞ Use our Community Forum for support queries, or to suggest new features: https://community.mypaint.org.]
[☞ Please search before posting to avoid duplicates.]

#### Description of the problem

I'm having problems with the cursor and the paintbrush itself. When i try to draw a line for example, the line starts with a gap from the cursor.
![screenshot_1](https://user-images.githubusercontent.com/34604316/34072256-f67b264a-e26a-11e7-95f9-ff05f10f67d7.png)

When i execute the Test MyPaint-w64's tablet support, the same issue happens.

#### Basic system details

MyPaint version:  1.2.1 stable
Operating system: Windows 10]
Desktop environment:

#### Steps to reproduce

1. Start MyPaint
2. Start to draw
3. The gap appears instantly

#### Backtraces or error messages

```
```

**Comment by achadwick** [comment]
@gbr2060 
I need to know more about the hardware setup you're using. Dual screen or HiDPI doesn't work very well on Windows.

Please can you test with a more recent alpha build and see if the problem is still happening?

1. Go to <https://ci.appveyor.com/project/achadwick/mypaint/branch/master>.
2. Click on the environment line for your system with `MSYSTEM=<MINGW64 or MINGW32>`. Normally you want the 64-bit build.
3. You'll see a job log for the build, but it can be ignored. The installers and standalones are on the ARTIFACTS tab.

**Comment by achadwick** [comment]
Hi there - thanks for the report!

There's not quite enough information in your original report to move this issue forward, sadly. Please read the [bug reporting guidelines](https://github.com/mypaint/mypaint/wiki/Reporting-Bugs). We need more information about your system, and more information about your MyPaint installation if this report is going to be useful to us.

**Comment by achadwick** [comment]
**TRIAGE NOTE:** requested info not supplied + unreproducible.

This issue should be closed after a couple more weeks of inactivity.

**Comment by jplloyd** [comment]
A couple of weeks (~70) have passed, I don't think the requested information will be provided.
