### ISSUE TITLE
Cleaning up the Issue Tracker

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/mypaint#896]
Just think it's time for us to start cleaning up our issue tracker. One thing we could do is look at the inactive issues tag with [Enhancement](https://github.com/mypaint/mypaint/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement) and move them to the Feature Requests on our [Community Fourms](https://community.mypaint.org/c/feature-requests) or just close them. This is something I can do.

**Comment by briend** [comment]
Yeah, lots of old stuff.  Some good issues though too, I wouldn't want to lose all those ideas...  Maybe before closing them we label them as "stale" so it's easy to find them and differentiate them from actually completed/closed issues.

**Comment by nekohayo** [comment]
Instead of throwing stuff into a "second system" (which creates its own set of problems I think), one way I deal with this in projects I manage is to create a "patch-or-wont-happen" tag (label), and you make it VERY clear that issues that have this label are issues that:
* are desireable by the maintainers (i.e. not "wontfix" issues), but but that REQUIRE someone new to come in and provide a patch/branch for it, otherwise it's "never going to happen because we don't have time".

Then you tag every such feature request that isn't "critical" or "currently or soon to be worked on by existing maintainers", and then you tell your maintainers to exclude all issues with that tag from their view (same for "needinfo" and "low-hanging-fruit-for-newcomers") so that they can focus on what they can personally commit to.

**Comment by odysseywestra** [comment]
I understand your reasoning. My goal is to try to get the community involved in the direction they would like to go and I think Discourse is the better platform at the moment mainly due to being extensible, easy barrier of entry, and being able to actually allow the users to edit the scope of the feature requests. 

The voting feature actually is pretty helpful in gauging the direction the community would like MyPaint to go. Plus since there a limited number of votes depending on your trust level, it allows users to think about what features they want too. Easier barrier of entry is another factor since I don't expect every user of MyPaint is going to want to create a github account just to comment on issues. This is why the forums takes advantage of social logins to make it easy as possible for them to get involve in the discussion and have an input. Then last is more of a personal favorite, but discourse has the ability to treat the first post as a wiki. So as long as you have a trust_level of 2 I believe, it can be edited to adjust the scope of the feature request. Is this the perfect solution? No, but I think it about as close as I can do to at least get the community involved in the discussion.

There are a few feature request such as #31 that will probably be an exception to the rule since it the most requested feature out of everything. Plus some users have a passion about having selection tools even though technically they are really not required to actually create art, it just makes it easier. Oh well. ^^'

Oh this is the same reasoning I encourage users to first open support tickets on the community forums first before coming here.

**Comment by AesaraB** [comment]
There isn't much of a developer community for MyPaint anymore, but I am labeling as much as I can. I hope this more or less addresses this issue for the current state of the project.
