### ISSUE TITLE
[Feature request] - Add the Ability to Manually Enter Values wherever Sliders are.

### ISSUE THREAD

**Issue by AtsusaKaneytza** [mypaint/mypaint#898]
(EDIT: Sorry for messing up on the submission guidelines, I've ported this over to the community site: https://community.mypaint.org/t/feature-request-manually-enter-values-for-brush-layer-shortcut-increments-and-other-numerically-based-settings/1127 )

1.) Most/all of the settings for brushes are sliders, but don't have the option of for manually inputting values. This can be inconvenient for setting more "absolute" numbers, like "1.00" for a setting instead of having the setting at "0.87" or "1.33" And while having the slider is useful for "tweaking" as you're editing a brush, having the option to enter a number is useful too. It'd also be nice for being able to enter a value that's just right, instead of having to "find" it again by messing with the slider.
A workaround for this is increasing the brush editor window so that the slider also gets bigger, and you have more increments. But that's a lot of extra steps for fine-tuning some brush settings.

2.) In the system preferences, we could specify the amount that using the increase/decrease shortcuts for layer or brush opacity affects the brushes. Or even have it as an option for a per brush basis. To customize it for each brush, maybe add it as an optional setting. Otherwise, have it as a default value in the preferences.
(Also worth noting, but in the latest versions, unless you have the brush editor open, you can't see the actual values of the brush settings, unlike the old versions of MyPaint, which I find a bit disappointing, but that's another issue.)

I hope I haven't crammed too much info into one issue, but I checked the tracker and didn't see a report for this. (If I did miss it, sorry)

Attached are some of my ideas for how it could look in the software. Sorry for the clunky photoshops, but I hope it gets the point across.
![image](https://user-images.githubusercontent.com/8382492/36380310-633f652a-1547-11e8-8174-561b37b9b2f6.png)
![image](https://user-images.githubusercontent.com/8382492/36380328-7368716c-1547-11e8-9d33-2a1ea9728f5b.png)
![image](https://user-images.githubusercontent.com/8382492/36380335-7a2b6c84-1547-11e8-8ddd-5325ac3698ce.png)
![image](https://user-images.githubusercontent.com/8382492/36380360-968b5d6c-1547-11e8-8b7f-50d9a9e6041a.png)

All this stuff isn't essential, but more for the artist's quality of life.
*Specs:*
MyPaint version: 1.2.0 stable, 32-bit
Operating system: Windows 10, 64-bit
Devices: Acer Laptop with a Yiynova MVP10U screen tablet, Microsoft Surface 3 (non-Pro)

**Comment by achadwick** [comment]
The Keys editor is too generic for what you want. IMO, sensible defaults are good enough for the size and opacity key increments. :-1:

The setting will be confusing if it brush-specific. :-1:

Being able to type in values into the brush editor: :+1: 

Being able to type in an opacity value into the layer properties dialog: :+1: if it can be kept simple.

![image](https://user-images.githubusercontent.com/61299/36768382-d28e4a40-1c36-11e8-86ac-eae04f91e5bb.png)

**Comment by achadwick** [comment]
↑ That's the 3.0 alpha build, btw.

**Comment by fbck** [comment]
Increment amount sliders don't have to be in keys, but it actually would make sense for them to be there, to change the parameters of actions to which keys can be bound, down to making different actions with different and specific amounts of increment. Right now the increment amounts are invisible and unclear, on top of them being unchangeable.
It won't be confusing. 'Increase/Decrease value by N'. If anything, the current names of some of those actions, like "Decrease/Increase Brush size", are more confusing and ambiguous than that. It's not clear by what amount would a parameter change, and to find that out at all, one would have to open the Brush Settings Editor and look at the way values change. For brush sizes it's 0.30. Okay, cool. Yet when I scroll over sliders, it changes by 0.10. And, while Brush size changes linearly, Opacity changes logarithmically or something, so it's all over the place. It's not confusing at all, even in that picture, actually, the lack of this setting is more confusing than anything.

Value sliders are annoying. There's a certain degree of expected terribleness from slider controls, but those sliders actually overcome that boundary, being even more terrible. It's surprising how the removal of visible value ruins everything so much, that it's borderline unusable.
- Actual values of anything are invisible. Sure, they're visible in Brush Settings Editor, but one'd have to know that or discover that, and keeping them visible means sacrificing a sizeable part of screen (like 480p-ish) Just to be able to see a brush size value. It'll also mostly cover a good part of paintable canvas. What the actual hell.
- It's hard to set any value, whether it's a precise value or not. Even just trying to get back to some arbitrary point on that silder will (kinda) fail (it will always be imprecise, just introducing more and more deviation), because there's no value visible, and the slider itself is imprecise completely (even in fine mode, which is basically undiscoverable and kinda broken). Like, i'm not talking "exactly 1.00" (surprisingly hard to set, actually), i'm talking even 'just about the halfway on that slider'. You're not doing that on this slider. (you're doing it in .myb file and never use those sliders ever again /s)
- Setting an exact value is impossible. There's no way to do just that.

I could go on, but like, look at the GIMP and it's value sliders, they're still a bit terrible and their usability is still iffy, but they have much more figured out. Like, they even have a 'reset value' button. (Good thing the brush parameters reset with a single click on that brush button. Just kidding, it's actually terrible.) The only thing they don't have is a dropdown menu with default and custom values, and that's doable in gtk -inkscape has that, but not the custom user values.

**Comment by jplloyd** [comment]
The feature, as it is currently worded, has been added with these commits: 6a2f91a3829d91912fdfd6d0f17f632e3addee48 & 31a072ae6d797ae687dc6154f49db62cfe31343f

The issue of not seeing the value for a slider is somewhat addressed by this commit: 0c722d20c6e6bf97e5febc5413495f1e3056046a

It latter does not, however,  address the issue raised by @fbck about values not always being very meaningful to the user, since they are direct mappings to (the base values of) internal brush settings. Though that can be addressed by having the value map, from and to, the internal value (e.g. showing the actual radius instead of its logarithm), with variable loss of precision, I think that should wait until such mappings are exposed from libmypaint.
