### ISSUE TITLE
Feature Request: Autosave

### ISSUE THREAD

**Issue by AnTi-ArT** [mypaint/mypaint#90]
I don't see it here. So...

### Autosave, please!
Perhaps with on/off and configurable time intervall in the settings.
And an auto backup on crash...

Just because...
![autosaveplz](https://cloud.githubusercontent.com/assets/6949092/4016363/a3c89c04-2a33-11e4-9d58-7ee7be823ae1.jpg)
... and now it's gone.

**Comment by achadwick** [comment]
I've pushed some test branches for background low-priority autosaves in #264, and I think the changes in that PR look good for performance on my systems (but full warning: I've got an SSD here on my main developmnet box. I hope the performance is still good on spinning glass/metal!)

If anyone's able to pull and test that branch (https://github.com/achadwick/mypaint/tree/issue90-autosave-chunked), I'd be super grateful. You'll need to re-run scons because I had to cut up one of the low-level PNG saving routines to make this work.

Performance is king on this. But for me, when I turn on MYPAINT_DEBUG=1 and watch the rate of event delivery for a long continuous freehand stroke started in the middle of a (multi-second) autosave, I don't see any significant drop in the figures at peak.

```
>>>>>>> I start by painting to the layer, then leaving it alone to let autosave begin
DEBUG: lib.layer.data: autosave: scheduled update of u'/home/andrewc/.cache/mypaint/doc.RYewrn/autosave/data/110e595d-ea7b-46d0-9aeb-93e35a3dfff5-strokemap.dat'
DEBUG: lib.tiledsurface: autosave: scheduled update of u'/home/andrewc/.cache/mypaint/doc.RYewrn/autosave/data/110e595d-ea7b-46d0-9aeb-93e35a3dfff5.png'
DEBUG: lib.command: Brushwork: stop_recording: 0.000s, tiles_changed=False
DEBUG: gui.freehand: Processing at 59 events/s (t_avg=0.017s)  <<<< start painting again here, seems OK
DEBUG: gui.freehand: Processing at 200 events/s (t_avg=0.005s)   <<<<< logs seem to bear it out too!
DEBUG: gui.freehand: Processing at 199 events/s (t_avg=0.005s)
DEBUG: gui.freehand: Processing at 199 events/s (t_avg=0.005s)
DEBUG: gui.freehand: Processing at 199 events/s (t_avg=0.005s)
DEBUG: gui.freehand: Processing at 199 events/s (t_avg=0.005s)
DEBUG: gui.freehand: Processing at 199 events/s (t_avg=0.005s)
DEBUG: lib.command: Brushwork: stop_recording: 6.194s, tiles_changed=True
DEBUG: gui.mode: BrushworkModeMixin: checkpoint()
DEBUG: gui.freehand: Processing at 200 events/s (t_avg=0.005s)
DEBUG: gui.freehand: Processing at 130 events/s (t_avg=0.008s)   <<<<<<<< roughly where I stop painting
DEBUG: gui.freehand: Processing at 21 events/s (t_avg=0.079s)   <<<<< this wacom drops to about 20 events/s
DEBUG: gui.freehand: Processing at 21 events/s (t_avg=0.052s)  <<<<< when the nib is off the tablet
DEBUG: lib.command: Brushwork: stop_recording: 6.330s, tiles_changed=True
DEBUG: gui.mode: BrushworkModeMixin: checkpoint()
DEBUG: gui.freehand: Processing at 21 events/s (t_avg=0.115s)
DEBUG: gui.freehand: Processing at 150 events/s (t_avg=0.007s)   <<<<< might have dabbed again here
DEBUG: lib.command: Brushwork: stop_recording: 2.046s, tiles_changed=True
DEBUG: gui.mode: BrushworkModeMixin: checkpoint()
DEBUG: lib.layer.data: autosave: updated u'/home/andrewc/.cache/mypaint/doc.RYewrn/autosave/data/110e595d-ea7b-46d0-9aeb-93e35a3dfff5-strokemap.dat'
```

That's a big layer (45.6 MB PNG file, 16064x8064 pixels), and a big working brush ("classic/coarse bulk 3" dialled up to the maximum radius), so I'm really pleased to see the event rate stays high even between the start and end of the layer snapshot being saved :smile:. Outside an autosave write it's 199 or 200 events/s as well, so for me at least #264 works out.

**Comment by achadwick** [comment]
We'll need a recovery dialog to make this complete. Any suggestions for the UI?

We can present thumbnails, number of layers, and last-changed times, but not the name of the original file right now (if there was one).

Some quick thoughts:

![UI sketch](https://cloud.githubusercontent.com/assets/61299/6766888/9bfff0f2-d010-11e4-84e6-8eefb47b9cf6.png)

**Comment by achadwick** [comment]
In fact I kinda don't want the original file name in there if we can avoid it. These are independent things, and with some recovery dialogs you're left wondering whether your choice will overwrite your original file with something old. Let's restrict it to very safe, very understandable choices.

**Comment by achadwick** [comment]
Restore gui done:

![autosave recover dialog](https://cloud.githubusercontent.com/assets/61299/6838359/cc82ac6e-d34f-11e4-960c-c500276d5919.png)

Looks like the best option is to restore the file, but immediately after that ask the user where they want to save the file.

**Comment by achadwick** [comment]
See PR #264 for more UI relating to this. And: Please Review :D

**Comment by achadwick** [comment]
Added UI for controlling it all (in PR #264)

![Prefs UI for autosave](https://cloud.githubusercontent.com/assets/61299/6932661/9e460afc-d814-11e4-8770-1230990cbe83.png)

The default interval is 10s, and there's a tooltip on the switch explaining that things happen in the background, and that it's for giving you a chance to recover unsaved work.
