### ISSUE TITLE
Fullscreen toggle causes canvas window to shrink (wraps up in a new frame every time)

### ISSUE THREAD

**Issue by mikshaw** [mypaint/mypaint#92]
Pressing F11 to toggle fullscreen creates an additional border within the canvas window each time you leave fullscreen mode. Eventually you get a tiny window and need to restart mypaint to reset.
This has been the case in mypaint-git for several months now.

Debian testing (Jessie) 64-bit, Intel HD4000 graphics, dwm window manager

![14-0822-175116-window](https://cloud.githubusercontent.com/assets/5081349/4018012/d22fc3fc-2a46-11e4-9673-9f63dc55b0c2.png)

**Comment by achadwick** [comment]
Visible in Adwaita for GNOME 3.16 too. Looks like it goes away if we use gtk_container_add() instead of gtk_scrolled_window_add_with_viewport() though - and the latter is deprecated in all cases since GTK 3.8 anyway.

I have a bunch of other gripes with GTK 3.16+: expect fixes soon :)

@mikshaw Yes, please report separate issues separately. But I think you're just not moving the pointer there? (For better or for worse, the autohide timer is implemented, and works for me, but relies on pointer movement events to be started...)

**Comment by mikshaw** [comment]
there is indeed an autohide...it just doesn't work every time on my desktop.  Sometimes when i move the cursor back to the canvas the toolbar hides...sometimes it doesn't. It might be my desktop.

**Comment by mikshaw** [comment]
I want to confirm that with today's commit i no longer see the duplicate frame problem.
Thank you.
