### ISSUE TITLE
Edit Layer in External App not working  correctly

### ISSUE THREAD

**Issue by don570** [mypaint/mypaint#979]
[
#### Basic system details

MyPaint version: mypaint-git-w64-2.0.0-alpha-master.467-installer.exe
Operating system: Windows 10  64 bit

1. Start MyPaint
2.   Choose  Layer  >  Edit Layer in External App
3.   Automatically  chooses built-in  microsoft paint   program  rather  than  KRITA.
There is no  choice.

Previous versions including  version  1.2.1  would  give a list of  apps to choose among.
I would  select  KRITA  because it includes  gmic plugins.

___________________________________________________________________________

**Comment by briend** [comment]
Just wondering, if you right click on a .ORA file, does Windows let you select Krita to open the file?  Wondering if it is application association thing for file types. . .

**Comment by don570** [comment]
> Just wondering, if you right click on a .ORA file, does Windows let you select Krita to open the file? 

> This is new computer (actually a used computer with windows 10 installed  by store)
so I didn't modify anything and I don't think  I even launched ms paint until  recently,  but I did get a list .

I set Krita to open  png files,  but that  doesn't solve  problem.

The earlier  version  of mypaint  1.2.1 will show a list.

**Comment by briend** [comment]
Think I know what's going on.  MyPaint is using the python [os.startfile(](https://docs.python.org/3/library/os.html#os.startfile)"filepath", "edit") to launch the default _editor_ (as opposed to "viewer") for the PNG file type:
https://github.com/mypaint/mypaint/blob/master/gui/externalapp.py#L245

This was related to some bugs introduced by gtk, it seems:
https://github.com/mypaint/mypaint/commit/abdaf83e81cfa5dcc59a0f8c5671ca0e7153d7ce#diff-51cf7ac88bf4654bf7d1c3e83f62807c

Windows doesn't seem to let you set the "edit" action anymore:
https://techjourney.net/windows-file-types-open-edit-actions-associations-advanced-management-tools/

So, the more appropriate action should probably be "open" instead of "edit".   I will look at switching that.  For the meantime you could try to set the "edit" action for PNG with one of those free apps mentioned in the article.  I verified that just running os.startfile(filename, "open") would open the proper associated application.  It does not prompt you anymore with a list of programs, as that was one of the things that was affected by the bug it seems.  We should revisit that too and see if that bug is resolved and we can go back to showing a list again, since that is handy.

**Comment by briend** [comment]
Another way to test this:
Just open this file with a text editor:
C:\Program Files\mypaint-git-w64\mingw64\lib\mypaint\gui\externalapp.py

and change this
        os.startfile(file_path, "edit")
to this:
        os.startfile(file_path)

**Comment by don570** [comment]
> For the meantime you could try to set the "edit" action for PNG with one of those free apps mentioned in the article.

Yes I did that and now  everything  is  working  great!!!  I am  now  using  paint.net  as the external app.
It supports layers and transparency and  gmic plugins.
https://forums.getpaint.net/topic/113564-gmic-3-01-2019/

I changed the  default app for imageviewer  and  the  app to open  PNG  to  paint.net.
**This is the solution.**

I suspect that I caused  some  damage  to my windows 10 install and  this is   what  caused  the
strange  behaviour.    I was  experimenting  with   several versions of KRITA  and I  forgot to  use the 
uninstall program.  I restored  the  program  from  the  trash  and then  used  the uninstall script that Krita supplies.
This  may  have  corrupted  some    windows file  that  tracks  whether  an app is installed or not.

Apparently  my computer  thinks  that  krita  is  not installed even  though it is.  ????

Fortunately  it does know  that  paint.net is installed.   Strangely  a list is not shown.  Instead
it opens  paint.net automatically.

![screenshot-mypaint](https://user-images.githubusercontent.com/19693002/53700295-b0d58100-3de8-11e9-8559-6d3b585aa302.png)


By the  way  I have  just tested  the  latest  version  of  mypaint    in  my  fatdog64  800 linux install
and  it  works  perfectly  with  my wacom  tablet  and   it opens  GIMP  as  the  external  app.
________________________________________________________________________________________________________
