### ISSUE TITLE
[Artwork] New Icon Proposal

### ISSUE THREAD

**Issue by jimmac** [mypaint/mypaint#986]
I'd like to propose an update of style for Mypaint app icon. While the current icon is a great piece of 3D art on its own, the world has moved on from a highly detailed realistic renderings of objects as app icons in all contemporary operating systems.

For more background on the issue feel free to read my two blog posts on app icon design [1][2]

With the new gudelines in mind and the effort to keep the current metaphor, here's my intial design proposal. 

![Mypaint](https://user-images.githubusercontent.com/14821/54353913-89d34680-4655-11e9-85d1-9f3b38ca7c96.png)

![mypain-fullcolor](https://user-images.githubusercontent.com/14821/54353961-ac655f80-4655-11e9-9430-10c7015d8551.png)

Apart from the fullcolor icon, provided as a scalable vector graphic file (the only 'size' it comes from now on), I've updated the symbolic variant of teh app icon to be used mainly by the high contrast/accessible theme.

I usually try to make it effortless for maintainers to incorporate the icon and provide patches[3], but sadly have trouble building master. Thus I am attaching the SVGs only and hope you can find the time to update the build system side of things.

[1] http://jimmac.musichall.cz/blog/2018-07-18-detail-considered-harmful/
[2] http://jimmac.musichall.cz/blog/2019-01-23-the-big-app-icon-redesign/
[3] https://gitlab.gnome.org/GNOME/Initiatives/issues/2

**Comment by jimmac** [comment]
Scalabel and symbolic variants of teh app icon as a zipped archive (contains 2 svg files)
[mypaint-icon.zip](https://github.com/mypaint/mypaint/files/2966173/mypaint-icon.zip)

**Comment by manuq** [comment]
The proposed icon looks great, @jimmac . I hope it lands soon!

**Comment by tjhietala** [comment]
While I like the new Gnome icon style in general, this icon needs improvement, IMO. It doesn't pass the squint test: the shaft of the brush is hard to see and the head of the brush seems more like a giant blueberry. The overall shape of the brush doesn't "pop out". (The initial sketch is much better than the final result in this regard.)

I'm afraid I don't have the vector graphics skills to improve it myself but hope you take this as constructive criticism.

**Comment by odysseywestra** [comment]
@jimmac are you still willing to work on getting this icon improved?

**Comment by jplloyd** [comment]
Original
![org mypaint Mypaint svg](https://user-images.githubusercontent.com/5107852/70695504-26e50d80-1cc2-11ea-9768-4afeca82b180.png)
Adjusted
![org mypaint Mypaint-alt2 svg](https://user-images.githubusercontent.com/5107852/70695425-f69d6f00-1cc1-11ea-890b-6f620195f9dd.png)

[org.mypaint.Mypaint-alt.svg.tar.gz](https://github.com/mypaint/mypaint/files/3954631/org.mypaint.Mypaint-alt.svg.tar.gz)

Here's an alternative version I made a while ago, tweaked to try to make the appearance more brush-like without making it too anemic. I also (just now) tweaked the tapering and colors of the handle a bit (maybe too dark...).
May need additional adjustments.

**Comment by jimmac** [comment]
> @jimmac are you still willing to work on getting this icon improved? I would be much interested in getting this icon updated.

I'll be happy to address any blocking issues that stand in the way of merging it. So far I got "doesn't pop" and "fails squint test" both of which I translate to low contrast which isn't the case.

**Comment by jplloyd** [comment]
@jimmac I think the "doesn't pop" comment just means that the brush looks like it's part of the canvas, and not separate from it. I don't personally think that detracts from the design, and your description clearly states that you're going for a more modern, flatter design without heavy 3D shading.

Squint test just means that it doesn't really look like a brush at a glance (at least in isolation, the wave of paint should make it fairly clear). To me it looks a bit like a rubber ball on a stick.

@tjhietala will have to comment if I've misinterpreted his remarks.

Personally I don't really have a horse in this race, as I don't use icons in my wm, but I do think at least the squint remark is valid (these things are subjective, of course).

**Comment by tjhietala** [comment]
@jplloyd got the idea, but perhaps my explanation was a bit unclear. The problem is that the head of the brush is very big and has a lot of contrast while the shaft is small and has low contrast. So the brush does not look like a brush, or even a single object at a glance. Instead, the paint trail and the head of the brush appear to form a single object, because their values are similar.

@jplloyd I like your alternative version, although I'd still suggest using a bit darker colour for the shaft of the brush (or possibly a bit lighter for the head of the brush).

**Comment by odysseywestra** [comment]
Probably adjusting the highlight do to more fit with a brush will help the overall look. The the abrupt cut-off of the brush doesn't sit right with me personally.

**Comment by jimmac** [comment]
Every time design is done with unclear decision makers and many voices in a public forum, the end result will lose any sort of [unique style touch](https://en.wiktionary.org/wiki/bikeshedding). But let's move things forward --

![image](https://user-images.githubusercontent.com/14821/70846468-cdafe200-1e59-11ea-97fa-41f1a566fd69.png)


Dulled down the stylistic elements to make the brush proportions less exaggerated.

**Comment by odysseywestra** [comment]
Proportions of the handle look much better. Brush head still looks awkward. I'd get rid of the highlight dot and give the brush more of an oval shape. Maybe instead of a gradient from the blue to black add a jagged edge to make it look like paint is coming off the brush.

**Comment by jplloyd** [comment]
Looks fine to me. Still gives me the impression of a bulb horn, but maybe that's just me. On the whole, it's better to have a vector-based icon than a raster icon (side note: the _old_ old icon was an svg, before the current version was created, also by @jimmac, in 2013).

@jimmac Will it bother you a lot if we tweak the icon a bit before/after including it?

**Comment by jimmac** [comment]
The geometric shapes are an attribute of the style and I would recommend against trying organic shapes.

**Comment by jplloyd** [comment]
The tweak I had in mind was to make the "metal" part of the brush just a tad darker so it doesn't meld into the canvas as much, but it's no big deal.

If you post an archive with the new files, I'll update the icons (without modifications) early next week.

**Comment by odysseywestra** [comment]
@jimmac I'm not trying to be rude, but I disagree. MyPaint itself is designed to emulate painting in general so the icon should have some of those traits as well. You can have organic shapes but keep it stylize too. Granted it is a vector image so we can changes it later as well easily too.

If you want to, you can post a copy of it' s current iteration, and I can see what I can come up with.

**Comment by Fatih20** [comment]
@odysseywestra Consistency between gnome apps icon is more important IMO.

**Comment by jplloyd** [comment]
@Fatih20 Many people do not use the GNOME desktop environment, and though MyPaint uses Gtk/Gdk it is not a GNOME app (of course it ships in distros using GNOME, but that's not the same thing).

Anyway, if an archive was posted I would have done the update and called it a day. However, since it didn't happen I made another attempt about a month ago based on the same concept and templates, but with a different brush and stroke (primarily using spiro splines):

![mypaint-icon-attempt-screenshot](https://user-images.githubusercontent.com/5107852/72730636-04cc8e00-3b92-11ea-8e1d-ad1b88a97884.png)

@jimmac I know (and appreciate) that you just made a PR to resolve this, but out of interest I'd like your input on whether this icon would violate any of the new GNOME HIG's in particular?

**Comment by bertob** [comment]
@jplloyd the easel looks good, but the brush doesn't really fit in with the style, primarily because breaks the folded perspective and is too un-geometric and detailed. It looks like it's taken from an icon in a different style. I think that's especially due to the complex geometry and the light reflections.

This blog post of mine gives some in-depth background on how to draw icons in this style in case you're interested https://blogs.gnome.org/tbernard/2019/12/30/designing-an-icon-for-your-app

**Comment by jplloyd** [comment]
@bertob Thank you, that's a nice and comprehensive post. When you say un-geometric, I assume you mean that the geometric complexity deviates too far from a combination of simple shapes.

You are correct about the folded perspective. I personally find the perspective weird-looking when applied to the brush representation, since it makes it look like the brush lies flat against the canvas (or is even leaning in towards it) with paint still emanating from the tip somehow. Still, my version _does_ break consistency, no question about that.

As for level of detail, I guess you would factor the complexity and scale of that detail. Your bookshelf example (and the card/key icon) certainly seem to contain quite a lot of detail, though those details themselves consist of simple shapes.

**Comment by Fatih20** [comment]
Also, the use of organic shapes would be a pain to be pixel fitted to smaller sizes while retaining its meaning. Before making any icon changes, I recommend posting a screenshot of your icon when used in real life without cropping to see if people would actually recognize what the icon is trying to do. Post an uncropped screenshots unlike what jimmac and jplloyd posted.

**Comment by jplloyd** [comment]
> Post an uncropped screenshots unlike what jimmac and jplloyd posted.

@Fatih20 Those aren't cropped screenshots, they're just screenshots taken from the [app icon preview](https://gitlab.gnome.org/World/design/app-icon-preview) application (which to my knowledge _is_ a Gnome app, unlike MyPaint).

**Comment by Fatih20** [comment]
Well, then post a screenshot then. An icon can look good up close, but messy in the big picture.

**Comment by jplloyd** [comment]
@Fatih20 As previously stated, I don't use desktop icons myself. If you are interested in this issue, I suggest you create and post the screenshots. Here's the zipped svg: 
[org.mypaint.MyPaint.MyPaint_export.svg.zip](https://github.com/mypaint/mypaint/files/4088189/org.mypaint.MyPaint.MyPaint_export.svg.zip)

**Comment by Fatih20** [comment]
![image](https://user-images.githubusercontent.com/51940383/72761736-844c7280-3c0f-11ea-93d9-16be138d911b.png)
