### ISSUE TITLE
Edit Frame results in black pixels

### ISSUE THREAD

**Issue by don570** [mypaint/mypaint#993]
MyPaint version: MyPaint---20190322.AppImage
Operating system: fatdog64linux  v800

#### Steps to reproduce
1. Start MyPaint
2.  Open  jpeg image
3. Click on  'Edit Frame' icon at top   of window
4. Open the settings  for 'Edit Frame' feature
5.  Click  'Set Frame to Document'     --->  It will  work  properly -->  Good!!
This is what I want  so I can  save  the  document  with  the  same  size.  However....

6. Click 'Set Frame to Layer'  results in  black  pixels  to right and bottom  of  image

As well...

7. Menu  > Layer > Import Layers
to import another  jpeg

8. Click  on 'Edit  Frame'  and  select the  imported layer .
Now click on 'Set Frame to layer'    --->     results in Black pixels on right and bottom of image.

**Comment by don570** [comment]
I've been  testing   mypaint  by opening  jpeg and png  images.

I've  concluded  that  the best thing  to do  is to make  sure  the frame  is activated  immediately  after
opening  the  image.   In fact I  think  the  mypaint  developers  should  do  this automatically  so
that  the  user  sees  the  frame  and  document  dimensions clearly  when  the  jpeg  is opened.

Shutting  off  the  frame is easy  and  straight forward.
_______________________________________________________________________________________________________

**Comment by jplloyd** [comment]
It seems this has nothing to do with setting the frame size based on layers or documents, rather it's caused by the box shadow used to emphasize the frame. The shadow is present whenever the frame is active, but is more prominent when editing the frame (it's deliberately drawn thicker for emphasis). This is easier to see with a fairly transparent frame colour.

Easiest fix would be to just disable the shadow and assume that the user will use sensible frame colours for emphasis instead.
