### ISSUE TITLE
Suggestion: Use 7z instead of zip for standalone w64 binaries

### ISSUE THREAD

**Issue by Playermet** [mypaint/mypaint#994]
The same files packed to the .7z format (with default settings) has drastically smaller size. To be precise, less then 100MB compared to the original 143MB of the .zip file.

**Comment by jplloyd** [comment]
I'm not up to date on this, but does the built-in archive managers in windows now support 7z? Is it common to install separate pieces of software to decompress 7z on Windows? Those are the only arguments against this I have.

**Comment by Playermet** [comment]
> does the built-in archive managers in windows now support 7z?

Unfortunately, not.

> Is it common to install separate pieces of software to decompress 7z on Windows?

7z format is supported by [almost all archivers](https://en.wikipedia.org/wiki/Comparison_of_file_archivers#Reading) for windows.

**Comment by jplloyd** [comment]
The archive bundling is done via [Styrene](https://github.com/achadwick/styrene/) (created by the MyPaint de-facto lead dev). I've made a PR that adds 7z archiving to it, so hopefully we can make this change before too long.

With the current file sizes, 149 builds/6months would be the limit to avoid hitting the storage cap, so that's another reason to get the sizes down.

**Comment by jplloyd** [comment]
The switch to 7z is now deployed: 706a6a0c0fe7fe0563f72e49ced6ddd12333d241
